### ISSUE TITLE
Catch up :latest tag?

### ISSUE THREAD

**Issue by fryfrog** [wolveix/satisfactory-server#102]
Looks like a number of small issues have been fixed on the `:dev` tag, but not on `:latest`. Would it be crazy to push an update? Mainly I'm thinking of the `STEAMBETA=false` thing, but the new `CRASHREPORT=true` is nice too! :)

**Comment by wolveix** [comment]
Hey! Yeah, I was waiting for the K8s stuff in #98 to be ready :P But I'll make a new release now, as I agree `STEAMBETA` should be in `latest` at least :)
