### ISSUE TITLE
mismatch versjon

### ISSUE THREAD

**Issue by paarak** [wolveix/satisfactory-server#104]
Server versjon  173879

Game versjon is 174005

**Comment by msladek** [comment]
your game client is on the experimental version but your server on early access. as the [README](https://github.com/wolveix/satisfactory-server#readme) suggests set `STEAMBETA` to `true`.

**Comment by paarak** [comment]
thanks. it was a simple stupid me :)

> your game client is on the experimental version but your server on early access. as the [README](https://github.com/wolveix/satisfactory-server#readme) suggests set `STEAMBETA` to `true` and restart the container.
