### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by seek1338** [wolveix/satisfactory-server#108]
Hi,

at first very nice work at all 👍 Thanks

**Describe the Bug**
Use of the Command "FG.DisableSeasonalEvents 1" in the console is not beeing saved after i restart the container. I cant deaktivate the season with produce some lags with 4 players.

**Your Runtime Command or Docker Compose File**
i start it over portainer, so i build the docker run command, and i hope its ok:

docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1000 -e PUID=1000 -e STEAMBETA=false -v statisfactory_config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest

**System Specs (please complete the following information):**
Linux docker 5.10.0-8-amd64 #1 SMP Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux (16 Core & 24GB Ram)

**Additional Context**
i tryed over Docker ENV "FG.DisableSeasonalEvents 1", but i think its not implimented. I also saw, that in the persistens volume "statisfactory_config" the config files are overwritten if i restart the container, but the save files are persistens.

maybe its not an issue? Maybe its a easy call and i dont know it -> im not an docker master :)

thanks

**Comment by msladek** [comment]
Yes, the command settings are overwritten on restart in order to inject values via env variables. The `FG.DisableSeasonalEvents` isn't yet available via env variable. I'm going to add it soon.

Until it's available the following workaround: set the command after every restart in the console and reload the last save game.

**Comment by wolveix** [comment]
Merged :) Please see the `README` for more information, or check the referenced issue #109
