### ISSUE TITLE
Server Never Leaves Offline State After Restart

### ISSUE THREAD

**Issue by rawrgulmuffins** [wolveix/satisfactory-server#110]
**Describe the Bug**
After an update I'm running `docker restart <container_id>`. Before the reboot the server is in the game client shows a version mismatch state but after the reboot the game client only shows "This server appears to be offline."

**Your Runtime Command or Docker Compose File**
```
ec2-user@ip-172-31-44-16 ~ :)% docker ps
CONTAINER ID   IMAGE                                COMMAND      CREATED        STATUS         PORTS                                                                                                                                     NAMES
6045bb930ddb   wolveix/satisfactory-server:latest   "/init.sh"   23 hours ago   Up 6 minutes   0.0.0.0:7777->7777/udp, :::7777->7777/udp, 0.0.0.0:15000->15000/udp, :::15000->15000/udp, 0.0.0.0:15777->15777/udp, :::15777->15777/udp   satisfactory-server
ec2-user@ip-172-31-44-16 ~ :)% docker restart 6045bb930ddb
6045bb930ddb
ec2-user@ip-172-31-44-16 ~ :)% docker ps
CONTAINER ID   IMAGE                                COMMAND      CREATED        STATUS              PORTS                                                                                                                                     NAMES
6045bb930ddb   wolveix/satisfactory-server:latest   "/init.sh"   24 hours ago   Up About a minute   0.0.0.0:7777->7777/udp, :::7777->7777/udp, 0.0.0.0:15000->15000/udp, :::15000->15000/udp, 0.0.0.0:15777->15777/udp, :::15777->15777/udp   satisfactory-server
```

**System Specs (please complete the following information):**
 ```
 ec2-user@ip-172-31-44-16 ~ :)% cat /etc/os-release

NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/
```
 
<img width="1200" alt="Screen Shot 2021-12-02 at 7 39 41 PM" src="https://user-images.githubusercontent.com/1521575/144541316-255eca55-8ba4-4317-b7d8-82eea5a6047a.png">

**Additional Context**
Servers been up for a day now. Had to rebuild the ec2 image after I ran the EBS volume out of space from trying to update the previous day.

**Comment by wolveix** [comment]
Please provide your full runtime command or Docker Compose file. In addition to this, please provide your full server log.

**Comment by rawrgulmuffins** [comment]
Apologies @wolveix but I think I jumped the gun on this one. For some reason I have to remove the server and re-add it on the client side after a reboot but it does find it if I do that after a sufficient amount of time. Not sure why but I do think this is a false attribution on my end.
