### ISSUE TITLE
Rename the v4 docker image tag to something else

### ISSUE THREAD

**Issue by starcraft66** [wolveix/satisfactory-server#112]
Hey, I've been using this project for a while and it's been working flawlessly for me.
There is, however, an annoyance I have uncovered related to docker tags.

Ongoing development seems to be going on using semantic versioning starting at major version 1 which is great, except an outdated and unrelated image tag, v4, is also present.

This is a big problem for automated updated tools like [Renovate](https://github.com/renovatebot/renovate) which inspect the docker image tag and attempt to find new versions using semantic versioning. It's currently impossible to update this image automatically following semver because renovate will always want to upgrade to v4 since it should, in theory be much newer than anything v1.

See this merge request on my infrastructure repo for an example: https://git.tdude.co/tristan/infrastructure/-/merge_requests/68/diffs

I don't have a better tag name to propose for the v4 tag but I'm sure someone could come up with one.

**Comment by wolveix** [comment]
I did remove the `v4` tag from Docker Hub, but frankly forgot about GitHub Packages. This has now been removed. Thanks :)

**Comment by starcraft66** [comment]
Thanks!
