### ISSUE TITLE
Possibility to increase connection timeout for players

### ISSUE THREAD

**Issue by halvors** [wolveix/satisfactory-server#119]
Possibility to increase connection timeout for players, problem is that our game takes so long to save that everyone is disconnected from server.

**Comment by msladek** [comment]
The connection timeouts are already set to 5 minutes https://github.com/wolveix/satisfactory-server/blob/main/Engine.ini#L15-L16

Arre you sure the save takes longer than that or could it be another issue?

**Comment by wolveix** [comment]
Is your issue that you get disconnected while waiting to join in the first place? In which case, this is a semi-known issue with the official server. Unfortunately, there's nothing that we can do about that.

**Comment by halvors** [comment]
@wolveix Yeah found that is was 5 mins, saves are not taking that long so have to be something else. I suspected that it somehow had something to do with 2 players leaving at the same time or that a player leaved while saving, the server just got stuck saving and where unjoinable.

So i tried to turn off the autosave on disconnect option, that seems to have solved it.
So considering that i think we can close this issue, you agree?

**Comment by wolveix** [comment]
Now that's interesting. Yeah, this does sound like a game bug, so there's nothing we can do about it. Thank you for reporting it though!
