### ISSUE TITLE
"Disk write failure" during setup

### ISSUE THREAD

**Issue by krmedia** [wolveix/satisfactory-server#12]
During the installation this error occurs. I can reproduce this error on several systems of different hardware. I have tried several locations (home, root, /var/lib/docker/volumes,...) and have also run chmod -R 777 on all data inside and outside the container.

Is the issue related to this ticket? https://githubmemory.com/repo/PufferPanel/PufferPanel/issues/977

Any ideas why this error occurs during deployment?

**Comment by wolveix** [comment]
Hi! Thanks for trying out this repo.

Please provide your full runtime log, as well as your host system specs (CPU, OS etc.)

Thanks!

**Comment by krmedia** [comment]
[terminal_output.txt](https://github.com/wolveix/satisfactory-server/files/6626406/terminal_output.txt)
[docker-compose.yml.txt](https://github.com/wolveix/satisfactory-server/files/6626407/docker-compose.yml.txt)

Host-System 1:
OS: Windows Version 10.0.19042 Build 19042
Processor: AMD Ryzen 9 5900X 12-Core Processor, 4175 MHz
RAM: 32GB
Docker-Engine v20.10.6


Host-System 2:
Ubuntu-Server 21.04
Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
RAM 8GB

**Comment by wolveix** [comment]
Thank you. Just to rule it out, could you try deploying the Docket Compose file as `root`?

**Comment by krmedia** [comment]
I already did on both systems. The logs i send to you are from root user ;)

**Comment by wolveix** [comment]
Hah, damn! Well, this is frustrating. I've just moved house so things are a little hectic right now, but I'll do what I can to investigate this issue. Firstly I need to try and re-create it on my end, which I've been unable to achieve so far.

**Comment by krmedia** [comment]
All right. Thanks for being on it ;) I also already tried to start the container via docker run ...., same result. If you need a live reproduction, I can offer you a screenshare session as soon as we both have time.

**Comment by BeardedIntern** [comment]
Hey, had the same problem with my container ([see this mess I made](https://github.com/wolveix/satisfactory-server/issues/11)). 
And either I am more of an arcanist than I thought or it had to do with the directory from where I executed the docker-compose command.
When it finally worked again I was in the same directory the docker-compose.yml is located in _and_ where I wanted the bind to the /config to be. I really don't know if that _should_ make a difference or if it made a difference at all, but that, somehow, worked for me.

Cheers.

**Comment by krmedia** [comment]
So for some reason it has now worked for me too. As much as it bothers me as a developer that I can't say exactly why it works now, I'm just as happy that it does :D 

Here is my approach:
1. create the container with docker run ...
2. error occurs
3. delete container
4. restart system
5. authorize already created folder with chmod 777
6. docker run... run again
7. worked for me after that....


Thanks for your efforts and work for this cool project.

@BeardedIntern This really looks like a healthy mess :D Try my steps. If I find the time, I'll be happy to take a look at your problem as well.


Many warm regards!

**Comment by krmedia** [comment]
Solved. Unclear cause, see last comment.
