### ISSUE TITLE
No one can log in except me...

### ISSUE THREAD

**Issue by ryclos** [wolveix/satisfactory-server#123]
Hello all

**Describe the Bug**
I can to connect, create the map and enter in the game, but when someone want to join he can't, and in the docker logs I don't see the connection attemp, just my ip public adresse.
Do you know how can I fix this bug ?
Thank you per advance 

**Your Runtime Command or Docker Compose File**
sudo su -
docker-compose up -d
![unknown-18](https://user-images.githubusercontent.com/9601851/154014793-7678ab73-8b6b-465a-8bba-b58366322f54.png)

**System Specs (please complete the following information):**
 - OS: Debian 11 Server

**Additional Context**
It's a Host server "So you start"

**Comment by MichaelGreenNZ** [comment]
Have you Port Fowarded in your Modem?

**Comment by ryclos** [comment]
> Have you Port Fowarded in your Modem?

Hello and thank you for your response!
It's a hoster in Canada, but i live far away on a island, and i can connect on the server...
So yes i think it's open.

docker logs satisfactory-server :
[docker logs satisfactory-server.txt](https://github.com/wolveix/satisfactory-server/files/8073825/docker.logs.satisfactory-server.txt)

netstat -paunt :
![image](https://user-images.githubusercontent.com/9601851/154130331-3e9580a9-f144-4f16-9807-96b077d394b8.png)

In the game after create etc :
![unknown (1)](https://user-images.githubusercontent.com/9601851/154131449-017d0d15-90e5-4c85-9d10-0cc1d3349ed5.png)


Maybe i need to copy this Engine.ini, Game.ini and Scalability.ini in the config volume ?
If yes, where exactly in the config ? : 
https://satisfactory.fandom.com/wiki/Multiplayer#Engine.ini

It's little crazy why the others can't join lol

**Comment by ryclos** [comment]
Ok it's fixed sorry it's about my ui server  :
![image](https://user-images.githubusercontent.com/9601851/154166883-e4f5bb62-f546-40cc-9b7d-ad6fe6cc4c81.png)

Thank you very much
