### ISSUE TITLE
No saved files in \saves, \gamefiles, \backups.  Could really use some help

### ISSUE THREAD

**Issue by Helias7700** [wolveix/satisfactory-server#124]
First, Wolveix, WOW!! Excellent docker setup.  Works really well; was able to load previous saved games into the "c:\...\saved" folder on host, loaded it into the server perfectly.  Server runs good all is well, except, none of the new saves are being saved from the container to the "\saved" folder on the local host.  They are mapped in docker, but no game files, no backups, nothing.  Beyond frustrating and I'm new to docker and the like.  Is it possible to mount the host folders again (i.e. c:\...\config\saves to /saves on the container) without losing the current saves on the container?  There are many, many hours on the saves in the container but I have no access to them on the host to back them up.  

I would be super grateful if it's possible to get the saves off the container and onto the host.  Thank you for your time, I really appreciate it.

Environment
PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USER
steam
HOMEDIR
/home/steam
STEAMCMDDIR
/home/steam/steamcmd
AUTOPAUSE
true
AUTOSAVEINTERVAL
300
AUTOSAVENUM
3
AUTOSAVEONDISCONNECT
true
CRASHREPORT
true
DEBUG
false
DISABLESEASONALEVENTS
false
GAMECONFIGDIR
/config/gamefiles/FactoryGame/Saved
GAMESAVESDIR
/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
MAXPLAYERS
4
PGID
1000
PUID
1000
SERVERBEACONPORT
15000
SERVERGAMEPORT
7777
SERVERIP
0.0.0.0
SERVERQUERYPORT
15777
SKIPUPDATE
false
STEAMAPPID
1690800
STEAMBETA
false
Mounts
/HOME/STEAM/STEAMCMD
/var/lib/docker/volumes/56f9b05dbe3daaf5071aea3fb2c02add0acd8759250429c815dd6249b4103164/_data
/SAVES
C:\Users\MTCL\.docker\config\saves
/BACKUPS
C:\Users\MTCL\.docker\config\backups
/GAMEFILES
C:\Users\MTCL\.docker\config\gamefiles
Ports
15000/udp
0.0.0.0:15000
15777/udp
0.0.0.0:15777
7777/udp
0.0.0.0:7777

**System Specs (please complete the following information):**
 -Windows 11
-Docker for Windows

**Comment by wolveix** [comment]
Hey! I'm just about to head to sleep (I'm in the UK), but I just wanted to comment to say don't panic! Your saves should absolutely be within the container :) I can't remember the appropriate directories off of the top of my head, but it's likely that something either outside or inside of the container has been incorrectly mapped (we had to do some symlinking to get around some hardcoded config stuff in CSS's server). I will get back to you tomorrow with something more meaningful :) 

Also, thank you so much for the kind words!

**Comment by Helias7700** [comment]
Thank you so much Wolveix!  I really appreciate your time!  Thank you again!  I look forward to hearing from you.

**Comment by wolveix** [comment]
Sorry for getting back to you so late! It's been a busy day. Would you mind sharing what your Docker run or `docker-compose.yml` looks like, please? Just helps to get an idea of what is and isn't mapped :) 

Also, could you exec into the container and run `ls -lah /home/steam/.config/Epic/FactoryGame/Saved/SaveGames`, please? You should be able to open command prompt (`WIN + R`, `cmd`), and run `docker exec -it satisfactory-server /bin/bash` to enter the container (assuming that your container name is `satisfactory-server` and not something else.

**Comment by wolveix** [comment]
Hey @Helias7700! Were you able to get this working?

**Comment by wolveix** [comment]
I'm going to close this, but feel free to re-open if the issue persists :)
