### ISSUE TITLE
FYI: Helm charts available

### ISSUE THREAD

**Issue by Truxnell** [wolveix/satisfactory-server#129]
Hey all,

Just a little note to let you know a helm chart for running this Satisfactory docker on k8s is now avaliable:

https://github.com/k8s-at-home/charts/tree/master/charts/stable/satisfactory
https://artifacthub.io/packages/helm/k8s-at-home/satisfactory

Literally just a FYI, you can close this one anytime.

**Comment by wolveix** [comment]
Hey @Truxnell, thanks for opening the issue! If anyone would be willing to submit a PR to merge the charts here or add info to the README, I'd be happy to merge it :)

**Comment by Truxnell** [comment]
Thanks @wolveix, i've poped in a PR to add some lite info to the readme.  Its probably best to leave the k8s-at-home chart in the repo as it relies on the k@h-common-chart (also why I created this, as i love the k@h common chart!)

**Comment by wolveix** [comment]
Thanks for creating a PR @Truxnell! I'll merge it when I have a second to review it :D

**Comment by wolveix** [comment]
Thanks for your work on this @Truxnell! Sorry it took so long to get this merged :)

**Comment by Truxnell** [comment]
@wolveix All good no issue!
