### ISSUE TITLE
Error! App '1690800' state is 0x602 after update job.

### ISSUE THREAD

**Issue by Platypuschan** [wolveix/satisfactory-server#131]
**Describe the Bug**
When i start the container, it end with the log entry: "Error! App '1690800' state is 0x602 after update job.", checking the files in the volume reveales the download is still incomplete, game binary missing and stuff... Downloading the game files manually with steamcmd (with another container) and copying the game binarys to the satisfactory_data-volume and starting the container is working.... 

**Your Runtime Command or Docker Compose File**
docker run -d 
--name=satisfactory-server 
-h satisfactory-server 
-e MAXPLAYERS=4 
-e PGID=1002 
-e PUID=1002 
-e STEAMBETA=false 
-v satisfactory_data:/config 
-p 7777:7777/udp 
-p 15000:15000/udp 
-p 15777:15777/udp wolveix/satisfactory-server:latest

**System Specs (please complete the following information):**
===== START ISSUE REPORT =====
OS:  Linux SmallServer 5.4.0-110-generic #124-Ubuntu SMP Thu Apr 14 19:46:19 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
RAM: 22GB/23GB
HDD: 12GB/234GB (6% used)
===== END ISSUE REPORT =====

**Additional Context**
Error! App '1690800' state is 0x602 after update job.

**Comment by wolveix** [comment]
Hi @Platypuschan, apologies I've only just seen this.

0x602 is a SteamCMD issue which occurs if your device loses internet connectivity for 5 or more seconds during the download/update phase. This isn't something I can do anything about, unfortunately.

Source: https://stackoverflow.com/questions/57758797/steamcmd-app-state-is-0x602-after-update-job

**Comment by AdamLMark** [comment]
Happening again! There's a new issue for it: https://github.com/wolveix/satisfactory-server/issues/371
