### ISSUE TITLE
Option to have /gamefiles mapped to a seperate location

### ISSUE THREAD

**Issue by Silver-Golden** [wolveix/satisfactory-server#132]
Hi there!

So currently in ``/config`` there is ``/config/gamefiles`` where teh games files are stored..

Would it be possible to split it out like:

```yml
volumes:
   - '/path/to/config:/config'
   - '/path/to/gamefiles:/gamefiles'
```

The reason why I am requesting it is to make it easier to do backups on everything else in ``/config``

**Comment by wolveix** [comment]
Hey! Thanks for taking the time to open this request :) 

You _should_ be able to map something like the following and achieve what you want (I haven't tested it):
```
volumes:
   - '/path/to/config:/config'
   - '/path/to/gamefiles:/config/gamefiles'
```

**Comment by Silver-Golden** [comment]
That worked perfectly.  
I had some doubts thinking that the contents of ``gamefiles`` would still be inside ``/config/gamefiles`` but that turned out to not be the case.

Tree output for anyone else sceptical:

```terminal
[nix-shell:~]# tree /etc/silver_satisfactory -L 3
/etc/silver_satisfactory
├── config
│   ├── backups
│   ├── gamefiles
│   ├── saves
│   └── ServerSettings.15777
└── gamefiles
    ├── Engine
    │   ├── Binaries
    │   ├── Content
    │   ├── Plugins
    │   ├── Programs
    │   └── Saved
    ├── FactoryGame
    │   ├── Binaries
    │   ├── Content
    │   └── Saved
    ├── FactoryServer.sh
    ├── launcher_id
    ├── linux64
    │   └── steamclient.so
    ├── Manifest_DebugFiles_Linux.txt
    ├── Manifest_NonUFSFiles_Linux.txt
    ├── steam_appid.txt
    ├── steamapps
    │   ├── appmanifest_1690800.acf
    │   ├── downloading
    │   └── temp
    └── steamclient.so

19 directories, 9 files
```
(files previously showed up under ``/config/gamefiles`` but now its empty)
