### ISSUE TITLE
Issue with initial Start up 

### ISSUE THREAD

**Issue by dusi90** [wolveix/satisfactory-server#145]
**Describe the Bug**
Network Problem while startup the new Docker Image (latest)!
I can ping everything from the Server so i think the Internet connection ist working fine

**Your Runtime Command or Docker Compose File**
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/Satisfactory/config:/config'
        environment:
            - MAXPLAYERS=8
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
            - AUTOPAUSE=false
        restart: unless-stopped

**Log:**
Creating satisfactory-server ... done
Attaching to satisfactory-server
satisfactory-server    | Checking available memory...15GB detected
satisfactory-server    | Setting autosave number to 3
satisfactory-server    | Setting crash reporting to True
satisfactory-server    | Setting max players to 8
satisfactory-server    | Setting autosave interval to 300s
satisfactory-server    | Setting disable seasonal events to 0
satisfactory-server    | Setting network quality number to 3
satisfactory-server    | Setting auto pause to False
satisfactory-server    | Setting autosave on disconnect to True
satisfactory-server    | Checking available space...335GB detected
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | CWorkThreadPool::StartWorkThread: Thread creation failed.
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | CWorkThreadPool::StartWorkThread: Thread creation failed.
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | [----] Verifying installation...
satisfactory-server    | [  0%] Downloading update...
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
satisfactory-server    | /home/steam/steamcmd/steamcmd.sh: line 39:    45 Segmentation fault      (core dumped) $DEBUGGER "$STEAMEXE" "$@"
satisfactory-server exited with code 254

Pulling satisfactory-server (wolveix/satisfactory-server:latest)...
latest: Pulling from wolveix/satisfactory-server
214ca5fb9032: Pull complete
75d8433c3ef0: Pull complete
4f4fb700ef54: Pull complete
d2aa24cc1f2e: Pull complete
27831c5cb639: Pull complete
2f4263696451: Pull complete
f4a981822c13: Pull complete
Digest: sha256:973fda5ddf04c1df4ca3fbaccc3abf0df80419047b38ec0104e5b27f5903b5d0
Status: Downloaded newer image for wolveix/satisfactory-server:latest
Creating satisfactory-server ... done
Attaching to satisfactory-server
satisfactory-server    | Checking available memory...15GB detected
satisfactory-server    | Setting autosave number to 3
satisfactory-server    | Setting crash reporting to True
satisfactory-server    | Setting max players to 8
satisfactory-server    | Setting autosave interval to 300s
satisfactory-server    | Setting disable seasonal events to 0
satisfactory-server    | Setting network quality number to 3
satisfactory-server    | Setting auto pause to False
satisfactory-server    | Setting autosave on disconnect to True
satisfactory-server    | Checking available space...336GB detected
satisfactory-server    | Downloading the latest version of the game...
satisfactory-server    | Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | CWorkThreadPool::StartWorkThread: Thread creation failed.
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | CWorkThreadPool::StartWorkThread: Thread creation failed.
satisfactory-server    | src/tier0/threadtools.cpp (4122) : Probably deadlock or failure waiting for thread to initialize.
satisfactory-server    | Thread failed to initialize
satisfactory-server    | [----] Verifying installation...
satisfactory-server    | [  0%] Downloading update...
satisfactory-server    | [  0%] Checking for available updates...
satisfactory-server    | [----] !!! Fatal Error: Steamcmd needs to be online to update. Please confirm your network connection and try again.
satisfactory-server    | src/common/workthreadpool.cpp (612) : pWorkThread->m_bFinished is false but thread is not running
satisfactory-server    | src/common/workthreadpool.cpp (612) : pWorkThread->m_bFinished is false but thread is not running
satisfactory-server    | CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
satisfactory-server exited with code 139

**System Specs:**
OS:  Linux vmd26514.contaboserver.net 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
RAM: 15GB/16GB
HDD: 36GB/392GB (10% used)

**Additional Context**
Can someone help me? 
Thanks to all

**Comment by wolveix** [comment]
Please see #143
