### ISSUE TITLE
[Game bug] Missing how to join as "host"

### ISSUE THREAD

**Issue by cslotterback** [wolveix/satisfactory-server#15]
Is there any documentation on how to join the dedi as the host once it's up and running? There are some issues in scheduling automated routes in multiplayer that only the host is able to perform with the current version of the game.

**Comment by wolveix** [comment]
Hi there!

There's no way to join as the host while using the dedicated server, as the host is the server itself. To perform host actions, you need to download the save from the server, load it using your local machine, do whatever you need to do, then go upload the save back to the server.

This is a limitation of the game, and not the server.implementation. So unfortunately, there's nothing that can be done about it until they fix the host-only actions. I can't say I've found it to be an issue personally.

**Comment by cslotterback** [comment]
I assumed as much, that’s how we got around it the first time. One thing I noticed is that booting the container using the updated savefile in mounted config, the container would load the old save and overwrite the new one. Got around this by copying the new savefile directly into the running container and restarting it worked.

**Comment by wolveix** [comment]
@cslotterback the container should grab the save file with the latest modified date. If you grabbed the save while the server was still running and only stopped the server before uploading the modified save, then the latest server-generated save could have had a later modified date.
