### ISSUE TITLE
SteamCMD not able to finish update

### ISSUE THREAD

**Issue by NiourK** [wolveix/satisfactory-server#150]
**Describe the Bug**
My Docker installation is not able to update anymore.
I am using the truecharts Apps embedded in TrueNAS scale, il was working fine last week-end, I update it on Friday evening to 1.3.1_2.0.38, and it can not start anymore, crashing on the update process.

**System Specs (please complete the following information):**
The host is TrueNas Scale (tried 22.02.3 and 22.02.4) - I added the Truecharts repository and installed the server from there.
```

OS: Linux satisfactory-server 5.10.131+truenas x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
RAM: 32 GB (26 available)
HDD: TrueNAS zvol with 2x HGST_HDN724040ALE640 (in RAID 1)

```

**Additional Context**
The container itself can access Internet ( can ping outside of my network and can resolve DNS).
As you can see in the logs The download is starting but failing at some point, and never succesfully finish.
RAM and Disk's space are available.

SteamCMD on windows seems running fine and can access the update server without issues.

Not sure where to find the Runtime Command.

Hope this could help other people.

[satisfactory-server_satisfactory-server-6dc56d989c-bbgs8_satisfactory-server.log](https://github.com/wolveix/satisfactory-server/files/9692933/satisfactory-server_satisfactory-server-6dc56d989c-bbgs8_satisfactory-server.log)

**Comment by wolveix** [comment]
Hey :) Could you please provide your logs? You refer to them, but haven't provided them.

Additionally, your runtime command would be the CLI command or Compose file, but you're using charts. I have no idea how that works really as I'm not the author of those charts.

**Comment by NiourK** [comment]
Sorry log uploaded

**Comment by wolveix** [comment]
Thanks for including the log. Sorry though, this does indeed appear to be network-related, and unrelated to anything unusual we may do within this repo. Please try deploying another SteamCMD server to verify this. If you're able to deploy others, I'll happily look further into this issue for you. I'd recommend trying the Valheim server (`lloesche/valheim-server`), but any server utilizing SteamCMD.

**Comment by NiourK** [comment]
alright keep you updated soon.

Thanks for being so quick to answer.

**Comment by NiourK** [comment]
Damn, you are right, Valheim Server is providing the same issue.

Sorry for reporting this invalid issue !
And Thanks for your work !


[valheim-server_valheim-server-db957b499-gmdlw_valheim-server.log](https://github.com/wolveix/satisfactory-server/files/9692960/valheim-server_valheim-server-db957b499-gmdlw_valheim-server.log)

**Comment by wolveix** [comment]
@NiourK no worries at all! I hope you're able to figure out the issue :) If you do, please do mention it here for any others that may stumble across this issue :D

**Comment by LoganAvatar** [comment]
Following on here. I just had this same issue ... updating packages on the host (centos 7) seemed to fix it. Not entirely sure why the container incompatibility, but it works now.

**Comment by NiourK** [comment]
Thanks Logan for following on this issue.
I updated both Valheim and Satisfactory App.

It's seems, it has been fixed on Valheim Server App but not on Satisfactory server App (both still provided by Truecharts repository on Truenas Scale host.
