### ISSUE TITLE
Needing gc.MaxObjects

### ISSUE THREAD

**Issue by AvisCeler** [wolveix/satisfactory-server#151]
Your Image is great, but we need to edit the engine.ini because of to many UObjects. Any Chances? 

PROBLEM:

```
CommonUnixCrashHandler: Signal=11
[2022.10.13-08.23.29:945][826]LogCore: === Critical error: ===
Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x0000000000000003

[2022.10.13-08.23.29:945][826]LogCore: Assertion failed: Result + NumToAdd <= MaxElements [File:Runtime/CoreUObject/Public\UObject/UObjectArray.h] [Line: 538] 
Maximum number of UObjects (2162688) exceeded, make sure you update MaxObjectsInGame/MaxObjectsInEditor/MaxObjectsInProgram in project settings.
```

OUR WORKAROUND:

```
[/Script/Engine.GarbageCollectionSettings]
gc.MaxObjectsInEditor=8000000
gc.MaxObjectsInGame=8000000
```

BUT HERE: the configfiles are being overwritten, and protected:

```
cp: cannot create regular file '/config/gamefiles/FactoryGame/Saved/Config/LinuxServer/Engine.ini': Permission denied
```

**Comment by AvisCeler** [comment]
That would be great! We build something very big. Savefile has 25 MB at the moment, mayby 40-50 MB at the end. Factotiess spread over the world and especially dedicated server can handle it quit well. I have testet your container with an older 18 MB save of the world (just under the 2 million object limit) and it was working like a charme. So i am very optimistic, that a docker container would be the best choise for our larger project. Same for other people, who have much to build ;) I don't know if or how much a raised limit would effect smaller saves, but at some point there is no other way to continue a world with thousands of hours of gameplay. The limit is standard for the unreal engine, right? but Satisfactory as an building game isn't a standard use of that engine^^

Thanks for your passion, looking forward to hearing from you.

**Comment by wolveix** [comment]
I left the limit default as it is since I read that it can cause save corruption in certain edge cases. But I've made the value user configurable with the `MAXOBJECTS` environment variable :) Let me know if you encounter any issues!

**Comment by AvisCeler** [comment]
awsome! Now it loads correctly. 25 MB Save cause 21 GB RAM for Docker :D Loadingtimes could be better, buts thats another thin. Problem solved. Thank you for the fast support!

**Comment by wolveix** [comment]
@AvisCeler I'm glad to hear it!

I just pushed more performance tweaks today. They may improve your experience as well :)
