### ISSUE TITLE
Missing Saves

### ISSUE THREAD

**Issue by Mmedved6** [wolveix/satisfactory-server#152]
Good afternoon.
I am a beginner and my English is not the best quality))
First I wanted to thank you for your work.

**Describe the Bug**

While the server was running, windows rebooted.
Further, when starting the server, going into the game, it says - create a new game, the server is not busy.
Those. I understand the server has retired and saved. There are no saves through the game menu.

Going to the server's terminal to access the saves:
```
> ls -lah
total 8.0K
drwxr-xr-x 2 steam steam 4.0K Oct 22 06:43 .
drwxr-xr-x 4 steam steam 4.0K Oct 13 13:27 ..
lrwxrwxrwx 1 steam steam 28 Oct 22 06:43 ServerSettings.15777 -> /config/ServerSettings.15777
lrwxrwxrwx 1 steam steam 13 Oct 22 06:43 server -> /config/saves

> cd server
> ls -lah
total 0
drwxr-xr-x 2 steam steam 40 Oct 22 06:18 .
drwxr-xr-x 5 steam steam 120 Oct 22 06:20 ..
```

Going to the /SaveGames_backup folder there are saves.
Maybe a very stupid question. Sorry. Can't transfer saves from /SaveGames_backup to /SaveGames
I think it's possible))?

Is it possible to additionally prescribe that SaveGames_backup was also saved in Windows?

Thank you for your attention

**Your Runtime Command or Docker Compose File**
Docker

**System Specs (please complete the following information):**
```
OS: Linux satisfactory-server 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
RAM: 5GB/14GB
HDD: 2GB/251GB (1% used)
```

**Environment**
```
MAXPLAYERS=4
PGID=1000
PUID=1000
STEAMBETA=false
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
USER=steam
HOMEDIR=/home/steam
STEAMCMDDIR=/home/steam/steamcmd
AUTOPAUSE=true
AUTOSAVEINTERVAL=300
AUTOSAVENUM=3
AUTOSAVEONDISCONNECT=true
CRASHREPORT=true
DEBUG=false
DISABLESEASONALEVENTS=false
GAMECONFIGDIR=/config/gamefiles/FactoryGame/Saved
GAMESAVESDIR=/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
NETWORKQUALITY=3
SERVERBEACONPORT=15000
SERVERGAMEPORT=7777
SERVERIP=0.0.0.0
SERVERQUERYPORT=15777
SKIPUPDATE=false
STEAMAPPID=1690800
```

Mounts
/CONFIG
/path/to/config

Ports
15000/udp
0.0.0.0:15000

15777/udp
0.0.0.0:15777

7777/udp
0.0.0.0:7777

**Comment by wolveix** [comment]
Hi, could you please fill out the issue template? It provides a lot of the information necessary to troubleshoot your issue. Thanks!

**Comment by wolveix** [comment]
Apologies, I've just realised you're not using Docker. It's very hard to troubleshoot your issues when you're not using Docker, as the image handles most of the issues that you're extremely likely to run into. How are you currently running everything? Which scripts are you running? Have you made any modifications?

**Comment by Mmedved6** [comment]
Sorry, I guess I didn't express myself well.
I did it through docker.
In the topic, he indicated that it was not the docker that disappeared, but the game server when I started the game itself.

I'm editing the thread now

**Comment by wolveix** [comment]
@Mmedved6 you said in the issue title that you weren't using Docker? Okay, I'm with you now. Could you please fill out the issue template requirements? They make troubleshooting much easier :) https://github.com/wolveix/satisfactory-server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by Mmedved6** [comment]
> @Mmedved6 you said in the issue title that you weren't using Docker? Okay, I'm with you now. Could you please fill out the issue template requirements? They make troubleshooting much easier :) https://github.com/wolveix/satisfactory-server/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

Of course, sorry again. **updated**

**Comment by wolveix** [comment]
@Mmedved6 no need to apologise! :) Could you also post your runtime command/`docker-compose.yml` file? Essentially, how are you running the image? If it's through Docker for Desktop interface, could you paste a screenshot of your environment variables (though you have already included those, so it's optional) as well as your mounts?

**Comment by Mmedved6** [comment]
> @Mmedved6 no need to apologise! :) Could you also post your runtime command/`docker-compose.yml` file? Essentially, how are you running the image? If it's through Docker for Desktop interface, could you paste a screenshot of your environment variables (though you have already included those, so it's optional) as well as your mounts?

I run through Docker Desktop.
if I understood correctly.
I can't find the path /path/to/config

Mounts
/CONFIG
/path/to/config

**Comment by wolveix** [comment]
Ah. If you didn't specify a config directory mount, then that would be why your saves are gone. You need to specify a local directory for the container's `/config` directory. On a Linux host, this would be something like `/opt/satisfactory-server` or `/home/steam/satisfactory-server`

**Comment by Mmedved6** [comment]
Did everything according to the manual.
https://github.com/wolveix/satisfactory-server
![image](https://user-images.githubusercontent.com/41422925/197466031-2527229e-3957-4986-8552-ed346cc0d176.png)

Folder /opt/ empty
/home/steam/ folder satisfactory-server does not exist

**Comment by wolveix** [comment]
@Mmedved6 sorry, I think you're misunderstanding me. You need to create a local directory, and then reference it there. I'm unfortunately not sure on how this process works through Docker for Desktop. When I use Docker on Windows, I use WSL2 which means I can use it from the terminal.

But essentially, that's all your issue is. You're not providing a directory, so your data is lost whenever the container state changes. Please research bind mounts on Windows, or look into volumes. Additionally, make sure to bind it specifically to `/config`, not `/CONFIG`.

**Comment by wolveix** [comment]
If there are saves in the backup folder, then move them to somewhere safe, and just upload them via the in-game server manager once you've started the server

**Comment by Mmedved6** [comment]
@wolveix 
Good afternoon.
I think you can close the topic. You helped me a lot.
Somehow I didn’t think of unloading saves from the docker.
Since there is still not enough navaka to make it so that saves are written directly to the hard drive. I will make a script that will simply copy 2 folders to the hard drive)

**Comment by egoodchild** [comment]
This is on synology, not windows FWIW.  I think CONFIG was default in the container.  I can do it for both cases I guess :)
