### ISSUE TITLE
Add TIMEZONE as enviromental variable for correct server time

### ISSUE THREAD

**Issue by ThaMighty90** [wolveix/satisfactory-server#158]
Hello wolveix,

first of all thank you for this amazing docker container.

Would it be possible to pass an Enviromental Variable for the local timezone in the style of Europe/Berlin etc.?
I am often online in the evening and because of FICSMAS right now i always have to stay on to at least 1am to open the calender door because my timezone differs one hour from the server. Or in other words the server is one hour behind my actual local time.

Cheers,
Thamighty

**Comment by wolveix** [comment]
Hey @ThaMighty90! I appreciate the kind words :) Docker images support `TZ` by default, but I should add that to the `README` for clarity. 

So you should be able to specify `-e TZ=London/Europe` for example :)

**Comment by ThaMighty90** [comment]
Wow, thanks for the quick answer. Didn't even know that every docker image supports the `TZ` variable.
Thanks.
