### ISSUE TITLE
savefile.sav not being updated

### ISSUE THREAD

**Issue by Drauku** [wolveix/satisfactory-server#16]
Hello, and thanks for publishing this game server.

I have the server running, but would like to change save game files. I replaced the `savefile.sav` inside `/config/savefile/` with my new world, but the old world keeps being loaded. I searched for other .sav files, but was unable to find any outside of the container. Even after deleting the `/config/` data and the container, the old `savefile.sav` is still loaded.

After reading through the dockerfile, it seems like any `/config/savefile/*.sav` files are all copied into the GameSave folder on container startup, but that is not the result I am seeing.

Am I missing something obvious? Do you have a suggestion for how I could fix this? Again, thanks for sharing your work.

**Comment by Drauku** [comment]
Update: After doing a complete `docker system prune` and removing all containers and volumes, the new save file was loaded.

Shouldn't whichever file was placed in the `/config/savefile/` folder be the one loaded on container start though?

**Comment by wolveix** [comment]
Hey!

Yeah, the container should pull the file with the latest modified timestamp from your mapped directory. My best guess is that there was a file within the container with a newer timestamp. Easy to fix on my end.

Thank you for bringing this to my attention!
