### ISSUE TITLE
mv error in container after last container update

### ISSUE THREAD

**Issue by nergdron** [wolveix/satisfactory-server#169]
**Describe the Bug**
mv error in container after last container update

**Your Runtime Command or Docker Compose File**
I'm running in nomad, and so my job file looks like this:
```hcl
job "satisfactory" {
  type = "service"
  datacenters = ["cad1"]
  group "satisfactory" {
    count = 1
    network {
      port "game" {
        static = 7777
      }
      port "beacon" {
        static = 15000
      }
      port "query" {
        static = 15777
      }
    }

    task "satisfactory" {
      driver = "docker"
      config {
        image = "wolveix/satisfactory-server"
        network_mode = "host"
        ports = ["game", "beacon", "query"]
        privileged = true
        mount {
          type = "bind"
          source = "/var/lib/nomad/volumes/satisfactory"
          target = "/config"
        }
      }
      env {
        MAXPLAYERS = 8
      }
      resources {
        cpu = 8000
        memory = 12000
      }

      service {
        name = "satisfactory"
        port = "game"
        check {
          type = "tcp"
          interval = "10s"
          timeout = "3s"
        }
        check_restart {
          limit = 3
          grace = "2m"
          ignore_warnings = true
        }
      }
    }

    restart {
      mode = "delay"
      attempts = "3"
      delay = "30s"
      interval = "2m"
    }
  }
}
```

**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux c1 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 7 2700X Eight-Core Processor
RAM: 1GB/32GB
HDD: 119GB/566GB (21% used)
===== END ISSUE REPORT =====
```

**Additional Context**
everything works the same as normal, but when the container finishes updates and stuff, I get the following:

```
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 4.54 (323295159 / 7119060920)
 Update state (0x5) verifying install, progress: 15.42 (1097966851 / 7119060920)
 Update state (0x5) verifying install, progress: 28.68 (2041593046 / 7119060920)
 Update state (0x5) verifying install, progress: 43.71 (3111766446 / 7119060920)
 Update state (0x5) verifying install, progress: 58.36 (4154584323 / 7119060920)
 Update state (0x5) verifying install, progress: 71.19 (5068242622 / 7119060920)
 Update state (0x5) verifying install, progress: 82.04 (5840269622 / 7119060920)
 Update state (0x5) verifying install, progress: 92.53 (6587056321 / 7119060920)
Success! App '1690800' fully installed.

mv: missing file operand
Try 'mv --help' for more information.
```

not really sure what it's trying to mv that isn't working, but it seems to be broken. I'm also seeing the following error further up in the logs:

```
Redirecting stderr to '/home/steam/.steam/logs/stderr.txt'
/tmp/dumps is not owned by us - delete and recreate
Unable to delete /tmp/dumps. Continuing anyway.
```

**Comment by wolveix** [comment]
Hey @nergdron. I'm not familiar with Nomad whatsoever, but I can't replicate this issue on my end. My best guess is that since you're not specifying an image tag (which you should be), you're pulling one of the older migration commits. Try specifying `v1.4.4` to ensure that this isn't the issue

**Comment by nergdron** [comment]
nomad just pulls `latest` if you don't specify a tag, but I'll try a tagged release and see how it goes... yeah, same issue with the explicit tag for `v1.4.4`.  I see the migration code in `run.sh`, and that appears to be the only place the mv command runs, so I do think you're right that it's something around migration, which means my on disk structure is likely in a weird state...

ahhh I had an empty directory `/config/saves/76561197980236361/`, and that was breaking that save file migration stuff. removing that dir fixed that error, but now I'm getting other problems:

```
Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
sh: 1: xdg-user-dir: not found
```

I think that there was probably a previous migration that didn't work so well, and so now my game dir state is all messed up. if I just remove my mounted config dir it'll probably sort itself out, I imagine. let's see. nope. with a fresh `/config` directory mounted, I still get the about project and `xdg-user-dir` errors. oh well, at least this problem is fixed.
