### ISSUE TITLE
Unable to Connect to Server

### ISSUE THREAD

**Issue by Nereg** [wolveix/satisfactory-server#17]
Hi! I am trying to run the server on a Linux machine. And I can't connect to it! [Here](https://prnt.sc/1g96jo8) is a screenshot of what the client is saying. Also I found those interesting line in logs of the server:
```
[2021.07.26-18.18.01:452][  1]LogOnlineIdentity: Warning: OSS: EOS-OSS: Unable to AutoLogin user (0) due to missing auth command line args
[2021.07.26-18.18.01:452][  1]LogOnlineIdentity: Warning: OSS: EOS-OSS: Login(0) failed with EOS result code (EOS_InvalidAuth)
[2021.07.26-18.18.01:452][  1]LogGameSession: Warning: Autologin attempt failed, unable to register server!
[2021.07.26-18.18.01:452][  1]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.07.26-18.18.01:452][  1]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.07.26-18.18.01:453][  1]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
```
How I can fix it ? I downloaded latest game version and latest image version.
I am running :
`Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3`
`Linux 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by wolveix** [comment]
Hey! Thanks for opening an issue :) 

Could you provide your full Docker run/Compose file, please? Obviously redact anything sensitive.

**Comment by Nereg** [comment]
I tried to use bash to debug it but I couldn't connect to it:
`docker run -d --name=satisfactory-server -h satisfactory-server -e STEAMUSER=*** -e STEAMPWD=*** -e STEAMCODE=*** -e MAXBACKUPS=10 -v $(pwd):/config -p 7777:7777/udp wolveix/satisfactory-server:latest bash`

**Comment by wolveix** [comment]
Thanks for providing that information!

Could you try `rm -rf steam` from the mapped directory, then try running the container?

**Comment by Nereg** [comment]
Still the same. Here is logs:
```
[2021.07.26-19.13.32:684][  0]LogOnline: Warning: OSS: [EOS SDK | Plugin] Begin Player Session...
[2021.07.26-19.13.32:685][  0]LogEngine: GameWindow did not exist.  Was created
[2021.07.26-19.13.32:687][  0]LogSlate: Updating window title bar state: overlay mode, drag disabled, window buttons hidden, title bar hidden
[2021.07.26-19.13.32:687][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.07.26-19.13.32:688][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.07.26-19.13.32:688][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.07.26-19.13.32:688][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.07.26-19.13.32:688][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.07.26-19.13.32:688][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.07.26-19.13.32:688][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.07.26-19.13.32:689][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.07.26-19.13.32:689][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.07.26-19.13.32:689][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
[2021.07.26-19.13.32:689][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
[2021.07.26-19.13.32:689][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
[2021.07.26-19.13.32:689][  0]LogInit: Display: Game Engine Initialized.
```
But the steam folder was recreated by the container

**Comment by wolveix** [comment]
The errors showing there are normal and not an issue, the login issue in your original log was. Is the container actually stopping now? Because it should continue running with the server working as expected.

**Comment by Nereg** [comment]
Maybe the issue is with firewall. Because  I can't  reach other server too. 
The container doesn't stop by the way

**Comment by wolveix** [comment]
Sounds like the container is running correctly then :) What happens when you try to connect to it from your client?

**Comment by Nereg** [comment]
[Here](https://prnt.sc/1givsri) is screenshot of client error.

**Comment by wolveix** [comment]
It seems like you have a networking issue on the server itself. Are you able to spin up a web server container? Apache or Nginx would suffice. This is just to verify whether the port is externally accessible. 

Interesting that Nmap doesn't show anything. Is there anything custom with your Docker setup?

**Comment by Nereg** [comment]
[Here](https://pastebin.com/2Jn8xh1F) you are. I will try to spin up a server there. I also will reinstall the docker because I did delete some docker network interface while trying to fix this.

**Comment by wolveix** [comment]
Is the http server running over Docker? Also, did you provide your own game save when spinning up the server?

**Comment by Nereg** [comment]
Yes I used [this](https://hub.docker.com/r/tutum/hello-world/) docker image to test the 7777 port. And yes the account owns satisfactory

**Comment by wolveix** [comment]
It's not a case of whether you own the game; did you generate a save on your client and then upload the save to the server prior to starting the container?

**Comment by Nereg** [comment]
Yes I generated a save (not a new one but a world I was playing in). Maybe I should make a clear one ?

**Comment by wolveix** [comment]
Port 27015 doesn't need to be open, and your existing world should be fine. This is a strange one to be honest with you! I'm curious as to why the port doesn't appear to be open for you. Could you show the output of `lsof -i -n | grep 7777` please?

**Comment by wolveix** [comment]
Also, from your client, try running the following command: `nmap -p 7777 your.ip.address

**Comment by silverfox0000** [comment]
lsof -i -n | grep 7777
    
    docker-pr  47928            root    4u  IPv4 174210      0t0  TCP *:7777 (LISTEN)
    docker-pr  47939            root    4u  IPv4 176225      0t0  UDP *:7777

   #

    nmap -sU -p 7777 ***.**.***.***
    Starting Nmap 7.91 ( https://nmap.org ) at 2021-07-28 09:23 RTZ 2 (ceia)
    Nmap scan report for ***.**.***.*** (***.**.***.***)
    Host is up (0.051s latency).

    PORT     STATE         SERVICE
    7777/udp open|filtered cbt

    Nmap done: 1 IP address (1 host up) scanned in 0.86 seconds

**Comment by Nereg** [comment]
Here is `lsof`
```
lsof -i -n | grep 7777
docker-pr 544508            root    4u  IPv4 605667      0t0  UDP *:7777
```
Here is `nmap`:
```
Starting Nmap 7.80 ( https://nmap.org ) at 2021-07-28 11:34 MSK
Nmap scan report for *****
Host is up (0.00066s latency).

PORT     STATE         SERVICE
7777/udp open|filtered cbt

Nmap done: 1 IP address (1 host up) scanned in 0.34 seconds
```

**Comment by wolveix** [comment]
@silverfox0000 if you're experiencing a similar issue, please either wait until this one is resolved (as the solution should address your issue as well) or at least provide some information about what you're seeing (e.g.: is it identical to the issue that @Nereg is experiencing)? Please don't just respond to my question to someone else as it can make the issue a little confusing :) 

@Nereg everything looks good there honestly, so I'm running out of ideas. I've tested this with a number of providers and have had zero issues. To rule out client-side issues, could you try connecting to `17.satisfactory-server.github.wolveix.com` within Satisfactory?

**Comment by Nereg** [comment]
I can connect to it !
(Though I spawn under the map)

**Comment by wolveix** [comment]
Huh, definitely a server-side issue then. Does your server provider have a firewall in-place? If you don't mind disclosing it, who is your server provider?

**Comment by Nereg** [comment]
Well the provider is [msk.host](https://msk.host/products/vds) (sadly they don't have English version of their site).
Also I tired to run another game server and it wasn't working too. Maybe anti-DDoS solution is blocking some ports? I am working with provider's support to create some exceptions to it. I think so because I can communicate with the game server (UDP) but it will stop responding after a short while. 
And I run docker under root but maybe I should give the container more privileges?

**Comment by wolveix** [comment]
Yeah, I reckon that they're probably filtering your traffic, especially since you can communicate with the server for a moment before it drops out. So either their network is poor, or the more likely option is that they're just filtering your traffic.

If you're running the container under `root`, then there's nothing more that needs to be done there. So for now, I believe this issue is with your host and not the implementation :) Please let me know how you get on with your host!

@silverfox0000 same applies to you; if you're able to connect to `17.satisfactory-server.github.wolveix.com` within Satisfactory, then it's definitely a server-side issue. If you're running the container as `root` and have no obvious errors in the container's runtime log, then there's a good chance that your server provider is the issue (or something network-related, e.g.: a firewall on your server or on your provider's network). Please feel free to provide additional information so that I can try to assist you further.

**Comment by Nereg** [comment]
They want a dump of network activity on 7777 to add to their anti-DDoS thing. This is crazy. Why they can't just disable it ?

**Comment by Nereg** [comment]
I recorded some traffic thanks to your `17.satisfactory-server.github.wolveix.com` server but `7777` port is still closed.

**Comment by wolveix** [comment]
If they're unable to assist you further, unfortunately I'd be inclined to recommend an alternative host, or change the port to something else as Satisfactory _should_ still work, you'll probably just need to append the port onto the end of the IP when trying to connect.

**Comment by Nereg** [comment]
Yes I changed the host and everything works fine! Thank you !
