### ISSUE TITLE
NAS Permissions Error: `preserving permissions for ‘/config/backups/.’: Operation not permitted`

### ISSUE THREAD

**Issue by Nevah5** [wolveix/satisfactory-server#170]
**Describe the Bug**
I run the container with any user, and I get this error. It worked before, but I don't know how I managed to do it.

```
cp: preserving permissions for ‘/config/backups/.’: Operation not permitted
```

**Your Runtime Command or Docker Compose File**
![image](https://user-images.githubusercontent.com/77238295/215336573-4f1ff46f-3798-48c8-9b6c-e762263532b5.png)

**System Specs:**
```
===== START ISSUE REPORT =====
OS:  Linux nas 5.10.142+truenas #1 SMP Mon Sep 26 18:20:46 UTC 2022 x86_64 GNU/Linux
CPU: AMD Ryzen 5 5600G with Radeon Graphics
RAM: 16GB/63GB
HDD: 2GB/444GB (1% used)
===== END ISSUE REPORT =====
```
(HDD is my OS drive, I run everything on my zfs drives.)

**Additional Context**
As I mentioned, It worked before, when I ran it on my HDDs. Then I moved everything onto the SSDs, and from there on I had those issues. Maybe it relates to #44 but I'm not sure. I have some Linux knowledge but I am not a master in it.

Also I'm fine with running it as root, because I use a VPN to connect to the server. This should be pretty secure.

**Comment by Nevah5** [comment]
Also I'm sorry if this is not a bug. I'm out of ideas of what I'm doing wrong here.

**Comment by wolveix** [comment]
Hey @Nevah5, this is probably due to the migration code we added due to the game adding a directory for persistent blueprints.

I'm not sure why it isn't working for you, but you could just manually move the files and you should be good. For now though, could you please upload your log file for the container?

**Comment by Nevah5** [comment]
Thanks for the quick response @wolveix 

I didn't want to manually move the save/blueprints into the container, because if I stop the container, the files are gone. Also I assume the container stops after the error occurs, so I bet the issue also persists with the other folders.

Here are the logs: 
[satisfactory_satisfactory-ix-chart-669f759f9-b886x_ix-chart.log](https://github.com/wolveix/satisfactory-server/files/10530249/satisfactory_satisfactory-ix-chart-669f759f9-b886x_ix-chart.log)

**Comment by wolveix** [comment]
@Nevah5 I'm a little confused as to what you mean. Your message implies that you have an instance of the container that's running fine that  you don't want to stop?

Also, I'm not saying to move the files into the container (though they would be copied back regardless), I'm saying that your mapped directory on the host is probably in the wrong format, hence why the migration code is trying to correct this. This is the correct structure:
```
- /config -> /config
- /config/blueprints -> /config/saved/blueprints
- /config/saves -> /config/saved/server
```

I'd recommend backing up your existing directory on your host (`/mnt/applications/satisfactory`), then make the adjustments listed above. Make sure to fully move/remove the old directories, otherwise the migration code will still trigger.

**Comment by wolveix** [comment]
Wait I'm wrong, this has nothing to do with the migration code, but with the backup code instead. I'm on my phone right now so couldn't look at your log, but will jump on a computer in a few minutes

**Comment by Nevah5** [comment]
> Wait I'm wrong, this has nothing to do with the migration code, but with the backup code instead. I'm on my phone right now so couldn't look at your log, but will jump on a computer in a few minutes

The logs are probably not very helpful. Let me check something, I will inform you if it has worked.

**Comment by Nevah5** [comment]
> ```
> - /config -> /config
> - /config/blueprints -> /config/saved/blueprints
> - /config/saves -> /config/saved/server
> ```

Alright, I've tried the following:
![image](https://user-images.githubusercontent.com/77238295/215340424-132a4c6a-908a-4975-9008-0ce632ad488d.png)

It seems to work. Maybe I just have to map the /config's sub folders.

```
root@nas[/mnt/applications/satisfactory/saves]# ls
test_autosave_0.sav
```

**Comment by Nevah5** [comment]
Hmm, mapping every sub folder of /config, doesn't work. I still get the same error `cp: preserving permissions for ‘/config/backups/.’: Operation not permitted`.

```
/mnt/applications/satisfactory/backups:/config/backups
/mnt/applications/satisfactory/gamefiles:/config/gamefiles
/mnt/applications/satisfactory/saved:/config/saved
```

But mounting it like
```
/mnt/applications/satisfactory/gamefiles:/config/gamefiles
/mnt/applications/satisfactory/saved:/config/saved
```
works.

@wolveix

**Comment by wolveix** [comment]
That's interesting. I'm not surprised given that you're using some form of NAS, and they have annoying permissions configurations. So everything is working correctly for you now?

**Comment by wolveix** [comment]
Oh the reason that works is because you're not maintaining backups anymore. It's not too important, as it only backs up the saves on container start. But that's why nonetheless

**Comment by wolveix** [comment]
@Nevah5 the latest release will fix this (https://github.com/wolveix/satisfactory-server/releases/tag/1.4.5). Pull the latest image in a few minutes, and switch back to only binding the `/config` directory

**Comment by Nevah5** [comment]
Yup, it fixed the error.

Thanks a lot!

**Comment by Nevah5** [comment]
@wolveix can you setup github sponsoring?
I don't want to pay £2 of fees on paypal.

**Comment by wolveix** [comment]
@Nevah5 I really appreciate the interest! I put off doing it before because I didn't have the time, but I've just submitted my application to GitHub. Once it's approved, I'll ping this and #47 :D As always, I do this work for free and don't expect any sponsorships. But they're always appreciated! :)

**Comment by Nevah5** [comment]
> @Nevah5 I really appreciate the interest! I put off doing it before because I didn't have the time, but I've just submitted my application to GitHub. Once it's approved, I'll ping this and #47 :D As always, I do this work for free and don't expect any sponsorships. But they're always appreciated! :)

Oh yeah, I forgot that you have to apply for that. Well I just wanted to say thanks with something small. I always appreciate someone who is maintaining something that is open-source for free.

**Comment by wolveix** [comment]
@Nevah5 I've added a sponsorship option to my GitHub profile. As a reminder, it's not expected nor required, though it's definitely appreciated! Thanks for using the project :D
