### ISSUE TITLE
Game.ini and Engine.ini appear to be default values.

### ISSUE THREAD

**Issue by rrbailey89** [wolveix/satisfactory-server#173]
Thanks for this!

Just seeking clarification.

The engine.ini and game.ini values for this on the server appear to be the default values. Scalability.ini reflects the recommendations in the wiki. 

I'm running this on Ubuntu.

**Comment by wolveix** [comment]
Hey @rrbailey89 :)

I'm not sure what you're asking here. The `Engine.ini` and `Game.ini` config files have the default values in them at the file-level, but are modified using environment variables on the server's startup.

**Comment by wolveix** [comment]
Closing this for now. Feel free to re-open if needed :)
