### ISSUE TITLE
Doesn't Launch On ARM

### ISSUE THREAD

**Issue by Sushi-Mampfer** [wolveix/satisfactory-server#174]
**Describe the Bug**
When running on arm I get back just a string and the logs just say:
exec /init.sh: exec format error

**Your Runtime Command or Docker Compose File**

docker run --platform=linux/amd64 -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=4 -e PGID=1002 -e PUID=1002 -e STEAMBETA=false -v /home/steam/satisfactory/config:/config -m 16G --memory-reservation=12G -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux main 5.15.0-1030-oracle #36-Ubuntu SMP Wed Feb 15 05:57:14 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
CPU: Neoverse-N1
RAM: 23GB/23GB
HDD: 4GB/97GB (5% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Maybe I’m just to dumb to search the internet, but I couldn’t find anything that says —platform=linux/amd64 doesn’t work how I’m expecting it.

**Comment by RisedSky** [comment]
i recommend to do the following : https://github.com/kocxyz/ServerDocker/issues/2#issuecomment-1589106935

**Comment by kaitlynkittyy** [comment]
> i recommend to do the following : [kocxyz/ServerDocker#2 (comment)](https://github.com/kocxyz/ServerDocker/issues/2#issuecomment-1589106935)

I'm running into the same issue and it seems like you may be able to help. I did set it up the way mentioned. It runs until it says "Downloading the latest version of the game..." and then it crashes with no extra logs.

(I'm using podman on my server if that causes any issues lmk)

**Comment by RisedSky** [comment]
> > i recommend to do the following : [kocxyz/ServerDocker#2 (comment)](https://github.com/kocxyz/ServerDocker/issues/2#issuecomment-1589106935)
> 
> I'm running into the same issue and it seems like you may be able to help. I did set it up the way mentioned. It runs until it says "Downloading the latest version of the game..." and then it crashes with no extra logs.
> 
> (I'm using podman on my server if that causes any issues lmk)

Try not to use podman, try a blank run just to be sure it does work without podman to know if it's the main issue

**Comment by wolveix** [comment]
@kaiserdj yes, that's due to Steam.
