### ISSUE TITLE
Startup stuck at PacketHandler

### ISSUE THREAD

**Issue by Dezaku** [wolveix/satisfactory-server#176]
**Describe the Bug**
I set up a new user and created the docker image via docker-compose
When running `docker-compose up` everything seems to work fine but it's stuck at
```PacketHandlerLog: Loaded PacketHandler component:Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)```
**Your Runtime Command or Docker Compose File**
```version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/home/satisfactory:/config'
        environment:
            - MAXPLAYERS=4
            - PGID=1001
            - PUID=1001
            - STEAMBETA=false
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 31G
            reservations:
              memory: 31G
  ```
              
**System Specs (please complete the following information):**
```
===== START ISSUE REPORT =====
OS:  Linux pDocker01 5.15.104-1-pve #1 SMP PVE 5.15.104-1 (2023-03-29T15:51Z) x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 7 1700X Eight-Core Processor
RAM: 30GB/32GB
HDD: 36GB/49GB (77% used)
===== END ISSUE REPORT =====
```
LOGS: https://pastebin.com/KgcY0MJU

**Comment by wolveix** [comment]
Hey there! That's the normal end of the log prior to any connections. I've just checked with my own, the server sits at that line until I connect to it through the in-game server browser. If you're unable to reach the server, then it's most likely an issue with your networking setup.

**Comment by Dezaku** [comment]
> Hey there! That's the normal end of the log prior to any connections. I've just checked with my own, the server sits at that line until I connect to it through the in-game server browser. If you're unable to reach the server, then it's most likely an issue with your networking setup.

yeah I was dumb and forgot to set up port forwading, the server is now shown to me ingame however it says "inactive" and I get a timeout when trying to connect. Could it have to do with the server or client?

![image](https://user-images.githubusercontent.com/68233398/230610869-462e65f8-ed28-46ea-a560-b22b26926c34.png)

**Comment by wolveix** [comment]
Happens to the best of us :) 

Have you done the following via the in-game server manager:
- Claimed the server?
- Loaded a save?
- Waited for the save to finish loading prior to connecting?

**Comment by Dezaku** [comment]
Sadly the error pops up before the window for claiming does

**Comment by wolveix** [comment]
Hmm, perhaps try clearing your mapped directory (`/home/satisfactory`)?

**Comment by Dezaku** [comment]
I've completely cleared it, created a new config directory and server directory where I created a new docker container but I still time out before I can connect for whatever reason

**Comment by wolveix** [comment]
That's strange. Are you running experimental in your client, but not on the server? I don't think that would produce this problem, but you never know.

Can you see your connection attempt in the server logs when you open Satisfactory on your client? If not, I'd guess that there's still a networking issue. What does your setup look like exactly?

**Comment by Dezaku** [comment]
Okay I finally fixed it, my setup is proxmox with pfsense as firewall and a vm for docker containers. It's my first time with this setup and while I had set up port forwarding set up for 15777 I didn't think of doing the same for 7777 and 15000.
I really thank you for your help even tho it had nothing to do with your docker image!

**Comment by wolveix** [comment]
Ah nice one, I'm glad you got it figured out! No worries at all, I'm happy to help :)
