### ISSUE TITLE
How Do I Set Timeout In `engine.ini`

### ISSUE THREAD

**Issue by warpander** [wolveix/satisfactory-server#177]
I wanted to change the engine.ini the time out but with every server restart the ini. Overwritten and rolled back...

If the file is set to read-only, the server will not start...

**Comment by wolveix** [comment]
Hey.

It's intended that you make these changes via environment variables (I believe you're looking for `TIMEOUT`). We already set a lot of defaults based on user feedback.

If you did want to manually edit the `ini` files directly, just create a volume mount for each file to:

```
/home/steam/filename.ini
```
