### ISSUE TITLE
`TIMEOUT` env-var to high

### ISSUE THREAD

**Issue by DenuxPlays** [wolveix/satisfactory-server#181]
**Describe the Bug**
Hey I noticed that the `TIMEOUT` var's default value is set to 300 and personally I think this is too high.
When I or my friends timeout of the server we need to wait 5min otherwise satis will spawn us as a "new" player by the hub and with an empty inventory.
I changed it and set it to 30 without having any problems.

**Your Runtime Command or Docker Compose File**
```bash
sudo docker run \
--sig-proxy=false \
--name=satisfactory-server \
--restart unless-stopped \
--hostname satisfactory-server \
-v /home/timon/satisfactory-config:/config \
-e MAXPLAYERS=4 \
-e PGID=1000 \
-e PUID=1000 \
-e STEAMBETA=false \
-e TIMEOUT=30 \
-e AUTOPAUSE=false \
--memory-reservation=12G \
-m 16G \
-p 7777:7777/udp \
-p 15000:15000/udp \
-p 15777:15777/udp \
wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux winchester 6.2.11-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 13 20:27:09 UTC 2023 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU D-1521 @ 2.40GHz
RAM: 17GB/31GB
HDD: 68GB/893GB (8% used)
===== END ISSUE REPORT =====
```

**Additional Context**
Occurred very late in the game when the server started too struggle.
(Lategame with maxed hub but not maxed space elevator)

We should consider lowering the value to 30 or similar to fix this issue.
Also have anyone else noticed this issue?

**Comment by wolveix** [comment]
Hey! Thanks for opening this issue :) I seem to recall it being set so high to circumvent an issue from the original implementation (this repo existed before CSS released the official dedicated server). There's a good chance then that whatever this workaround was, is no longer necessary.

I'll see if I can remember the exact issue as well as test a lower value locally to see whether anything obvious crops up.

**Comment by DenuxPlays** [comment]
Okay great :)

**Comment by wolveix** [comment]
Finally got around to changing this, thanks :)
