### ISSUE TITLE
Update 8 Consumes Considerably Lower Memory

### ISSUE THREAD

**Issue by DenuxPlays** [wolveix/satisfactory-server#198]
Hey,
I updated my Server to update 8 and I noticed a big improvement on RAM usage.
My server (with 2 players and about 80% things done) needs 3,5GB RAM.
Here:
![image](https://github.com/wolveix/satisfactory-server/assets/83671398/acc1abd7-13af-4354-82be-33a33a5b9938)

The performance is okay...
Not as good as in update 7 but this is expected.

**Comment by wolveix** [comment]
@DenuxPlays thanks for the information! I'd noticed this too :D Until it hits early access, I'll leave the information as-is in the README. Feel free to open a PR to be merged when this happens!
