### ISSUE TITLE
Experimental Fails To Launch: DLSS

### ISSUE THREAD

**Issue by Lipora** [wolveix/satisfactory-server#204]
**Describe the Bug**

**Your Runtime Command or Docker Compose File**
Please censor anything sensitive.

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
echo "===== START ISSUE REPORT =====
OS:  $(uname -a)
CPU: $(lscpu | grep 'Model name:' | sed 's/Model name:[[:space:]]*//g')
RAM: 

MemTotal:       32863684 kB
MemFree:        25244300 kB
MemAvailable:   31994608 kB

Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              3.2G  1.1M  3.2G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   48G   14G   32G  30% /
tmpfs                               16G     0   16G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  253M  1.6G  14% /boot
tmpfs                              3.2G  4.0K  3.2G   1% /run/user/1000
overlay                             48G   14G   32G  30% /var/lib/docker/overlay2/dc49e65831bad86ecec25c09c357ba7012f9e68cbae407a5d1a2de709f68eb1c/merged

**Additional Context**
Add any other context about the problem here.
Sill post logs here as to where I get too in the load.  Just need to properly collect them.

**Comment by Lipora** [comment]
This seems to be the relevant portion of the startup logs:
Can provide full log file if needed.


[----] Verifying installation...
Steam Console Client (c) Valve Corporation - version 1691628584
-- type 'quit' to exit --
Loading Steam API...dlmopen steamservice.so failed: steamservice.so: cannot open shared object file: No such file or directory
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.08 (4194304 / 5141792214)
 Update state (0x5) verifying install, progress: 7.83 (402514132 / 5141792214)
 Update state (0x5) verifying install, progress: 16.34 (840403987 / 5141792214)
 Update state (0x5) verifying install, progress: 26.08 (1341225050 / 5141792214)
 Update state (0x5) verifying install, progress: 35.51 (1825746207 / 5141792214)
 Update state (0x5) verifying install, progress: 45.09 (2318212002 / 5141792214)
 Update state (0x5) verifying install, progress: 54.56 (2805245584 / 5141792214)
 Update state (0x5) verifying install, progress: 64.24 (3303046472 / 5141792214)
 Update state (0x5) verifying install, progress: 74.07 (3808358921 / 5141792214)
 Update state (0x5) verifying install, progress: 83.77 (4307481097 / 5141792214)
 Update state (0x5) verifying install, progress: 93.52 (4808700425 / 5141792214)
Success! App '1690800' fully installed.
Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
5.1.1-247367+++FactoryGame+rel-main-0.8.0 1008 3
Disabling core dumps.
LogInit: Display: Running engine for game: FactoryGame
LogInit: Display: Project file not found: /config/gamefiles/FactoryGame/FactoryGame.uproject
LogInit: Display: 	Attempting to find via project info helper.
LogUProjectInfo: Found projects:
LogPakFile: Display: Found Pak file ../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak attempting to mount.
LogPakFile: Display: Mounting pak file ../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak.
LogPakFile: Display: Mounted Pak file '../../../FactoryGame/Content/Paks/FactoryGame-LinuxServer.pak', mount point: '../../../'
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +0:00, Platform Override: ''
LogInit: Session CrashGUID >====================================================
         Session CrashGUID >   UECC-Linux-68F6C3E55E0649C6933E8B034B353AB7
         Session CrashGUID >====================================================
LogAssetRegistry: Premade AssetRegistry loaded from '../../../FactoryGame/AssetRegistry.bin'
LogConfig: Warning: Found a deprecated ini section name in ../../../FactoryGame/Config/DefaultEngine.ini. Search for [/Script/Engine.TextureLODSettings] and replace with [GlobalDefaults DeviceProfile]
LogConfig: Warning: Found a deprecated ini section name in ../../../FactoryGame/Config/DefaultDeviceProfiles.ini. Search for [/Script/Engine.TextureLODSettings] and replace with [GlobalDefaults DeviceProfile]
LogPluginManager: Warning: Engine version string in ../../../FactoryGame/Plugins/DLSS/DLSS.uplugin could not be parsed ("5.1")
LogPluginManager: Warning: Engine version string in ../../../FactoryGame/Plugins/NIS/NIS.uplugin could not be parsed ("5.1")
LogPluginManager: Warning: Engine version string in ../../../FactoryGame/Plugins/XeSS/XeSS.uplugin could not be parsed ("5.1")
LogPluginManager: Mounting Engine plugin Paper2D
LogPluginManager: Mounting Engine plugin AISupport
LogPluginManager: Mounting Engine plugin EnvironmentQueryEditor
LogPluginManager: Mounting Engine plugin ControlRigSpline
LogPluginManager: Mounting Engine plugin ControlRig
LogPluginManager: Mounting Engine plugin IKRig
LogPluginManager: Mounting Engine plugin Bridge
LogPluginManager: Mounting Engine plugin CameraShakePreviewer
LogPluginManager: Mounting Engine plugin GameplayCameras
LogPluginManager: Mounting Engine plugin LensDistortion
LogPluginManager: Mounting Engine plugin OpenColorIO
LogPluginManager: Mounting Engine plugin OodleNetwork
LogPluginManager: Mounting Engine plugin DSTelemetry
LogPluginManager: Mounting Engine plugin AnimationSharing
LogPluginManager: Mounting Engine plugin PluginUtils
LogPluginManager: Mounting Engine plugin UObjectPlugin
LogPluginManager: Mounting Engine plugin AssetManagerEditor
LogPluginManager: Mounting Engine plugin BlueprintHeaderView
LogPluginManager: Mounting Engine plugin EditorScriptingUtilities
LogPluginManager: Mounting Engine plugin FacialAnimation
LogPluginManager: Mounting Engine plugin GeometryMode
LogPluginManager: Mounting Engine plugin LightMixer
LogPluginManager: Mounting Engine plugin ObjectMixer
LogPluginManager: Mounting Engine plugin SequencerAnimTools
LogPluginManager: Mounting Engine plugin SpeedTreeImporter
LogPluginManager: Mounting Engine plugin EnhancedInput
LogPluginManager: Mounting Engine plugin DatasmithContent
LogPluginManager: Mounting Engine plugin GLTFExporter
LogPluginManager: Mounting Engine plugin VariantManagerContent
LogPluginManager: Mounting Engine plugin AutomationUtils
LogPluginManager: Mounting Engine plugin BackChannel
LogPluginManager: Mounting Engine plugin BlueprintStats
LogPluginManager: Mounting Engine plugin ChaosCaching
LogPluginManager: Mounting Engine plugin ChaosClothEditor
LogPluginManager: Mounting Engine plugin ChaosCloth
LogPluginManager: Mounting Engine plugin ChaosEditor
LogPluginManager: Mounting Engine plugin ChaosNiagara
LogPluginManager: Mounting Engine plugin ChaosSolverPlugin
LogPluginManager: Mounting Engine plugin ChaosUserDataPT
LogPluginManager: Mounting Engine plugin ChaosVehiclesPlugin
LogPluginManager: Mounting Engine plugin CharacterAI
LogPluginManager: Mounting Engine plugin Dataflow
LogPluginManager: Mounting Engine plugin FullBodyIK
LogPluginManager: Mounting Engine plugin GeometryCollectionPlugin
LogPluginManager: Mounting Engine plugin GeometryScripting
LogPluginManager: Mounting Engine plugin Iris
LogPluginManager: Mounting Engine plugin Landmass
LogPluginManager: Mounting Engine plugin PlanarCut
LogPluginManager: Mounting Engine plugin PlatformCrypto
LogPluginManager: Mounting Engine plugin ProxyLODPlugin
LogPluginManager: Mounting Engine plugin PythonScriptPlugin
LogPluginManager: Mounting Engine plugin RawInput
LogPluginManager: Mounting Engine plugin UVEditor
LogPluginManager: Mounting Engine plugin Niagara
LogPluginManager: Mounting Engine plugin AlembicImporter
LogPluginManager: Mounting Engine plugin InterchangeEditor
LogPluginManager: Mounting Engine plugin ImgMedia
LogPluginManager: Mounting Engine plugin MediaCompositing
LogPluginManager: Mounting Engine plugin MediaPlate
LogPluginManager: Mounting Engine plugin MfMedia
LogPluginManager: Mounting Engine plugin MeshPainting
LogPluginManager: Mounting Engine plugin TcpMessaging
LogPluginManager: Mounting Engine plugin UdpMessaging
LogPluginManager: Mounting Engine plugin ActorSequence
LogPluginManager: Mounting Engine plugin LevelSequenceEditor
LogPluginManager: Mounting Engine plugin MovieRenderPipeline
LogPluginManager: Mounting Engine plugin SequencerScripting
LogPluginManager: Mounting Engine plugin TemplateSequence
LogPluginManager: Mounting Engine plugin EOSShared
LogPluginManager: Mounting Engine plugin OnlineBase
LogPluginManager: Mounting Engine plugin OnlineFramework
LogPluginManager: Mounting Engine plugin OnlineServices
LogPluginManager: Mounting Engine plugin OnlineSubsystemEOS
LogPluginManager: Mounting Engine plugin OnlineSubsystemNull
LogPluginManager: Mounting Engine plugin OnlineSubsystemSteam
LogPluginManager: Mounting Engine plugin OnlineSubsystemUtils
LogPluginManager: Mounting Engine plugin OnlineSubsystem
LogPluginManager: Mounting Engine plugin SocketSubsystemEOS
LogPluginManager: Mounting Engine plugin EOSVoiceChat
LogPluginManager: Mounting Engine plugin LauncherChunkInstaller
LogPluginManager: Mounting Engine plugin ActorLayerUtilities
LogPluginManager: Mounting Engine plugin AndroidFileServer
LogPluginManager: Mounting Engine plugin ApexDestruction
LogPluginManager: Mounting Engine plugin AppleImageUtils
LogPluginManager: Mounting Engine plugin AssetTags
LogPluginManager: Mounting Engine plugin AudioCapture
LogPluginManager: Mounting Engine plugin AudioSynesthesia
LogPluginManager: Mounting Engine plugin AudioWidgets
LogPluginManager: Mounting Engine plugin CableComponent
LogPluginManager: Mounting Engine plugin ChunkDownloader
LogPluginManager: Mounting Engine plugin CustomMeshComponent
LogPluginManager: Mounting Engine plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting Engine plugin GeometryCache
LogPluginManager: Mounting Engine plugin GeometryProcessing
LogPluginManager: Mounting Engine plugin GooglePAD
LogPluginManager: Mounting Engine plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting Engine plugin MeshModelingToolset
LogPluginManager: Mounting Engine plugin Metasound
LogPluginManager: Mounting Engine plugin DTLSHandlerComponent
LogPluginManager: Mounting Engine plugin ProceduralMeshComponent
LogPluginManager: Mounting Engine plugin PropertyAccessEditor
LogPluginManager: Mounting Engine plugin ReplicationGraph
LogPluginManager: Mounting Engine plugin ResonanceAudio
LogPluginManager: Mounting Engine plugin SignificanceManager
LogPluginManager: Mounting Engine plugin SoundFields
LogPluginManager: Mounting Engine plugin SteamController
LogPluginManager: Mounting Engine plugin SteamShared
LogPluginManager: Mounting Engine plugin Synthesis
LogPluginManager: Mounting Engine plugin WaveTable
LogPluginManager: Mounting Engine plugin WindowsDeviceProfileSelector
LogPluginManager: Mounting Engine plugin EditorTests
LogPluginManager: Mounting Engine plugin FbxAutomationTestBuilder
LogPluginManager: Mounting Engine plugin FunctionalTestingEditor
LogPluginManager: Mounting Engine plugin RuntimeTests
LogPluginManager: Mounting Engine plugin TraceUtilities
LogPluginManager: Mounting Engine plugin Takes
LogPluginManager: Mounting Engine plugin Wwise
LogPluginManager: Mounting Project plugin AbstractInstance
LogPluginManager: Mounting Project plugin DLSS
LogPluginManager: Mounting Project plugin InstancedSplines
LogPluginManager: Mounting Project plugin NIS
LogPluginManager: Mounting Project plugin SignificanceISPC
LogPluginManager: Mounting Project plugin XeSS
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/2D/Paper2D/Content/' mounted to '/Paper2D/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/ControlRigSpline/Content/' mounted to '/ControlRigSpline/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/ControlRig/Content/' mounted to '/ControlRig/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Animation/IKRig/Content/' mounted to '/IKRig/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Bridge/Content/' mounted to '/Bridge/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Compositing/LensDistortion/Content/' mounted to '/LensDistortion/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Compositing/OpenColorIO/Content/' mounted to '/OpenColorIO/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Developer/AnimationSharing/Content/' mounted to '/AnimationSharing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/BlueprintHeaderView/Content/' mounted to '/BlueprintHeaderView/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/GeometryMode/Content/' mounted to '/GeometryMode/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/ObjectMixer/LightMixer/Content/' mounted to '/LightMixer/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/ObjectMixer/ObjectMixer/Content/' mounted to '/ObjectMixer/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Editor/SpeedTreeImporter/Content/' mounted to '/SpeedTreeImporter/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Enterprise/DatasmithContent/Content/' mounted to '/DatasmithContent/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Enterprise/GLTFExporter/Content/' mounted to '/GLTFExporter/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosCaching/Content/' mounted to '/ChaosCaching/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosClothEditor/Content/' mounted to '/ChaosClothEditor/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosNiagara/Content/' mounted to '/ChaosNiagara/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosSolverPlugin/Content/' mounted to '/ChaosSolverPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/ChaosVehiclesPlugin/Content/' mounted to '/ChaosVehiclesPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/Dataflow/Content/' mounted to '/Dataflow/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/FullBodyIK/Content/' mounted to '/FullBodyIK/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/GeometryCollectionPlugin/Content/' mounted to '/GeometryCollectionPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/GeometryScripting/Content/' mounted to '/GeometryScripting/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/Landmass/Content/' mounted to '/Landmass/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/PythonScriptPlugin/Content/' mounted to '/PythonScriptPlugin/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Experimental/UVEditor/Content/' mounted to '/UVEditor/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/FX/Niagara/Content/' mounted to '/Niagara/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Media/MediaCompositing/Content/' mounted to '/MediaCompositing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Media/MediaPlate/Content/' mounted to '/MediaPlate/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/MovieScene/MovieRenderPipeline/Content/' mounted to '/MovieRenderPipeline/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/MovieScene/SequencerScripting/Content/' mounted to '/SequencerScripting/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/AudioSynesthesia/Content/' mounted to '/AudioSynesthesia/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/AudioWidgets/Content/' mounted to '/AudioWidgets/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/GeometryProcessing/Content/' mounted to '/GeometryProcessing/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/MeshModelingToolset/Content/' mounted to '/MeshModelingToolset/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/Metasound/Content/' mounted to '/Metasound/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/ResonanceAudio/Content/' mounted to '/ResonanceAudio/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/Synthesis/Content/' mounted to '/Synthesis/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Runtime/WaveTable/Content/' mounted to '/WaveTable/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Tests/EditorTests/Content/' mounted to '/EditorTests/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Tests/RuntimeTests/Content/' mounted to '/RuntimeTests/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/VirtualProduction/Takes/Content/' mounted to '/Takes/'
LogPackageName: Display: FPackageName: Mount point added: '../../Plugins/Wwise/Content/' mounted to '/Wwise/'
LogPackageName: Display: FPackageName: Mount point added: '../../../FactoryGame/Plugins/AbstractInstance/Content/' mounted to '/AbstractInstance/'
LogPackageName: Display: FPackageName: Mount point added: '../../../FactoryGame/Plugins/DLSS/Content/' mounted to '/DLSS/'
LogPackageName: Display: FPackageName: Mount point added: '../../../FactoryGame/Plugins/InstancedSplines/Content/' mounted to '/InstancedSplines/'
LogPackageName: Display: FPackageName: Mount point added: '../../../FactoryGame/Plugins/SignificanceISPC/Content/' mounted to '/SignificanceISPC/'
LogPackageName: Display: FPackageName: Mount point added: '../../../FactoryGame/Plugins/XeSS/Content/' mounted to '/XeSS/'
LogHAL: Log category LogOnlineSession verbosity has been raised to Verbose.
Shutdown handler: initalize.
LogInit: Using libcurl 7.83.1
LogInit:  - built for Linux
LogInit:  - supports SSL with OpenSSL/1.1.1n
LogInit:  - supports HTTP deflate (compression) using libz 1.2.12
LogInit:  - other features:
LogInit:      CURL_VERSION_SSL
LogInit:      CURL_VERSION_LIBZ
LogInit:      CURL_VERSION_IPV6
LogInit:      CURL_VERSION_ASYNCHDNS
LogInit:      CURL_VERSION_LARGEFILE
LogInit:  CurlRequestOptions (configurable via config and command line):
LogInit:  - bVerifyPeer = true  - Libcurl will verify peer certificate
LogInit:  - bUseHttpProxy = false  - Libcurl will NOT use HTTP proxy
LogInit:  - bDontReuseConnections = false  - Libcurl will reuse connections
LogInit:  - MaxHostConnections = 16  - Libcurl will limit the number of connections to a host
LogInit:  - LocalHostAddr = Default
LogInit:  - BufferSize = 65536
LogEOSSDK: Initializing EOSSDK Version:1.15.3-21924193
LogOnline: Error: EOS: FOnlineSubsystemEOS: failed to initialize the EOS SDK with result code (EOS_AlreadyConfigured)
LogEOSSDK: LogEOS: [Boot] EOSSDK Version 1.15.3-21924193 booting at 2023-08-23T14:28:08.451Z using C
LogEOSSDK: LogEOS: [Boot] EOSSDK Platform Properties [OS=Linux/, ClientId=02612880aa774fb28e3741d3e01501fd, ProductId=prod-crab, SandboxId=crab, DeploymentId=5aebeb30a7614270b4f40c0bc2fe7549, ProductName=FactoryGame, ProductVersion=++FactoryGame+rel-main-0.8.0-CL-247367, IsServer=true, Flags=None]
LogEOSSDK: LogEOSAnalytics: Start Session (User: ...)
LogEOSSDK: LogEOSAntiCheat: [AntiCheatClient] Anti-cheat client not available. Verify that the game was started using the anti-cheat bootstrapper if you intend to use it.
LogEOSSDK: LogEOS: Updating Platform SDK Config, Time: 0.000074
LogSteamShared: Display: Loading Steam SDK 1.53
LogSteamShared: Display: Loaded libsteam_api.so at 0x128a7f0
LogSteamShared: Steam SDK Loaded!
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
LogOnline: OSS: Unable to create OnlineSubsystem module Steam
LogEOSSDK: LogEOSP2P: Starting NAT Detection
LogOnline: OSS: Created online subsystem instance for: EOS
LogOnline: OSS: TryLoadSubsystemAndSetDefault: Loaded subsystem for module [EOS]
LogOnline: Warning: STEAM: Steam API failed to initialize!
LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
Message dialog closed, result: Ok, title: Message, text: Plugin 'DLSS' failed to load because module 'DLSSBlueprint' could not be found.  Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module LinuxDeviceProfileSelector (78)
LogModuleManager: Shutting down and abandoning module ExampleDeviceProfileSelector (76)
LogModuleManager: Shutting down and abandoning module ChunkDownloader (74)
LogModuleManager: Shutting down and abandoning module LauncherChunkInstaller (72)
LogModuleManager: Shutting down and abandoning module OnlineSubsystem (70)
LogOnline: EOS: Destroying FUserManagerEOS at 0x7fcddff58080
LogModuleManager: Shutting down and abandoning module SteamShared (68)
LogSteamShared: Freeing the Steam Loaded Modules...
LogModuleManager: Shutting down and abandoning module HTTP (61)
LogModuleManager: Shutting down and abandoning module SSL (60)
LogModuleManager: Shutting down and abandoning module OnlineSubsystemUtils (56)
LogModuleManager: Shutting down and abandoning module OnlineServicesCommonEngineUtils (54)
LogModuleManager: Shutting down and abandoning module OnlineServicesCommon (52)
LogModuleManager: Shutting down and abandoning module OnlineServicesInterface (50)
LogModuleManager: Shutting down and abandoning module EOSShared (48)
LogEOSSDK: LogEOS: SDK Config Platform Update Request Successful, Time: 0.454499
LogEOSSDK: LogEOS: Updating Product SDK Config, Time: 0.455006
LogEOSSDK: LogEOS: SDK Config Product Update Request Successful, Time: 0.680030
LogEOSSDK: Warning: LogEOSEcom: Purchase flow is disabled due to overlay setup failure (EOS_NotConfigured).
LogEOSSDK: LogEOS: SDK Config Data - Watermark: 1926026542
LogEOSSDK: LogEOS: ScheduleNextSDKConfigDataUpdate - Time: 0.680030, Update Interval: 301.264008
LogEOSSDK: FEOSSDKManager::Shutdown EOS_Shutdown Result=[EOS_Success]
LogModuleManager: Shutting down and abandoning module NiagaraVertexFactories (46)
LogModuleManager: Shutting down and abandoning module NiagaraShader (44)
LogModuleManager: Shutting down and abandoning module ChaosCloth (42)
LogModuleManager: Shutting down and abandoning module VariantManagerContent (40)
LogModuleManager: Shutting down and abandoning module GLTFExporter (38)
LogModuleManager: Shutting down and abandoning module DatasmithContent (36)
LogModuleManager: Shutting down and abandoning module OpenColorIO (34)
LogModuleManager: Shutting down and abandoning module LensDistortion (32)
Assertion failed: Ptr [File:Runtime/Core/Public\Misc/LazySingleton.h] [Line: 109] 

libc++abi: Pure virtual function called!
Signal 6 caught.
libc++abi: Pure virtual function called!
Signal 6 caught.
libc++abi: __cxa_guard_acquire detected recursive initialization
Signal 6 caught.

**Comment by Lipora** [comment]
This is the section I don't remember seeing in the logs prior to this performance patch:
Message dialog closed, result: Ok, title: Message, text: Plugin 'DLSS' failed to load because module 'DLSSBlueprint' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project.
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module LinuxDeviceProfileSelector (78)
LogModuleManager: Shutting down and abandoning module ExampleDeviceProfileSelector (76)
LogModuleManager: Shutting down and abandoning module ChunkDownloader (74).......

**Comment by wolveix** [comment]
Hey. Yeah, seems like a bug from the game? I can't check the latest version myself right now so I can't verify

**Comment by Lipora** [comment]
Yeah they released a performance patch that moves the software to Unreal Engine 5.2, so likely some new dependencies.

**Comment by wolveix** [comment]
@Lipora thanks for the information. Yeah, I've just reproduced it on my end. So experimental does **not** launch whatsoever right now. I'm looking into it to see whether this is something I can resolve myself

**Comment by Lipora** [comment]
Might just require a start-up option to "disable DLSS" for the server instance, not sure where that is in the config files currently.
Let me know if you need any additional logs or info.  Can provide anytime.  Will be at my day job for a few hours but can check in in 4 hours or so.

**Comment by Lipora** [comment]
Perfect.  Yeah I saw on Bitz's stream this morning he had issue with firing up a headless version of the game, which is basically the same as what the server is doing, so I'll keep an eye our for the extra fix.

Is there a spot on the wiki where they are tracking that? or just in the discord for updates on that?

**Comment by wolveix** [comment]
Seems to just be in their Discord (under the `#dedicated-servers-experimental` channel) :)

**Comment by Lipora** [comment]
Thanks!  I'll keep an eye out for that patch and let you know if it solves the issue.
I can check that from the office.

**Comment by 98jan** [comment]
A fix was published 2h ago, Linux Server ist now starting up without issues.

**Comment by wolveix** [comment]
Amazing, thanks so much @98jan!
