### ISSUE TITLE
Docker build currently crashes with the newest

### ISSUE THREAD

**Issue by zp33dy** [wolveix/satisfactory-server#217]
The Satisfactory Docker build currently crashes with the following message:
```
tput: No value for $TERM and no -T specified
```

Problem seems to be in the changed `init.sh` which is started by the Dockerfile.
These are my env vars in the docker-compose:
```
environment:
MAXPLAYERS: 20
PGID: 1000
PUID: 1000
STEAMBETA: "false"
AUTOSAVEINTERVAL: 300 #5 min
AUTOPAUSE: "true"
AUTOSAVENUM: 10
AUTOSAVEONDISCONNECT: "true"
CRASHREPORT: "true"
DEBUG: "false"
DISABLESEASONALEVENTS: "false"
MAXTICKRATE: 30
NETWORKQUALITY: 3
```
Additionally it's running with 20G RAM and 1 CPU. It was working with the last version.

**System Specs (of the Docker host machine)**
```
===== START ISSUE REPORT =====
OS:  Linux Fedora 6.5.5-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Sep 23 22:53:27 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
BIOS 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz To Be Filled By O.E.M. CPU @ 2.5GHz
RAM: 16GB/31GB
HDD: 288GB/912GB (32% used)
===== END ISSUE REPORT =====
```

**Comment by wolveix** [comment]
@zp33dy ah, this is caused by the latest commit. I can get this fixed quickly, apologies!

**Comment by wolveix** [comment]
Once the new build has pushed, you should be good. Thanks!

**Comment by zp33dy** [comment]
After pulling and restarting it's not working at all. It tries to attach the container and then exits with code 1. The container starts, or at least debugs, when setting the env DEBUG var to true

**Comment by wolveix** [comment]
@zp33dy this is what I get for pushing a quick fix out the door on a Friday night 🤦‍♂️ 

I've fixed this now, please pull again. Sorry for the hassle!
