### ISSUE TITLE
Save File Issue

### ISSUE THREAD

**Issue by JonnyGuns** [wolveix/satisfactory-server#22]
Many thanks to you and all who made this docker possible. So fricken good!

Hey, the only issue I have is I wanted to change out save files. 

They seem deleted after I delete them from either WinSCP, or rm'ing them right out of the file directory through SSH. I start the server again and the saves are right back in the savefiles directory. I've tried deleting the saves, moving them, replacing them, and it still returns to the save I initially put in the directory. It actually defaults to the FIRST ever save that was put into the directory, no matter what else is in there afterwards. 

 I think this issue is more of a user error, but I wanted to see what you thought of it. Working great, I just wanted to use one new save and the old ones are not wanting to leave ;)

Thank you!

-Jonny

**Comment by wolveix** [comment]
Hi @JonnyGuns, I'm really sorry for taking so long to get back to you! Life's been pretty busy.

Firstly, thanks for using my project! The server _should_ always pull the save file with the latest modification date upon server launch. Are you 100% sure that this isn't the case? Are you stopping and starting the server between putting the new save file into the saves directory? If this is the case, you can probably get around the issue you're experiencing by destroying the container ('docker stop satisfactory-server && docker rm satisfactory-server'), removing all of the saves from the saves directory, and then rebuilding the container.

**Comment by JonnyGuns** [comment]
Very much appreciate the response! I totally hear you with IRL being busy. Thank you so much for making this a possibility in your free time. I haven't messed with it since starting. I just took down everything in the game and started like new. I was too excited to play with the guys, so I didn't bother restarting the whole container again. Been working flawlessly other than my botched save file shenanigans lol. I'm going to clone what I've done and mess around with it on another VM when I'm feeling ambitious. Thank you for the reply!

**Comment by wolveix** [comment]
Finally had a few minutes to check on this :) When running the container, it pulled the file with the latest modification date as expected. What I imagine happened for you is that you put a new savefile in, but didn't restart the container until _after_ it moved the latest internal savefiles into the mapped savefiles directory, resulting in the existing files having a more recent modified date.
