### ISSUE TITLE
DEBUG envvar issue

### ISSUE THREAD

**Issue by teejo75** [wolveix/satisfactory-server#224]
https://github.com/wolveix/satisfactory-server/blob/001254a1f59b39738630b09623fc29017c8f433f/init.sh#L13

If you don't have `DEBUG=true` in your envvars, then the container exits.

I'm not sure if this is intended.

**Comment by wolveix** [comment]
Yeah, seems I flipped the checked value. So the container would exit if `DEBUG == false`, which it does unless you manually set any other value.

Thanks for catching this, I'll rebase the v1.6.0 tag to the latest commit
