### ISSUE TITLE
Feature request: add option to toggle Server Streaming

### ISSUE THREAD

**Issue by williamoverstreet** [wolveix/satisfactory-server#231]
The reason satisfactory is taking up so little memory right now is because they accidentally shipped the update with Server Streaming enabled. The feature itself can impact server stability negatively when enabled. Would like an option to force it on/off.

Engine.ini:
```
[ConsoleVariables]
wp.Runtime.EnableServerStreaming=0
```

**Comment by williamoverstreet** [comment]
Also, I've heard that CSS intends to disable it again on another update.

**Comment by wolveix** [comment]
Hey! I somehow missed the noficiation for this. Seems trivial enough to add, I'll work on this shortly :) In the meantime, you can override the `Engine.ini` file directly

**Comment by wolveix** [comment]
Sorry this took so long! This is doable via the `SERVERSTREAMING` environment variable now :)

**Comment by Koozu1** [comment]
Sorry to post into a closed issue.
What is this server streaming? I couldn't find any resources on this, would be nice to know what this relates to, since it apparently changes the ram usage a lot!

**Comment by wolveix** [comment]
@Koozu1 it's referring to asset streaming :) When it's enabled, it drastically reduces the RAM utilization of the server, but can introduce other bugs as a result. So if you've got the RAM to spare, you're better off disabling it
