### ISSUE TITLE
Server crashes on start

### ISSUE THREAD

**Issue by stacode123** [wolveix/satisfactory-server#244]
**Describe the Bug**
After running the container the server crashes instantly before loading steamcmd

**Your Runtime Command or Docker Compose File**
```
sudo docker run --platform linux/amd64 --name=satisfactory-server --hostname satisfactory-server --volume /home/opc/satisfactory2:/config --env MAXPLAYERS=4 --env PGID=1000 --env PUID=1000 --env ROOTLESS=false --env STEAMBETA=false --memory-reservation=4G --memory 12G --net=host wolveix/satisfactory-server:latest
```

**System Specs**
```
===== START ISSUE REPORT =====
OS:  Linux instance-20230426-1654 5.15.0-202.135.2.el8uek.aarch64 #2 SMP Fri Jan 5 16:31:37 PST 2024 aarch64 aarch64 aarch64 GNU/Linux
CPU: Neoverse-N1
RAM: 14GB/22GB
HDD: 159GB/189GB (85% used)
===== END ISSUE REPORT =====
```

**Additional Context**
I see there where similar issues to this one but i think  this is different?
Note: First time using docker.

**Comment by wolveix** [comment]
Hi @stacode123, could you publish the container logs, if there are any? I notice that you're using a non-`amd64` system architecture. While Docker does allow you to run other architectures on your own, running `amd64` on `aarch64` isn't as easy as, say, `arm64` on `amd64`. I'd consult Docker documentation on this issue specifically.

**Comment by stacode123** [comment]
O god i tottaly forgot my bad:
`Checking available memory...14GB detected
Setting autosave number to 5
Setting crash reporting to True
Setting max objects number to 2162688
Setting max tick rate to 30
Setting timeout number to 30
Setting server streaming to 1
Setting timeout number to 30
Setting max players to 4
Setting autosave interval to 300s
Setting disable seasonal events to 0
Setting network quality number to 3
Setting auto pause to True
Setting autosave on disconnect to True
Checking available storage...30GB detected
Downloading the latest version of the game...
`

**Comment by wolveix** [comment]
@stacode123 yeah, if that's all you're seeing, it's _probably_ architecture-related. I believe `steamcmd` has issues with other architectures, nevermind Satisfactory not supporting other architectures either
