### ISSUE TITLE
[feature request] Auto load save on container start

### ISSUE THREAD

**Issue by DragonHunter274** [wolveix/satisfactory-server#246]
Currently I have to manually load the latest save after restarting the container.
It would be great if that could happen automatically

**Comment by wolveix** [comment]
Hey @DragonHunter274, the server should already do this by default. Are you definitely running the latest version of the Docker image?

**Comment by DragonHunter274** [comment]
I'm running container version 1.6.2

**Comment by wolveix** [comment]
I'll find time soon to look into this :)

**Comment by Yanni-X** [comment]
Quick thought: maybe forgot to mount the volumes? Or maybe some permission-stuff in the volume?

**Comment by wolveix** [comment]
@DragonHunter274 apologies, I've been too busy these past few months. If you're still experiencing this issue, please supply your container launch information (per the issue template) and we can dig into this further for you :)
