### ISSUE TITLE
Symbol In Steam Password

### ISSUE THREAD

**Issue by Allread** [wolveix/satisfactory-server#25]
**Describe the Bug**
I have the "$" symbol in my Steam password.
Every time I launch docker, I get an error message

I removed the symbol and everything works

**Your Runtime Command or Docker Compose File**
docker run -d --name=satisfactory-server2 -h satisfactory-server2 -e STEAMUSER=xxxxx -e STEAMPWD=xxx$xxxxx -e STEAMCODE=xxxx -e MAXBACKUPS=10 -v /home/serveur:/config -p 7777:7777/udp wolveix/satisfactory-server:latest

**System Specs:**
 - OS: Debian 10

**Comment by wolveix** [comment]
Thanks for submitting this issue!

Please try wrapping your password in `'` or `"`
