### ISSUE TITLE
Server Can't Find Savefiles

### ISSUE THREAD

**Issue by Allread** [wolveix/satisfactory-server#26]
**Describe the Bug**
Server doesn't lunch.
Error cp: cannot stat '/config/savefiles/*.sav': No such file or directory

![image](https://user-images.githubusercontent.com/16807391/134236055-7653bbad-2d7e-407a-b2c1-24a04a8e7d45.png)

**Your Runtime Command or Docker Compose File**
docker run -d --name=satisfactory-server2 -h satisfactory-server2 -e STEAMUSER=xxxxx -e STEAMPWD=xxxxx -e STEAMCODE=xxxxx -e MAXBACKUPS=10 -v /home/serveur:/config -p 7777:7777/udp wolveix/satisfactory-server:latest

**System Specs:**
 - OS: Debian 10

**Comment by wolveix** [comment]
Your `savefiles` directory is mapped incorrectly. You either need to change `-v /home/serveur:/config` to `-v /home/serveur/config`, or move the `/home/serveur/config` to `/home/serveur/`

**Comment by Allread** [comment]
Hello :) 
After modifying the launch command, I still have the same error ! I copy too _/home/serveur/config_ to _/home/serveur/_

**Command :** 
docker run -d --name=satisfactory-server2 -h satisfactory-server2 -e STEAMUSER=xxxxxx -e STEAMPWD=xxxxxxx -e STEAMCODE=xxxxxx -e MAXBACKUPS=10 -v /home/serveur/config -p 7777:7777/udp wolveix/satisfactory-server:latest

**Result**
![image](https://user-images.githubusercontent.com/16807391/134300298-f8fc487b-d132-4974-8efa-a960e399d981.png)

**Comment by wolveix** [comment]
Your config directory still isn't mapped correctly. Your `-v` directive should look like `/home/serveur:/config`

**Comment by Allread** [comment]
Yep :) It's ok now :D 
Thx to you !
