### ISSUE TITLE
Missing version: '3' in docker-compose.yml

### ISSUE THREAD

**Issue by PxL1337** [wolveix/satisfactory-server#262]
Missing version: '3' in docker-compose.yml

**Comment by DenuxPlays** [comment]
No the version tag is omitted in new compose versions

**Comment by noahjahn** [comment]
The version tag was made obsolete some time ago: https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

**Comment by PxL1337** [comment]
won't launch for me without version tag

**Comment by DenuxPlays** [comment]
> won't launch for me without version tag
> 
> 

Update your compose version

**Comment by lennartdohmann** [comment]
The "version" attribute of docker compose is obsolete

**Comment by hexd0t** [comment]
You should switch from `docker-compose` (which was a Python script) to `docker compose` which is a plugin to the docker cli ([install guide](https://docs.docker.com/compose/install/linux/))
The former is deprecated.
