### ISSUE TITLE
Is it possible to use a different mapped port (UDP 7777?)

### ISSUE THREAD

**Issue by dnabsuh** [wolveix/satisfactory-server#27]
Not so much an issue as a question - is it possible to expose satisfactory on a different external port (In the port mapping?)  I have ARK Survival on the same server, and it already is using UDP Port 7777.

**Comment by wolveix** [comment]
Thanks for taking the time to open an issue.

Since the project utilizes Docker for deployment, you can just remap the port when deploying your server. Change the port flag like so:

```
7778:7777/udp
```

This will tell the server to listen on port `7778`. You'll need to append the modified port onto the end of your server IP/hostname in-game to be able to connect to the server. Do this like so:

```
connect your.server.ip.address:7778
```

**Comment by AeSix** [comment]
So, in this case, i think I would use HAProxy, and separate subdomains for each game. 
I... actually have done this in the past with Minecraft.  One of the things I also did with this, was to host HAProxy on a high bandwidth/throughput VM to disallow my servers' IPs from being made public. 

Here's a quick primer for (ab)using HAProxy like this:
https://www.spigotmc.org/threads/obscure-corner-for-obscure-conf-file.345414/#post-3212938

It's stable, at least with Minecraft (about 400 users going through it)  I can't imagine Satisfactory could kill it - but it is CPU and network intensive if not hosted on the same box as the endpoint game servers. 

(also, been lurking for quite a while, just this is the first time I've felt I could contribute by chiming in)

**Comment by wolveix** [comment]
@AeSix Please open a separate issue if you require any help with your setup! 😃

**Comment by AeSix** [comment]
I don't.  I was trying to offer help, before realizing HAProxy don't handle UDP.

**Comment by wolveix** [comment]
@AeSix my mistake. Thanks!
