### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by Xekko1629** [wolveix/satisfactory-server#270]
Hello, i just started a new server for the update one. I delete the previous image just in case and launch the docker-compose.yml just bellow.

version: '3'
services:
    satisfactory-server:
        container_name: 'sfV1'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '7777:7777/tcp'
        volumes:
            - './server:/config'
        environment:
            - MAXPLAYERS=4
            - AUTOPAUSE=false
            - AUTOSAVEINTERVAL=600
            - TIMEOUT=180
            - PGID=1000
            - PUID=1000
            - STEAMBETA=false
        restart: always
        tty: true
        stdin_open: true
        deploy:
          resources:
            limits:
              memory: 64G
            reservations:
              memory: 64G

When i start the game and enter the server ip, it says "Failed to Connect to the Server API" but the docker logs say "NotifyAcceptingConnection accepted from:" (See screen below)
I don't really know how to fix it. My server is on ubuntu 22.04 lts. And i've got the game on epic game.
![image_2024-09-10_192030133](https://github.com/user-attachments/assets/0d5b8dd9-bacf-4648-9f90-f8aa67313db4)
![image_2024-09-10_192056116](https://github.com/user-attachments/assets/c28bc962-9a38-4ed8-a286-871e3e456097)

**Comment by lennartdohmann** [comment]
I think you are experiencing an already known issue #260 . We have to wait for the fix of Coffee Stain (Game developers)

**Comment by lennartdohmann** [comment]
https://github.com/wolveix/satisfactory-server/issues/260#issuecomment-2341540516

**Comment by Xekko1629** [comment]
Ho my bad, I've never see this topic.
Thanks for the reply.

Have a great day.

**Comment by ChaosFoxOverlord** [comment]
Environment:

Satisfactory 1.0 Dedicated Server via Steam on Ubuntu 24.04 (vRoot)


Problem:

UDP Listner 0.0.0.0:7777, but TCP (API) Listner only on 127.0.0.1:7777, thus not reachable, thus leading to "Failed to connect to API"-Error in Client


Solution:

Setting up a DNAT, Code:

```
sudo iptables -t nat -A PREROUTING -i <your_external_interface> -p tcp --dport 7777 -j DNAT --to 127.0.0.1:7777
sudo sysctl -w net.ipv4.conf.<your_external_interface>.route_localnet=1
```

First line sets up the routing from your external interface to 127.0.0.1. The route back is automaticly managed by conntrack.
Second line allows localnet Adresses (e.g. 127.0.0.1) on your external interface after rewrting its destination (see first line) to prevent discarding.
Replace <your_external_interface> with the name of your external interface, e.g. eth0, ens6, etc..


Disclaimer:

Parameter -multihome=0.0.0.0 is (still) used, removing the parameter not tested.
Similar solution for other OS (e.g. Windows) may or may not work.

**Comment by wolveix** [comment]
@ChaosFoxOverlord no, that is not a solution, that's a hacky workaround. You're not using the latest version of the container, if you were, you wouldn't have the connection issue in the first place. The logs indicate that they bind to 127.0.0.1, but Coffee Stain themselves confirmed to me that the log message is irrelevant. Please see #260

**Comment by ChaosFoxOverlord** [comment]
ACK.
