### ISSUE TITLE
Settings Not Persisting

### ISSUE THREAD

**Issue by tylerstraub** [wolveix/satisfactory-server#276]
The environment varaible `AUTOPAUSE` is not being respected right now, maybe this is a 1.0 thing?

Can't even seem to persist the configuration through the ingame Server Manager either - it doesn't withstand reboots after applying the config change and then rebooting the container. 

I'm going to try an INI file override in the meantime.

**Comment by wolveix** [comment]
You're using an old container image, please upgrade. Additionally, per the README, `AUTOPAUSE` was removed as it's now configurable through the server manager.

**Comment by tylerstraub** [comment]
That makes sense. What I was trying to communicate though is that although the option is indeed configurable through the server manager - it does not persist container reboots. I am using the latest branch of `wolveix/satisfactory-server`.

**Comment by wolveix** [comment]
Ah, I see! That is interesting. Admittedly when removing the environment variables, I didn't explicitly check that these settings persisted across reboots as I was in the middle of debugging 1.0 issues.

I suspect they write your configuration to an ini file, and then we overwrite it on the next startup. I'll find time to investigate this further tomorrow. Though do feel free to look into it yourself, if you're up to it!

**Comment by tylerstraub** [comment]
Thanks @wolveix I will keep tinkering on my end. I suspect that they may have even moved this parameter location to a different ini file perhaps but I'm still trying to sort through the information. It may not even really be a container issue and could just be a problem with 1.0 idk.

**Comment by kashyn89** [comment]
But what about about the MAXTICKRATE? It was set before per envs, i can see in the logs that the conainter replies it is set, but then it is set to 30 when i have a look ingame, any chance to get it back working?

**Comment by wolveix** [comment]
@kashyn89 please fill out the issue template. That variable should still work, but there's a chance it was broken during the madness yesterday. Thank you!

**Comment by Xirado** [comment]
If i'm not mistaken, `AUTOPAUSE` was also not being saved correctly before 1.0, i remember having to switch it back on everytime the server auto-restarted.

**Comment by wolveix** [comment]
This is now fixed! Also, `AUTOPAUSE` has been removed as an environment variable as it's configurable from the server manager :) But settings not persistent is now **fixed** as configuration has been overhauled: https://github.com/wolveix/satisfactory-server/commit/a151b0c96c52858a813deb955362cbc951b25eb2

**Comment by tylerstraub** [comment]
Thank you @wolveix this did fix the state persistance of the Auto Pause option for me. 

Is it possible that in the process of fixing this issue the state persistance of the "Network Quality" parameter was affected?

This value now resets itself to "Medium" each time the server is rebooted reguardless of what value is saved, similar to the problem we had before for Auto Pause.

**Comment by tylerstraub** [comment]
Ah okay that makes perfect sense thank you for taking the time to explain. Have a great week and I hope you get to enjoy 1.0 as well!
