### ISSUE TITLE
Make number of autosave slots configurable

### ISSUE THREAD

**Issue by Chimaine** [wolveix/satisfactory-server#277]
Hi! A hopefully small feature request.

I would like to be able to configure the number of autosave slots via an environment variable (see [Autosave slots and Autosave interval](https://satisfactory.wiki.gg/wiki/Dedicated_servers/Configuration_files#Autosave_slots_and_Autosave_interval) in the wiki).

As I understand it, I could also do it with the configuration overrides, but it might be a useful enough setting to expose via a environment variable for easier setup.

My personal use-case for this would be increasing the slots (along with a longer interval) to cover a longer period (24h), as an anti-grieving measure on semi-public servers.

Thanks for your fast work on the 1.0 update!

**Comment by wolveix** [comment]
Lol, I removed this accidentally just a few hours ago 🤦

**Comment by wolveix** [comment]
I'm off to sleep now, but will add it back in the morning. Apologies!

**Comment by Chimaine** [comment]
And here I thought I was crazy for swearing I saw that being a feature before 😅

No worries!

**Comment by wolveix** [comment]
Fixed, thank you!
