### ISSUE TITLE
Add Modding Support

### ISSUE THREAD

**Issue by fionera** [wolveix/satisfactory-server#28]
I already hacked something together, since the official mod manager runs on electron. I hope I can help to add it ^^

https://github.com/fionera/satisfactory-server

**Comment by wolveix** [comment]
Thanks again for your work :) Mod support was already coming in the rewrite, but your work will be helpful! I'll ask you to submit a PR once the rewrite has been pushed.

**Comment by fionera** [comment]
Did you clone my Repo or this? Because it seems the folder with the modding tool is missing

**Comment by ysm1mh** [comment]
i would love to see mod support i never got it to work for some reason.

and hopefully a small explenation with it for me to guide the install of mods  ( i am a noob )

**Comment by Feyko** [comment]
Hey, Admin of the Satisfactory Modding Discord here :smile: Modding does not work on dedicated servers. Currently the team is working on U5 support but server support will come for sure at some point

**Comment by shadhes** [comment]
Hello, I would like to know if the modding support works or not with your image? I have a little trouble understanding your previous message :)

Thank you very much for the work you have done.

**Comment by wolveix** [comment]
Hello :) Mods are not currently supported by CSS's official server implementation. @fionera built a custom mod handler over my original server implementation, which predates CSS's version.

**Comment by shadhes** [comment]
thank you for your quick response  :)

**Comment by shadhes** [comment]
Do you think this is something you will have time to work on or is it absolutely not in your plans ?

**Comment by wolveix** [comment]
It's not a case of whether or not I have the time or desire to work on it. As this repo now utilizes CSS's own implementation, it's entirely down to when they have the time to implement it (as they have expressed the desire to do so) :)

**Comment by shadhes** [comment]
AHHHH alright, I hadn't understood it like that, thank you :)

**Comment by cornernote** [comment]
+1 for modding support

**Comment by Johan-Claesson** [comment]
+1 for modding support

**Comment by wolveix** [comment]
@cornernote @Johan-Claesson again, this is a limitation of CSS's implementation. We can't do anything until they officially support it.

**Comment by Feyko** [comment]
(It's not a limitation of CSS's implementation. It's a matter of mods working on servers and us providing mod management tools adapted for a server environment)

**Comment by wolveix** [comment]
> (It's not a limitation of CSS's implementation. **It's a matter of mods working on servers** and us providing mod management tools adapted for a server environment)

Indeed, so it mods **don't work on servers**, we can't do anything until CSS changes that. Regardless of when mod management tools exist, as soon as their implementation supports mods, so can we.

**Comment by Feyko** [comment]
No, what I'm saying is that it's not up to CSS lol. It's up to us (the modding community)

**Comment by wolveix** [comment]
@Feyko it was my understanding that mods didn't work **at all** with CSS's implementation per your earlier comment in this thread. Is that not the case, and rather that most mods are incompatible or along those lines?

**Comment by Feyko** [comment]
Mods don't work at all on servers, that's correct. But it's a problem on our end, we have to adapt and fix our tools to allow them to work on servers. It's not CSS that needs to change the game is what I mean :smile:

**Comment by wolveix** [comment]
Ahhhh, I see. Thank you for clarifying :) 

Prior to CSS's official implementation, this repo ran the full Satisfactory client so mods did work since it's the same client. I hadn't considered that the implementation of mods themselves would of course be different with a server instance 🤦‍♂️

**Comment by porisius** [comment]
Heads up, and no, mods on dedicated servers is not a thing yet... but there has been some progress at least.

Look at ficsit-cli and see if that is something that can help for when modded servers become a thing. I wouldn't implement it in yet, since it is not complete. However, might be something good to at least look at on if it will be useful.

I have no experience with docker/kuberates, and I only found this because of TrueNAS Scale/TrueCharts.

**Comment by wolveix** [comment]
Hey @porisius, thanks for mentioning `ficsit-cli` :) I'm familiar with it, and will keep it in mind for when mods are supported.

**Comment by wolveix** [comment]
Closing this out as it's been stale for over a year, and we're still awaiting mod implementations from other developers :)

**Comment by wolveix** [comment]
Mods exist and work now thanks to the excellent these excellent developers: https://docs.ficsit.app/satisfactory-modding/latest/ForUsers/DedicatedServerSetup.html

**Comment by rlnt** [comment]
@wolveix Let me know if you want this in a new tracking issue but with the new Satisfactory Mod Manager that just came out for Satisfactory 1.0, it introduced immediate support with dedicated servers and offers server mod setup for FTP, SFTP, and path. Do you think it would be feasible to support this in the docker image directly? Maybe by spinning up an optional FTP instance with a configurable port that the mod manager can connect to and manage the server's mods.

**Comment by wolveix** [comment]
@rlnt that's been covered in this repo's readme for months (since SMM first supported dedicated servers): https://github.com/wolveix/satisfactory-server?tab=readme-ov-file#modding :)

**Comment by brink668** [comment]
In case anyone sees this, I can confirm Satisfactory Mod Manager works with this container using Docker Host SFTP.

However, what was not apparent to me is that in the Satisfactory Mod Manager is how the manager copied the files to the Docker Container.  

1. Mods have to compatible for server. (Must use the website to see this attribute).
2. The same Mod files must reside on **BOTH** the **CLIENT** side as well as on the **SERVER** side.
3. In the Mod Manager under the "Manage Servers" section make sure the path is targeting the "gamesfiles" location, the app will help you verify this directory.

*In my case the path was here:* 
Named: **Remote 1** 
/home/admin3/portDATA/satisfactory/gamefiles

5. Under "Select Game Installation > select "Epic Games" or Steam.. , then "MODS On"
6. Once you download the mods, place them under your designated profile such as "modded", click check for updates
7. Under "Select Game Installation > select "**Remote 1**", select "modded", click check for updates and the mods will be pushed to the docker host.

You may need to run through steps 5-7 to ensure both sides are up to date.

**Comment by wolveix** [comment]
Thanks so much for sharing @brink668!
