### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by ProCakeMan** [wolveix/satisfactory-server#280]
I'm still encountering the "Failed to connect to the API" issue, I just ran this command 5 minutes ago on the latest image. I have opened the port tcp and udp using ufw, and I have verified that both ports are open in my router. It doesn't work through my public or local IP (I am on the same network as the host machine).

```shell
docker run \
--detach \
--name=guttas-ronkehi \
--hostname guttas-ronkehi \
--restart unless-stopped \
--volume ./satisfactory-server:/config \
--env MAXPLAYERS=8 \
--env PGID=1000 \
--env PUID=1000 \
--env ROOTLESS=false \
--env STEAMBETA=false \
--memory-reservation=6G \
--memory 12G \
--publish 7777:7777/udp \
--publish 7777:7777/tcp \
wolveix/satisfactory-server:latest
```

**Comment by val-exe** [comment]
Did you get this fixed in the end?

**Comment by wolveix** [comment]
@val-exe see #260. There are no connectivity issues eith the image if you're using the latest version, and actually follow the 1.0 upgrade steps in the README

**Comment by val-exe** [comment]
I've been having connectivity issues on my end with the newest image and while I'm fairly sure it's something **I** misconfigured, just wanted to follow other leads.

**Comment by wolveix** [comment]
@val-exe feel free to open your own issue or discussion, and we'll see if we can get to the bottom of it! Just make sure to go through the README first, and ensure that no firewalls are blocking `7777/tcp` or `7777/udp` :)
