### ISSUE TITLE
EncryptionTokenMissing

### ISSUE THREAD

**Issue by P6g9YHK6** [wolveix/satisfactory-server#283]
**Describe the Bug**
EncryptionTokenMissing error when trying to login to the server

**Your Runtime Command or Docker Compose File**
Please censor anything sensitive. Your runtime command might look like this:

```services:
  satisfactory-server:
    container_name: satisfactory-server
    hostname: satisfactory-server
    image: wolveix/satisfactory-server
    ports:
      - 7777:7777/udp
      - 7777:7777/tcp
    volumes:
      - /mnt/user/appdata/satisfactory-server:/config
    environment:
      MAXPLAYERS: 4
      PGID: 1000
      PUID: 1000
      ROOTLESS: false
      STEAMBETA: false
    restart: unless-stopped
networks: {}

```

**System Specs (please complete the following information):**
If you're on Linux, just paste the following block as a single command, and paste the output here.
```
===== START ISSUE REPORT =====
OS:  Linux Tower 6.1.106-Unraid #1 SMP PREEMPT_DYNAMIC Wed Aug 21 23:36:07 PDT 2024 x86_64 AMD EPYC 7302 16-Core Processor AuthenticAMD GNU/Linux
CPU: AMD EPYC 7302 16-Core Processor
BIOS AMD EPYC 7302 16-Core Processor                 Unknown CPU @ 3.0GHz
RAM: 43GB/128GB
HDD: 1GB/63GB (2% used)
===== END ISSUE REPORT =====

```
**Additional Context**

```

satisfactory-server  | [2024.09.11-07.04.34:274][176]LogNet: UChannel::Close: Sending CloseBunch. ChIndex == 0. Name: [UChannel] ChIndex: 0, Closing: 0 [UNetConnection] RemoteAddr: 192.168.1.156:51667, Name: IpConnection_2147482273, Driver: GameNetDriver FGDSIpNetDriver_2147482292, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
satisfactory-server  | [2024.09.11-07.04.34:307][177]LogNet: UNetConnection::PendingConnectionLost. [UNetConnection] RemoteAddr: 192.168.1.156:51667, Name: IpConnection_2147482273, Driver: GameNetDriver FGDSIpNetDriver_2147482292, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID bPendingDestroy=0 
satisfactory-server  | [2024.09.11-07.04.34:307][177]LogNet: NotifyAcceptingConnection accepted from: 192.168.1.156:51667
satisfactory-server  | [2024.09.11-07.04.34:307][177]LogNet: NotifyAcceptingConnection accepted from: 192.168.1.156:51667
satisfactory-server  | [2024.09.11-07.04.58:459][900]LogServer: Display: Server startup time elapsed and saving/level loading is done, auto-pause is allowed to proceed from now on (if enabled in server settings). WorldTimeSeconds = 30.10
satisfactory-server  | [2024.09.11-07.07.58:783][299]LogNet: NotifyAcceptingConnection accepted from: 192.168.1.156:63483
satisfactory-server  | [2024.09.11-07.07.58:817][300]LogNet: NotifyAcceptingConnection accepted from: 192.168.1.156:63483
satisfactory-server  | [2024.09.11-07.07.58:817][300]LogNet: Server accepting post-challenge connection from: 192.168.1.156:63483
satisfactory-server  | [2024.09.11-07.07.58:817][300]LogNet: IpConnection_2147482264 setting maximum channels to: 32767
satisfactory-server  | [2024.09.11-07.07.58:818][300]PacketHandlerLog: Loaded PacketHandler component: DTLSHandlerComponent ()
satisfactory-server  | [2024.09.11-07.07.58:818][300]PacketHandlerLog: Loaded PacketHandler component: Engine.EngineHandlerComponentFactory (StatelessConnectHandlerComponent)
satisfactory-server  | [2024.09.11-07.07.58:818][300]LogNet: NotifyAcceptedConnection: Name: DedicatedserverEntry, TimeStamp: 09/11/24 07:07:58, [UNetConnection] RemoteAddr: 192.168.1.156:63483, Name: IpConnection_2147482264, Driver: GameNetDriver FGDSIpNetDriver_2147482292, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
satisfactory-server  | [2024.09.11-07.07.58:818][300]LogNet: AddClientConnection: Added client connection: [UNetConnection] RemoteAddr: 192.168.1.156:63483, Name: IpConnection_2147482264, Driver: GameNetDriver FGDSIpNetDriver_2147482292, IsServer: YES, PC: NULL, Owner: NULL, UniqueId: INVALID
satisfactory-server  | [2024.09.11-07.07.58:819][301]LogStreaming: Display: 0.008 ms for processing 44 objects in RemoveUnreachableObjects(Queued=0, Async=0). Removed 3 (1842->1839) packages and 15 (3304->3289) public exports.
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet: NotifyAcceptingChannel Control 0 server World /Game/FactoryGame/Map/DedicatedserverEntry.DedicatedserverEntry: Accepted
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet: Remote platform little endian=1
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet: This platform little endian=1
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet: Warning: IpConnection_2147482264: No EncryptionToken specified, disconnecting.
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet: UNetConnection::SendCloseReason:
satisfactory-server  | [2024.09.11-07.07.58:850][301]LogNet:  - Result=EncryptionTokenMissing, ErrorContext="EncryptionTokenMissing"

```

**Comment by wolveix** [comment]
Hey @P6g9YHK6! Please check #263 :)

You need to manage the server through the in-game server manager before joining.

**Comment by P6g9YHK6** [comment]
Indeed this server manager is something i have never seen in a game and it looks very good !
but not very intuitive the logs should be more explicit about what is expected.

**Comment by P6g9YHK6** [comment]
i still have the issue but not when using the local ip
only when using the public ip with port forwarding O_O

**Comment by wolveix** [comment]
@P6g9YHK6 make sure you're using the latest image (you can alternatively specify your tag as `v1.7.3` to make sure you have the fix)

**Comment by P6g9YHK6** [comment]
[+] Running 1/1
 ✘ satisfactory-server Error                                                                        1.6s 
Error response from daemon: manifest for wolveix/satisfactory-server:1.7.3 not found: manifest unknown: manifest unknown

**Comment by wolveix** [comment]
You put `1.7.3`, you need `v1.7.3`

**Comment by P6g9YHK6** [comment]
yea it is running
![image](https://github.com/user-attachments/assets/94483411-825b-460a-a6bd-c21e80e2abd1)


but now nothing works anymore to connect to the server ._, the server manager is ok but joining is just more of the same error

**Comment by wolveix** [comment]
So you're able to connect to the server in the server manager fine, but nothing else works? Try stopping the container, clearing out the mounted directory, and then start it back up (backup anything important beforehand)

**Comment by P6g9YHK6** [comment]
i did it a couple of times and now this is the behavior:
pressing join on the server manager works ( no idea what it connects to as it does not say anything about IP/DNS

using the join game directly button then typing the ip/dns does not work.

**Comment by wolveix** [comment]
You're not meant to join the game via IP, you're meant to add it through the server manager and join through that. Which sounds like it's working?

**Comment by P6g9YHK6** [comment]
![image](https://github.com/user-attachments/assets/179afa11-9892-4059-b5f6-46bdd7cedf6d)

**Comment by wolveix** [comment]
Yes, it's working as expected. Coffee Stain have said that you should NOT be using the join game menu for dedicated servers. 

Glad it's working for you!

**Comment by P6g9YHK6** [comment]
ok thanks the whole thing could need a bit more polish on the ui side and thanks for the pointers

**Comment by wolveix** [comment]
I agree! Direct your feedback to Coffee Stain though, I don't work for them :D

**Comment by P6g9YHK6** [comment]
yea i know it is just that it is not your fault that the whole "workflow" is this messy 
but you could update the docs to at least not have that many clueless people like me opening useless issues

**Comment by bazzspeed** [comment]
Alternative issue and fix.
When a player is trying to join from EPIC they might also get:
EncryptionTokenMissing
FIX: Go into your account settings in EPIC and make sure you have linked your steam account, then you will be able to connect. (Probably will need a minute, and restart the epic client)
