### ISSUE TITLE
main branch does not preserve save files

### ISSUE THREAD

**Issue by matejc** [wolveix/satisfactory-server#288]
I am using my own image built from main.
I have ROOTLESS=false

User running the FactoryGame is ubuntu (uid: 1000) and therefore savegames are saved on /home/**ubuntu**/...
But the savegames are pointing from /home/**steam**/... to /config/...

Result: savegames are being deleted every time when you recreate the container

**Comment by wolveix** [comment]
You're running an outdated version of the image, please try manually specifying the tag as `v1.7.4`
