### ISSUE TITLE
ERROR: Your CPU model is configured as "Common KVM processor", which will cause Satisfactory to crash.

### ISSUE THREAD

**Issue by dennybrah** [wolveix/satisfactory-server#304]
I was having no issues earlier today, then received a message in-game regarding different client vs server versions.

Game Version: 366202
Server Version: 365306

I went ahead and repulled your image and received the following error when attempting to start the container in portainer:

===== Satisfactory Server 1.8.3 =====
https://github.com/wolveix/satisfactory-server
ERROR: Your CPU model is configured as "Common KVM processor", which will cause Satisfactory to crash.
If you have control over your hypervisor (ESXi, Proxmox, etc.), you should be able to easily change this.
Otherwise contact your host/administrator for assistance.

I tried changing to different CPU types in proxmox for my ubuntu VM, but unable to start my VM with Skylake or Haswell (I am using intel), do you have any recommendations on a workaround or which CPU type I can use?

**Comment by wolveix** [comment]
Hey @dennybrah! In Proxmox, just set the VM's CPU to Host, and you should be fine :)

**Comment by dennybrah** [comment]
Thanks, that worked!

**Comment by wolveix** [comment]
Glad to hear it! Enjoy :D
