### ISSUE TITLE
Increase Player Limit After session created

### ISSUE THREAD

**Issue by fast1marine** [wolveix/satisfactory-server#308]
I started a server and the initial player maximum was four in my docker compose.  I would like to increase it to 6.  I did so in my compose file but it seems to be still limited to 4.

**Comment by rooleyzee123** [comment]
Have you rebuilt the container? If you recreate this should update just make sure you don't remove data.

**Comment by fddn** [comment]
Probably you need to manually modify the config if you changed the compose file after the first initial deploy.
You can do it just by editing the Engine.ini located in ./satisfactory-server/gamefiles/FactoryGame/Saved/Config/LinuxServer 

Add this block to the end of the file, save it and restart the container.
```bash
[/Script/Engine.GameSession]
MaxPlayers=6
```

**Comment by wolveix** [comment]
@fast1marine you need to rebuild the container whenever you make environment variable changes. You need to run `docker compose up -d`, then you should be good :) 

@fddn you shouldn't use the ini files to make configuration changes. Not to mention, it won't work as qe override the ini config via the launch command

**Comment by fast1marine** [comment]
yup rebuilt the container and it still has our game capped at

**Comment by fast1marine** [comment]
@fddn your solution did work. 
@wolveix they are set to the same value currently so if changing the environment variable eventually works they hopefully won't conflict with each other.

**Comment by wolveix** [comment]
@fast1marine then you're using an old version of the container, as we dropped those ini files in 1.7.1 I believe

**Comment by fast1marine** [comment]
satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:v1.7.4'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=8
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G

@wolveix using 1.7.4

**Comment by wolveix** [comment]
@fast1marine hm, that's interesting. My apologies, no one else has had any issues since the config change, and it doesn't really make sense that you _have_.

Could you try upgrading to `v1.8.4`? If that doesn't work, could you send your full container log?

**Comment by wolveix** [comment]
@fast1marine I've just tested this on multiple machines, and cannot reproduce the issue whatsoever. Are you definitely rebuilding your container after making changes? Could you also fill out the full issue template, please?

**Comment by fast1marine** [comment]
@wolveix sorry I have dad duties interfering with me on and off here.  Let me do some save backups and try 1.8.4 we downgraded after getting stuck in a restart loop using latest yesterday.  Can't make my fellow factory friends mad if it's down.

**Comment by wolveix** [comment]
@fast1marine completely understand, no stress! I'm keen to understand what the heck is causing the issue for you, but at least you have a solution that works in the meantime :D

**Comment by fast1marine** [comment]
@wolveix 1.8.4 stuck in a restart loop again :-(

**Comment by wolveix** [comment]
@fast1marine stuck in a restart loop? Could you provide me with your container log?

**Comment by fast1marine** [comment]
@wolveix so I downgraded back to 1.7.4 but i changed the max player variable to 10.  Now it stuck!  not sure what but if there's any logs or whatever you want from me just let me know what to pull for you and I'll send them.

So for the restart loop.  Basically after changing to 1.8.4 the container won't start it basically keeps restarting ever 5 to 10 seconds.  And sorry I'm not the best at containers what directory do I need to pull those from?

**Comment by wolveix** [comment]
@fast1marine that's interesting, I wonder if something was preventing rebuilding or something.

For the logs, when running `v1.8.4`, run this `docker logs satisfactory-server &> output.log`, and then attach the `output.log` file to your response here :)

**Comment by fast1marine** [comment]
@wolveix So I did the log as you said, and I had the QEMU issue listed in your other open issue.  Not sure if it's related at all but now I got 1.8.5 up and running fine so far.   So I'll attach that here and thanks again.  Hope the log file helps.
[output1.log](https://github.com/user-attachments/files/17008991/output1.log)

**Comment by wolveix** [comment]
@fast1marine yep, that explains the reboot loop you mentioned. If you haven't already, you need to change your CPU type to "host" in your VM's settings
