### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by xyzjesper** [wolveix/satisfactory-server#309]
### Describe the Bug

Blueprints not Load. I can't use it

### Screenshots

![image](https://github.com/user-attachments/assets/0bec1ef5-664e-40c1-90b2-ee455b081b31)
![image](https://github.com/user-attachments/assets/644c3f01-8713-4b1a-9eef-35cc185d5380)

### Logs

[FactoryGame.log](https://github.com/user-attachments/files/16994189/FactoryGame.log)

**Comment by wolveix** [comment]
You need to put the blueprints under a directory with the name of your session, that's how the game stores them. Create a blueprint in-game, it'll create the directory for you.

**Comment by xyzjesper** [comment]
True sorry

**Comment by xyzjesper** [comment]
> You need to put the blueprints under a directory with the name of your session, that's how the game stores them. Create a blueprint in-game, it'll create the directory for you.

No 
![image](https://github.com/user-attachments/assets/d5419cbc-beae-496a-8f8d-d8910d72e0f0)

**Comment by xyzjesper** [comment]
And i have created one.
