### ISSUE TITLE
System Crash under Synology DSM 7.1.1 (DSM 7.1.1-42962 Update 5) - Seems to be a Kernel Issue - Not a Container issue

### ISSUE THREAD

**Issue by Hecatonchires667** [wolveix/satisfactory-server#310]
### Describe the Bug

The bug seems to be Kernel-related - not Container related. But i would like to rise awareness.
I would like to cite a reddit post which tells you maybe more than me:

"This is a known issue. You need to use Use lloesche/valheim-server:debian10 instead, Synology uses an old kernel which runs into problem with the latest valheim container running debian11. "

https://www.reddit.com/r/synology/comments/z5vkbr/comment/iy4z8n7/?utm_source=reddit&utm_medium=web2x&context=3

This seems to be a know issue.

Sorry for posting here, but i had a 1 hour near heart-attack experience in the middle of the night (because i was so clever to set the container to autorun ... *haha*)

One of my HDDs won't survive this and begs to be "shot" - hat 12 hard reboots till i fixed this issue.

### Your Runtime Command or Docker Compose File

Please censor anything sensitive. Your runtime command might look like this:

I use the 7.1.1 DSM Docker GUI - The Variables and Startup-Commands are literally from your 2-Step Beginners Guide.

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

Linux pandora 3.10.108 #42962 SMP Fri Mar 24 00:28:41 CST 2023 x86_64 GNU/Linux synology_avoton_1815+

Alternatively, you can find the information manually. Here's what we're looking for:

- OS: [e.g. Ubuntu 18.04 x86_64] (Linux: `uname -a`)
- CPU: INTEL Atom C2538
- RAM: 6GB
- HDD; 10TB
- 
### Logs

Sorry... cant provide due to immidiate crash. Had to enable SSH in a 20-30 Second window after plenty of reboots (hard resets) and to sudo stop docker (htop and killing every docker process) and deleting the docker image/server

### Additional Context

I know this might be only a Synology issue - but maybe there might be a workaround for this. :)

Kind Regards

Marc

**Comment by Hecatonchires667** [comment]
maybe https://github.com/lloesche can shine some light on this because basically the consequences are the same.

**Comment by wolveix** [comment]
@Hecatonchires667 try running the container with following image: `wolveix/satisfactory-server:v1.7.4`

**Comment by Hecatonchires667** [comment]
This Version starts without a crash! :) - Thank you!

**Comment by Hecatonchires667** [comment]
Seems to work - but the system was unresponsive for a moment. Let´s see - In general it seems to work. Downloading stuff right now :)

**Comment by Hecatonchires667** [comment]
Works like a charm! Thanks a lot 💯

**Comment by wolveix** [comment]
@Hecatonchires667 glad to hear it! So, we upgraded the Docker image from Ubuntu 18 to Ubuntu 22 in `v1.8.0`. Looks like that's causing the issue for you.

If possible, you should really upgrade your system's OS as soon as possible, given that Ubuntu 18 reach end of life last year :) I don't intend to put out any future image versions with it, instead using Ubuntu 22 moving forward.

**Comment by Hecatonchires667** [comment]
Thanks for the fast reply!

Unfortunately DSM 7.1.1 is the last OS for my precious Synology 1815+ 😢

The Successor Model costs around 1070€ which is a bit expensive 🫰 for my taste 😢😅

But as long as we can use the older Docker container of yours we are quite happy ❤️❤️❤️

Thanks for your efforts!

Will donate a few bucks 😉😚😊

**Comment by wolveix** [comment]
@Hecatonchires667 hah, yeah that's the problem with locked down systems! Thanks for sharing your perspective with me.

It wouldn't be particularly difficult for me to push an Ubuntu 18 image from time to time, so perhaps I'll do that as a single image tag (e.g. `ubuntu-18`), or I'll test an alternative OS and see whether they work on your system (if you're ever willing to test it on my behalf).

Glad to hear you have a working solution at least, enjoy!!

**Comment by Hecatonchires667** [comment]
Oh this would be awesome! There are plenty of people using Synology NAS who might struggle with this!

I even would suggest a little hint in your leading text for them before they fry their System like I did 🙈

Something like:

"Attention Synology users!
DSM 7.1.x - Please use the 1.7.4 Image
DSM 7.2.x - Please use latest built"

😅

I would of course test an alternative for you. No problem. 😊 But I think every Kernel above 4.x might be an Issue. Even DSM 7.2.x is "only" a heavily modified Ubuntu 19 with a Kernel of 5.x which causes this problem (the first mentioned valheim threads mentioned this).

Ah... Before I forget... Would you provide me your PayPal.me link?

I would like to donate 20€ to you - it's not that much but a sign of appreciation ❤️

Can't find the link via the mobile GitHub app 😅

**Comment by Hecatonchires667** [comment]
Ah! Found the PayPal.me link 😄🤟

**Comment by wolveix** [comment]
@Hecatonchires667 that certainly wasn't necessary, though it is greatly appreciated! Thank you so much! ❤️
