### ISSUE TITLE
docker boot loop

### ISSUE THREAD

**Issue by Sangito-hack** [wolveix/satisfactory-server#314]
### Describe the Bug
I can start the docker since it can not finish the script run.sh  permission deny.

### Your Runtime Command or Docker Compose File

```services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/srv/dev-disk-by-label-Sharefile/Appdata/satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

```

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

```shell
===== Satisfactory Server 1.8.4 =====
https://github.com/wolveix/satisfactory-server
Debugging enabled (the container will exit after printing the debug info)
Printing environment variables:
declare -x AUTOSAVENUM="5"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/home/steam"
declare -x HOSTNAME="satisfactory-server"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOG="true"
declare -x MAXOBJECTS="2162688"
declare -x MAXPLAYERS="4"
declare -x MAXTICKRATE="30"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="100"
declare -x PUID="1000"
declare -x PWD="/config"
declare -x ROOTLESS="false"
declare -x SERVERGAMEPORT="7777"
declare -x SERVERSTREAMING="true"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x TIMEOUT="30"
declare -x USER="steam"
declare -x VERSION="1.8.4"
declare -x VMOVERRIDE="false"
      
System info:
OS:  Linux satisfactory-server 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Pentium(R) CPU G4560 @ 3.50GHz
RAM: 14GB/15GB
HDD: 17GB/102GB (18% used)
Current version:
1.8.4
Current user:
uid=0(root) gid=0(root) groups=0(root)
Proposed user:
uid=1000(?) gid=100(?) groups=100(?)
Exiting...

```

### System Specs (please complete the following information):

```shell
echo "===== START ISSUE REPORT =====
OS:  Linux katte 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
CPU: $(Intel(R) Pentium(R) CPU G4560 @ 3.50GHz)
RAM: $(16)GB
HDD: $(17GB/102GB (18% used))
===== END ISSUE REPORT ====="
```

### Logs

===== Satisfactory Server 1.8.4 =====
https://github.com/wolveix/satisfactory-server
Checking available memory: 14GB detected
Setting autosave number to 5
Setting max objects to 2162688
Setting max tick rate to 30
Setting server streaming to 1
Setting timeout to 30
Setting max players to 4
Checking available storage: 2677GB detected
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
Logging directory: '/home/steam/.steam/steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1726260406
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 50 msec
OK
Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.22 (9437184 / 4303607233)
 Update state (0x5) verifying install, progress: 18.14 (780603493 / 4303607233)
 Update state (0x5) verifying install, progress: 39.22 (1687893690 / 4303607233)
 Update state (0x5) verifying install, progress: 59.86 (2576097878 / 4303607233)
 Update state (0x5) verifying install, progress: 80.88 (3480855872 / 4303607233)
Success! App '1690800' fully installed.
Launching game server
/home/steam/run.sh: line 107: ./FactoryServer.sh: Permission denied

### Additional Context
lin 107:
exec ./FactoryServer.sh -Port="$SERVERGAMEPORT" "${ini_args[@]}" "$@"

The docker refuse to execute FactoryServer.sh

**Comment by wolveix** [comment]
Hey @Sangito-hack, did you modify your `/config/gamefiles` directory's permissions?

Try deleting that directory entirely, and rebuilding the container

**Comment by Sangito-hack** [comment]
I check the permission of the /config file inside and out of the docker.
i have try to rebuilder the docker dozen of time, with no result.
I also try the "ROOTLESS" thing without any success.
I still can explain with the docker remove right to execute when it launch the run.sh script.
I bypass this by changing the line:
`exec ./FactoryServer.sh -Port="$SERVERGAMEPORT" "${ini_args[@]}" "$@"`
by 
` bash ./FactoryServer.sh -Port="$SERVERGAMEPORT" "${ini_args[@]}" "$@"`
It work but FactoryServer.sh lost it faculty to execute anything else outside /bin or /sbin...
so no: `"$UE_PROJECT_ROOT/Engine/Binaries/Linux/FactoryServer-Linux-Shipping" FactoryGame "$@" `
For me it make no sense that a file with right 0777 cannot be execute...

**Comment by wolveix** [comment]
Your proposed user doesn't match the information in your Docker Compose. Are you definitely passing in PUID and PGID as 1000? I've never seen someone experience this issue before.

Please try `v1.8.5`. If that doesn't work, please try `v1.7.4`

**Comment by Sangito-hack** [comment]
I i set the PUID and the GUID to fit my system and verify it match the one inside the docker.
I try version 1.8.5, 1.8.4, 1.8.3, 1.7.4
Always the same issue:
`/home/steam/run.sh: line 103: /config/gamefiles/FactoryServer.sh: Permission denied`

**Comment by Sangito-hack** [comment]
after some test it look like the permission deny only touch thing inside the /config folder...

**Comment by wolveix** [comment]
I mentioned the proposed user because your Docker Compose does not match the log you provided. Could you run please send the output of running `ls -lah` in `/config/gamefiles`?

Additionally, please test this without specifying PUID and PGID, as well as without binding the volume mount

**Comment by Sangito-hack** [comment]
I already test i with original PUID and PGID, still crash by now instead of group users the repertory is in SFTP_ACCESS group
right. 
Event if change to 00777 still not execute and go permission deny
I try to execute an other script for testing purpose 
`#/bin/bs`
`echo "It's work"`
Work in anywhere in the docker except in the /config.
I have like 6 docker on my computer, I try all 6 of them and they have the same issue.
Look like my docker add some security filtering mask not mention anywhere in there documentation.

**Comment by wolveix** [comment]
Could you please test the two things I requested? :)

**Comment by Sangito-hack** [comment]
Ask so politely how to refuse:
![image](https://github.com/user-attachments/assets/6df3e087-e6ac-4497-819f-3f181fc2d96d)
Also i make it work by using the Docker volume the execution restriction was lift.
Still this behavior cannot be explained easily or rapidly.

**Comment by wolveix** [comment]
@Sangito-hack obviously there's a language barrier here. Yes, as I suggested, not binding a directory was likely to work as you have interesting permissions configured on your system.

I recommend binding `/config/saves` at least to persist your save data
