### ISSUE TITLE
Timestamps in logs not honoring TZ

### ISSUE THREAD

**Issue by varinyc** [wolveix/satisfactory-server#316]
The time, date, and timezone of my container are set up correctly, and I've verified the container `date` is displaying the correct information. The date, time, and timezone of my server pc are also correct.

But the timestamps for the log are not correct.

I passed in TZ to the docker-compose, I even mounted
            - '/etc/localtime:/etc/localtime:ro'
            - '/usr/share/zoneinfo:/usr/share/zoneinfo:ro'
            
None of these have changed the display of the timestamps in the logs.

It currently 9/15/24 at 9:34AM

This what the log format displaying:
[2024.09.15-14.34.51:785][298]

**Comment by wolveix** [comment]
Hey @varinyc. This is a known game bug, and is not a flaw of the Docker image. As such, there's nothing I can do to change it unfortunately. The logs all use UTC
