### ISSUE TITLE
Unraid specific, unable to run after permission reset

### ISSUE THREAD

**Issue by CrapuleJack** [wolveix/satisfactory-server#320]
### Describe the Bug

Unraid has a tool to reset all permissions on all files across the whole NAS. this tool is ->very<- usefull and often used BUT it removes the executable bit on .sh files.

With the "Config" folder properly bound to a local directory, the FactoryServer.sh file gets its execute bit removed every time the tool is run. This prevent the server from starting properly on next restart.

### Your Runtime Command or Docker Compose File
[nothing special here, I followed your readme]

### Debug Output
```
satisfactory  | Success! App '1690800' fully installed.
satisfactory  | Launching game server
satisfactory  |
satisfactory  | /home/steam/run.sh: line 107: ./FactoryServer.sh: Permission denied
```

### SOLUTION:
Can you please add a "chmod +x " on FactoryServer.sh before you try to run it, pretty please :)

**Comment by wolveix** [comment]
Guessing this is the same issue as #314 :) Sure, I can do that tomorrow

**Comment by CrapuleJack** [comment]
Sure looks like it
I was about to provide a commit and pull request, looks like you have that locked down

Thanks for responding so fast :)

**Comment by wolveix** [comment]
@CrapuleJack you should be able to fork and PR, as many others have :)

**Comment by KyleDiao** [comment]
but this cause my server can't start even its execute bit is on, the user runs the server just cant do the chmod operation
: chmod: changing permissions of 'FactoryServer.sh': Operation not permitted

**Comment by wolveix** [comment]
@KyleDiao please test `wolveix/satisfactory-server:dev` :)

**Comment by KyleDiao** [comment]
> @KyleDiao please test `wolveix/satisfactory-server:dev` :)

@wolveix it's ok now, the server is running and we can play, thx
![log](https://github.com/user-attachments/assets/97511898-4ff2-4df7-af9e-77f1a5f3da69)
