### ISSUE TITLE
Game client updated to 367101. Docker server version still at 366202

### ISSUE THREAD

**Issue by JigglesTheFett** [wolveix/satisfactory-server#325]
Pretty straightforward, game updated, can't connect to server anymore. Assuming the container needs to be updated with the newest server version.
![image](https://github.com/user-attachments/assets/929487cc-42af-46fd-bae3-6d53a1425d3a)

**Comment by myrcutio** [comment]
the game files aren't stored in the container, they're in a volume mount.  you should be able to recreate the container and the server should automatically update.  I just restarted my k8s pod and it picked up the latest.

**Comment by JigglesTheFett** [comment]
Well then, don't I feel dumb! Thank you.
