### ISSUE TITLE
Client/Server Mismatch 1.0 Hotfix v1.0.0.2

### ISSUE THREAD

**Issue by saedrin** [wolveix/satisfactory-server#327]
A client update has been forced through Steam and we're seeing a client/server version mismatch on attempting to join.

**Comment by gotanks0407** [comment]
If you restart your container it will check for latest version available on steam and download it. Please restart your container to get the latest version. If that does not work. Then it is not available on Steam yet. If you are playing with EPIC launcher this has happened in the past.

**Comment by saedrin** [comment]
> If you restart your container it will check for latest version available on steam and download it. Please restart your container to get the latest version. If that does not work. Then it is not available on Steam yet. If you are playing with EPIC launcher this has happened in the past.

Great to know, thank you very much for the reply. Go figure, in the last hour they must have updated the server binary and we're back in business
