### ISSUE TITLE
Server crashes while playing got memory error

### ISSUE THREAD

**Issue by Dexy2811** [wolveix/satisfactory-server#338]
### Describe the Bug
users of the server reported a bug where they were just on playing and server crashed and reboots.
the title of the diagnostics log is: 

Application version 5.3.2.0
 ... built from changelist 365306

OS version Linux 6.1.82-Unraid (network name: satisfactory-server)
Running 6 x86_64 processors (12 logical cores)
Exception was "SIGSEGV: invalid attempt to read memory at address 0x0000000000000000"

### Your Runtime Command or Docker Compose File

services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        network_mode: 'host'
        ports:
            - 7777:7777/udp
            - 7777:7777/tcp
        volumes:
            - /mnt/disk1/appdata/docker/satisfactory/config:/config
        environment:
            - MAXPLAYERS=10
            - PGID=1000
            - PUID=1000
            - ROOTLESS=false
            - STEAMBETA=false
            - AUTOSAVEINTERVAL=60
            - AUTOSAVEONDISCONNECT=true
            - CRASHREPORT=true
            - MAXTICKRATE=60
        restart: always
        deploy:
          resources:
            limits:
              memory: 16G
            reservations:
              memory: 8G

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

[FactoryGamewithDebugenabled.log](https://github.com/user-attachments/files/17116806/FactoryGamewithDebugenabled.log)

### System Specs (please complete the following information):

Alternatively, you can find the information manually. Here's what we're looking for:

OS:  Linux 6.1.82-Unraid (Docker for satisfactory server)
CPU: Intel® Core™ i7-8700 CPU @ 3.20GHz
RAM: 32GB
SSD: 1TB

### Logs
[FactoryGame.log](https://github.com/user-attachments/files/17116692/FactoryGame.log)

### Additional Context

Not sure if it is the containers fault or actually a bug report i should send to Coffestain?

**Comment by wolveix** [comment]
@Dexy2811 this is unfortunately a known game bug. Please check the official Satisfactory Discord for more information :)
