### ISSUE TITLE
FactoryServer.sh unable to execute

### ISSUE THREAD

**Issue by Khasir** [wolveix/satisfactory-server#339]
### Describe the Bug

I'm trying to run this container on Google Compute Engine when I run into an error. `run.sh` fails when trying to run `FactoryServer.sh`. Might be related to issues #314 and #320?

```
/home/steam/run.sh: line 108: ./FactoryServer.sh: Permission denied
```

### Your Runtime Command or Docker Compose File

```sh
docker run \
--sig-proxy=false \
--name=satisfactory-server \
--hostname satisfactory-server \
--rm \
--volume ./satisfactory-server:/config \
--env MAXPLAYERS=4 \
--env ROOTLESS=false \
--env STEAMBETA=false \
--env PGID=20166 \
--env PUID=20162 \
--memory 12G \
--publish 7777:7777/udp \
--publish 7777:7777/tcp \
wolveix/satisfactory-server:latest
```

### Debug Output

```shell
===== Satisfactory Server 1.8.6 =====
https://github.com/wolveix/satisfactory-server

Debugging enabled (the container will exit after printing the debug info)

Printing environment variables:
declare -x AUTOSAVENUM="5"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/home/steam"
declare -x HOSTNAME="satisfactory-server"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOG="false"
declare -x MAXOBJECTS="2162688"
declare -x MAXPLAYERS="4"
declare -x MAXTICKRATE="30"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="20166"
declare -x PUID="20162"
declare -x PWD="/config"
declare -x ROOTLESS="false"
declare -x SERVERGAMEPORT="7777"
declare -x SERVERSTREAMING="true"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x TIMEOUT="30"
declare -x USER="steam"
declare -x VERSION="1.8.6"
declare -x VMOVERRIDE="false"

System info:
OS:  Linux satisfactory-server 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sat Sep 21 16:23:38 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
RAM: 15GB/16GB
HDD: 4GB/16GB (29% used)

Current version:
1.8.6
Current user:
uid=0(root) gid=0(root) groups=0(root)
Proposed user:
uid=20162(?) gid=20166(?) groups=20166(?)

Exiting...
```

### System Specs (please complete the following information):

```shell
===== START ISSUE REPORT =====
OS:  Linux satisfactory-server-20240924 6.1.100+ #1 SMP PREEMPT_DYNAMIC Sat Sep 21 16:23:38 UTC 2024 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
RAM: 15GB/16GB
HDD: 1GB/2GB (60% used)
===== END ISSUE REPORT =====
```

### Logs

[satisfactory-server-log-240924.txt](https://github.com/user-attachments/files/17121824/satisfactory-server-log-240924.txt)

### Additional Context

My current user:
```sh
$ id
uid=20162(me) gid=20166(me) groups=20166(me),4(adm),27(video),412(docker),20165(google-sudoers)
```

I've also tried this with `PGID=0`, `PUID=0` but your script doesn't allow for that. 

Also tried `--ROOTLESS=true --user=20162:20166` but run into permissions denied issues:
```sh
$ docker run \
> --sig-proxy=false \
> --name=satisfactory-server \
> --hostname satisfactory-server \
> --rm \
> --volume ./satisfactory-server:/config \
> --env MAXPLAYERS=4 \
> --env ROOTLESS=true \
> --env STEAMBETA=false \
> --env PGID=20166 \
> --env PUID=20162 \
> --user 20162:20166 \
> --memory 12G \
> --publish 7777:7777/udp \
> --publish 7777:7777/tcp \
> wolveix/satisfactory-server:latest
===== Satisfactory Server 1.8.6 =====
https://github.com/wolveix/satisfactory-server

Checking available memory: 15GB detected
Clearing old Satisfactory logs (set LOG=true to disable this)
The current user does not have write permissions for /config
```

**Comment by wolveix** [comment]
This suggests that there's a permissions issue on the host itself, which the container is unable to resolve. Please verify that your `./satisfactory-server` path is correctly owned by your specified PUID/PGID.

**Comment by Khasir** [comment]
I ran `sudo chown -R me satisfactory-server` but that wasn't the solution. It turns out that the VM image I was using (container-optimized OS / cos-113-18244-151-80) [disables execution of scripts and executables by default](https://stackoverflow.com/a/50279396). I had to remount my disk without `noexec` for it to work properly. Thanks for the help!

**Comment by linton1187** [comment]
> I ran `sudo chown -R me:me satisfactory-server` but that wasn't the solution. It turns out that the VM image I was using (container-optimized OS / cos-113-18244-151-80) [disables execution of scripts and executables by default](https://stackoverflow.com/a/50279396). I had to remount my disk without `noexec` for it to work properly. Thanks for the help!

Hey there!

I'm struggling with the exact same issue. I'm a complete and total noob and need to do this in my unraid server. Wondering if I could get some assistance or guidance on this if possible.

**Comment by Khasir** [comment]
@linton1187 Is this a local machine? Can you check if your user is the owner of the `./satisfactory-server` folder? I can provide you with commands if you're not familiar.
