### ISSUE TITLE
Feature Request - Have an option to change when the daily restart happens on the server

### ISSUE THREAD

**Issue by AidanHarveyNelson** [wolveix/satisfactory-server#341]
I can see that every day the server restarts and on restarts checks and updates the server at 12 AM UTC+.

Depending on where you are in the world this can be annoying as the updates won't apply by the time you wake up and can restart at an inconvenient time.

It would be useful to have an environment variable we can set that can tell the server when to perform the restart (In UTC). Let me know if you think this would be helpful, happy to have a crack at putting a PR up for this.

**Comment by AidanHarveyNelson** [comment]
My understanding is incorrect for any future people.

Dedicated server will restart every 24 hours (Configurable) so restart it at the desired time you want the restart to happen and it will continue to do that.

**Comment by wolveix** [comment]
@AidanHarveyNelson this isn't a container feature, this is the game server. You can adjust the time it automatically restarts through the in-game server manager. It says restart interval, it's actually the time it'll restart (usually in UTC)

**Comment by seigneurao** [comment]
OMG wasn't aware of that. What you're basically saying is, the 24-hour interval can't be modified, but the time of the restart can ?
Awesome ! Thanks a lot.
