### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by Eri-tog** [wolveix/satisfactory-server#345]
### Describe the Bug
Trying this fix for a timeout issue on the server : 
https://questions.satisfactorygame.com/post/62572a7cca608e080350c2ad 
The engine.ini file that I'm using is currently rewritten and I loose the time out config everytime I redeploy the the container. 
I am trying to set the following in the engine.ini file (.../gamefiles/FactoryGame/Saved/Config/LinuxServer/) : 
```shell
[/Script/OnlineSubsystemUtils.IpNetDriver]
InitialConnectTimeout=30.0
ConnectionTimeout=60.0
```
The server itself crash due to what seems like a time out of more than 30sec for the save to write. Hardware wise, all config are already on a separate N100 beelink computer with files stored on the internal SSD (M.2 I believe) 

### Your Runtime Command or Docker Compose File

Please censor anything sensitive. Your runtime command might look like this:

```shell
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/docker/satisfactory-server:/config'
    dns:
      - 192.168.0.49
      - 1.1.1.1  # DNS servers to use within the container
      - 1.0.0.1
    environment:
      - MAXPLAYERS=4
      - TZ="America/Montreal"
      - PGID=1001
      - PUID=1001
      - ROOTLESS=false
      - STEAMBETA=false
      - TIMEOUT=120
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 12G
          cpus: 3.5
        reservations:
          memory: 10G
```

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

```shell
OUTPUT HERE
```

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

```shell
===== START ISSUE REPORT =====
OS:  Linux docker 6.5.13-3-pve #1 SMP PREEMPT_DYNAMIC PMX 6.5.13-3 (2024-03-20T10:45Z) x86_64 GNU/Linux
CPU: Intel(R) N100
BIOS Intel(R) N100 To Be Filled By O.E.M. CPU @ 2.8GHz
RAM: 11GB/14GB
HDD: 39GB/99GB (41% used)
===== END ISSUE REPORT =====
```

### Logs

[_satisfactory-server_logs.txt](https://github.com/user-attachments/files/17155603/_satisfactory-server_logs.txt)

### Additional Context

It's hard to maintain a stable container, I have health check enable and I often have my container turning to unhealthy in portainer when I leave it running overnight. I did disable the auto-pause recently (but the issue was happening before too) 
Thank you!

**Comment by wolveix** [comment]
Hi @Eri-tog, you should not modify ini files directly, and should instead use the environment variables (the `TIMEOUT` variable modifies those values for you).

Additionally, your instability issues will be due to your CPU's low single-core performance. As mentioned in various other issues, Satisfactory requires a single-core passmark score of approximately 3000+, while yours is ~1900.

**Comment by Eri-tog** [comment]
I see - Thank you @wolveix ! I will setup a longer time out and get a more powerful dedicated server, until then I think I think i'll look into a save sync solution ! :)

**Comment by wolveix** [comment]
@Eri-tog if you do want a save sync solution, do take a look at the `saveshare` directory on this repo :) I wrote it for exactly that reason
