### ISSUE TITLE
Explain Your Issue

### ISSUE THREAD

**Issue by Maxdola** [wolveix/satisfactory-server#350]
### Describe the Bug

Every time I try to open the Server URL in the browser I get the following error:

```shell
[2024.09.29-14.19.54:478][182]LogSocketsSSL: Warning: Failed to initialize SSL state for Socket HttpRequest
[2024.09.29-14.19.54:478][182]LogHttpListener: Error: Error accepting expected connection [0] SE_NO_ERROR
```

From the game client, the server appears as offline.

### Your Runtime Command or Docker Compose File

Please censor anything sensitive. Your runtime command might look like this:

```shell
services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - DEBUG=false
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 8G

```

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

```shell
===== Satisfactory Server 1.8.7 =====
https://github.com/wolveix/satisfactory-server
Debugging enabled (the container will exit after printing the debug info)
Printing environment variables:
declare -x AUTOSAVENUM="5"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/home/steam"
declare -x HOSTNAME="satisfactory-server"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOG="false"
declare -x MAXOBJECTS="2162688"
declare -x MAXPLAYERS="4"
declare -x MAXTICKRATE="30"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="1000"
declare -x PUID="1000"
declare -x PWD="/config"
declare -x ROOTLESS="false"
declare -x SERVERGAMEPORT="7777"
declare -x SERVERSTREAMING="true"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x TIMEOUT="30"
declare -x USER="steam"
declare -x VERSION="1.8.7"
declare -x VMOVERRIDE="true"
System info:
OS:  Linux satisfactory-server 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 5 5600X 6-Core Processor
RAM: 15GB/15GB
HDD: 11GB/31GB (38% used)
Current version:
1.8.7
Current user:
uid=0(root) gid=0(root) groups=0(root)
Proposed user:
uid=1000(?) gid=1000(?) groups=1000(?)
```

### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

```shell
===== START ISSUE REPORT =====
OS:  Linux satisfactory 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
CPU: AMD Ryzen 5 5600X 6-Core Processor
BIOS pc-i440fx-8.1  CPU @ 2.0GHz
RAM: 15GB/15GB
HDD: 11GB/31GB (38% used)
===== END ISSUE REPORT =====
```

The Container is run within a VM created on a Proxmox server.

### Logs
[satisfactory-server_logs.txt](https://github.com/user-attachments/files/17179642/satisfactory-server_logs.txt)

**Comment by wolveix** [comment]
This is not a container issue, please ask for help in the official Satisfactory Discord

**Comment by Maxdola** [comment]
> This is not a container issue, please ask for help in the official Satisfactory Discord.
> 
> Your issue is almost definitely networking-related within your environment, as it almost always is. Please see the many, many other issues and discussions others have opened.

How can this be a network issue, when the server has a static IP and I see the Log in the console. And there is a connection indicated by the log.

**Comment by wolveix** [comment]
@Maxdola please take a look at the other issues :) If when trying to connect to the server through the in-game Server Manager you receive a "server offline" message, then your client is unable to reach the server on `7777/udp`. Your `7777/tcp` port is clearly allowed through your firewall given that you're able to hit it via your browser, but it sounds like `7777/udp` is not.

**Comment by wolveix** [comment]
I just searched your exact issue and found your Reddit post where you provided more information. Do note, per the repo's troubleshooting guide, you **cannot** connect to your server via your external IP, and must use your internal IP if you're within the same network as your server. It generally **does not** work for Satisfactory.

That doesn't mean external connections aren't working.

**Comment by Maxdola** [comment]
> I just searched your exact issue and found a Reddit post (presumably yours given the username and timestamp) where you provided more information. Do note, per the repo's troubleshooting guide, you **cannot** connect to your server via your external IP, and must use your internal IP if you're within the same network as your server. It generally **does not** work for Satisfactory.
> 
> That doesn't mean external connections aren't working.

Can you please send me the link to my reddit post? Because I didn't make a Reddit post. And the Server is not in my local network. The server is on a remote machine.

**Comment by wolveix** [comment]
My apologies, the timeframe matched up, the error looks to be the same, and your usernames are similar:

https://www.reddit.com/r/SatisfactoryGame/comments/1fsewmg/satisfactory_docker_server/

As mentioned, please ask for help in the Satisfactory Discord. Your Satisfactory game client is unable to reach your server's `7777/udp` port (evident by the server appearing offline in-game, despite your ability to reach `7777/tcp`).
