### ISSUE TITLE
[SOLUTION] Bad request: json: cannot unmarshal string

### ISSUE THREAD

**Issue by RedC4ke** [wolveix/satisfactory-server#351]
### Describe the Bug

When using Docker Compose, I'm getting the error. I don't know if it's version dependent, a bug in the compose file or just because I'm using Cosmos Cloud GUI (it parses the compose to a json format with strings in double quotes). 

```
[OPERATION FAILED] Bad request: json: cannot unmarshal string into Go struct field ContainerCreateRequestContainerHealthcheck.services.healthcheck.test of type []string%!(EXTRA int=400, string=DS003){"status":"error","message":"Bad request: json: cannot unmarshal string into Go struct field ContainerCreateRequestContainerHealthcheck.services.healthcheck.test of type []string","code":"DS003"}
```

### Your Runtime Command or Docker Compose File

@7e1ae65d3e59919ee5bff9196ecaa9bf8ed25500 
docker-compose.yaml

### System Specs 

```
===== START ISSUE REPORT =====
OS:  Linux htpc 6.1.0-25-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.106-3 (2024-08-26) x86_64 GNU/Linux
CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
RAM: 12GB/15GB
HDD: 42GB/233GB (19% used)
===== END ISSUE REPORT =====
```

### Found solution

You have to wrap the healthcheck command in a list of strings like this:
```
healthcheck:
      test  ["bash /healthcheck.sh"]
```

**Comment by wolveix** [comment]
Hey @RedC4ke, that seems to be an interesting quirk unique to your environment, I suspect due to your Cosmos Cloud GUI

**Comment by wolveix** [comment]
Though admittedly from reviewing the Docker spec, it _should_ be an array :) I'll make that adjustment, thanks!

https://docs.docker.com/reference/compose-file/services/#healthcheck
