### ISSUE TITLE
docker compose environment variable for lognet log level not setting log level in server

### ISSUE THREAD

**Issue by g-silliman** [wolveix/satisfactory-server#360]
The recently implemented lognet log level environment variable is not properly setting the lognet log level at startup.

docker-compose.yml:
```services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - './satisfactory-server:/config'
    environment:
      - MAXPLAYERS=4
      - PGID=1000
      - PUID=1000
      - ROOTLESS=false
      - STEAMBETA=false
      - LOG=true
      - LOGNETLEVEL=Log
    restart: unless-stopped
    healthcheck:
      test: bash /healthcheck.sh
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 6G
        reservations:
          memory: 4G
```

### Debug Output

```
satisfactory-server  | System info:
satisfactory-server  | OS:  Linux satisfactory-server 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
satisfactory-server  | CPU: AMD Opteron(tm) Processor 4386
satisfactory-server  | RAM: 15GB/15GB
satisfactory-server  | HDD: 20GB/24GB (87% used)
satisfactory-server  |
satisfactory-server  | Current version:
satisfactory-server  | 1.8.7
satisfactory-server  | Current user:
satisfactory-server  | uid=0(root) gid=0(root) groups=0(root)
satisfactory-server  | Proposed user:
satisfactory-server  | uid=1000(?) gid=1000(?) groups=1000(?)
satisfactory-server  |
satisfactory-server  | Exiting...
```

### System Specs (please complete the following information):

```===== START ISSUE REPORT =====
OS:  Linux satisfactory 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Opteron(tm) Processor 4386
RAM: 14GB/15GB
HDD: 20GB/24GB (88% used)
===== END ISSUE REPORT =====

```

### Logs
[container.log](https://github.com/user-attachments/files/17382246/container.log)

**Comment by dragonis41** [comment]
I am trying to do the same thing since yesterday and I struggle too. `LogNet:` Does not show up in the logs

**Comment by wolveix** [comment]
@joshenders could you take a look at this? It's been a minute since I've looked at Unreal's logging parameters

**Comment by wolveix** [comment]
@dragonis41 @g-silliman please try `ghcr.io/wolveix/satisfactory-server:360`. I've removed the log parameters as it seems specifying them disables them for Satisfactory (or at least, alters them in an unusual way)

**Comment by dragonis41** [comment]
I confirm that it works with this version

**Comment by wolveix** [comment]
Thanks for confirming @dragonis41, I've rolled the log variable changes back until we're able to investigate them further. Thanks again for your contribution @joshenders :) I've experimented with the different log variables a lot in the past, but found them to behave very strangely compared to Unreal's documentation

**Comment by dragonis41** [comment]
Thank you for your time and for your work :)
