### ISSUE TITLE
linux/arm64/v8 not supported

### ISSUE THREAD

**Issue by reyes256** [wolveix/satisfactory-server#363]
Tried creating a server on a Oracle cloud free tier machine which runs on linux/arm64/v8

### Error

 ! satisfactory-server The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested                                         0.0s 
Attaching to satisfactory-server
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server exited with code 0
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server  | exec /init.sh: exec format error
satisfactory-server  | exec /init.sh: exec format error

**Comment by wolveix** [comment]
Duplicate #174

**Comment by jrcichra** [comment]
I was able to boot the satisfactory server on a Raspberry Pi 4 by setting up the game files on an AMD64 system, then on the Pi running https://github.com/tonistiigi/binfmt and then ghcr.io/wolveix/satisfactory-server but you have to set SKIPUPDATE to true so you don't emulate steamcmd (it segfaults). You basically want to get it to start up FactoryGame straight without steam involved.

I was able to eventually connect to the server but the tick rate is really bad. Not enough cpu power with a Pi + qemu userspace emulation. You'll warp around a map a lot.

If I try a Pi 5 it segfaults early. Must be some difference between ARM Cortex-A72 and ARM Cortex-A76 and qemu support.

So it's "possible" it's just not playable at all. :). Fun as an experiment though!
