### ISSUE TITLE
Please update the container to support version 1.0.0.5

### ISSUE THREAD

**Issue by wsvoorhees** [wolveix/satisfactory-server#366]
### Describe the Bug
I cannot connect to my server since there is a version mismatch since Steam updated my client.

### Additional Context

[Add any other context about the problem here.]
Release Notes
(https://questions.satisfactorygame.com/post/6728ef53ddb9d97e0720c4ae)

**Comment by Navok85** [comment]
Can't relate your problem. I have no problem with 1.0.0.5

Just restart the container. (docker compose down / docker compose up -d)

The deticated server is updated during the start of the container. 

You should see something like that in the logs

Downloading the latest version of the game...
Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
[  0%] Checking for available update...
[----] Downloading update (0 of 48,914 KB)...
[  0%] Downloading update (0 of 48,914 KB)...
[  0%] Downloading update (0 of 48,914 KB)...
[  0%] Downloading update (4,046 of 48,914 KB)...
[  8%] Downloading update (8,670 of 48,914 KB)...
[ 17%] Downloading update (12,488 of 48,914 KB)...
[ 25%] Downloading update (15,992 of 48,914 KB)...
[ 32%] Downloading update (19,498 of 48,914 KB)...
[ 39%] Downloading update (22,995 of 48,914 KB)...
[ 47%] Downloading update (26,126 of 48,914 KB)...
[ 53%] Downloading update (29,599 of 48,914 KB)...
[ 60%] Downloading update (32,746 of 48,914 KB)...
[ 66%] Downloading update (36,236 of 48,914 KB)...
[ 74%] Downloading update (39,371 of 48,914 KB)...
[ 80%] Downloading update (42,755 of 48,914 KB)...
[ 87%] Downloading update (44,459 of 48,914 KB)...
[ 90%] Downloading update (46,135 of 48,914 KB)...
[ 94%] Downloading update (47,814 of 48,914 KB)...
[ 97%] Downloading update (48,914 of 48,914 KB)...
[100%] Download Complete.
[----] Applying update...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching...
Redirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
Logging directory: '/home/steam/.steam/steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
[  0%] Downloading update...
[  0%] Checking for available updates...
[----] Download complete.
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Extracting package...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Installing update...
[----] Cleaning up...
[----] Update complete, launching Steamcmd...
steamcmd.sh[39]: Restarting steamcmd by request...
UpdateUI: skip show logoRedirecting stderr to '/home/steam/.steam/steam/logs/stderr.txt'
Logging directory: '/home/steam/.steam/steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1728594755
-- type 'quit' to exit --
Loading Steam API...IPC function call IClientUtils::GetSteamRealm took too long: 57 msec
IPC function call IClientUtils::GetConnectedUniverse took too long: 53 msec
OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
IPC function call IClientAppManager::GetUpdateInfo took too long: 105 msec
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) verifying install, progress: 1.95 (83738574 / 4304528671)
 Update state (0x5) verifying install, progress: 5.97 (256832103 / 4304528671)
 Update state (0x5) verifying install, progress: 7.77 (334255910 / 4304528671)
 Update state (0x5) verifying install, progress: 9.09 (391329769 / 4304528671)
 Update state (0x5) verifying install, progress: 10.48 (451155981 / 4304528671)
 Update state (0x5) verifying install, progress: 12.95 (557402011 / 4304528671)
 Update state (0x5) verifying install, progress: 15.51 (667502491 / 4304528671)
 Update state (0x5) verifying install, progress: 16.29 (701056923 / 4304528671)
 Update state (0x5) verifying install, progress: 16.34 (703154075 / 4304528671)
 Update state (0x5) verifying install, progress: 16.38 (705251227 / 4304528671)
 Update state (0x5) verifying install, progress: 19.26 (828917918 / 4304528671)
 Update state (0x5) verifying install, progress: 22.20 (955717292 / 4304528671)
 Update state (0x5) verifying install, progress: 25.39 (1092716994 / 4304528671)
 Update state (0x5) verifying install, progress: 28.18 (1213083550 / 4304528671)
 Update state (0x5) verifying install, progress: 31.37 (1350383761 / 4304528671)
 Update state (0x5) verifying install, progress: 34.69 (1493055633 / 4304528671)
 Update state (0x5) verifying install, progress: 37.78 (1626159249 / 4304528671)
 Update state (0x5) verifying install, progress: 42.63 (1834958417 / 4304528671)
 Update state (0x5) verifying install, progress: 45.72 (1968188655 / 4304528671)
 Update state (0x5) verifying install, progress: 47.92 (2062606212 / 4304528671)
 Update state (0x5) verifying install, progress: 50.67 (2180915636 / 4304528671)
 Update state (0x5) verifying install, progress: 53.70 (2311735739 / 4304528671)
 Update state (0x5) verifying install, progress: 57.40 (2470731353 / 4304528671)
 Update state (0x5) verifying install, progress: 64.02 (2755653082 / 4304528671)
 Update state (0x5) verifying install, progress: 67.99 (2926506775 / 4304528671)
 Update state (0x5) verifying install, progress: 72.69 (3128906744 / 4304528671)
 Update state (0x5) verifying install, progress: 77.76 (3347010524 / 4304528671)
 Update state (0x5) verifying install, progress: 81.58 (3511756455 / 4304528671)
 Update state (0x5) verifying install, progress: 85.65 (3687019494 / 4304528671)
 Update state (0x5) verifying install, progress: 89.10 (3835305288 / 4304528671)
 Update state (0x5) verifying install, progress: 91.73 (3948550480 / 4304528671)
 Update state (0x5) verifying install, progress: 95.03 (4090532296 / 4304528671)
 Update state (0x5) verifying install, progress: 98.42 (4236631995 / 4304528671)
 Update state (0x61) downloading, progress: 40.81 (513291436 / 1257912100)
 Update state (0x61) downloading, progress: 85.41 (1074410668 / 1257912100)
 Update state (0x81) verifying update, progress: 10.39 (130758603 / 1257912100)
 Update state (0x81) verifying update, progress: 39.18 (492871175 / 1257912100)
 Update state (0x81) verifying update, progress: 91.56 (1151781418 / 1257912100)
IPC function call IClientAppManager::GetUpdateInfo took too long: 48 msec
Success! App '1690800' fully installed.

**Comment by wolveix** [comment]
@wsvoorhees the image doesn't store the game files as they're automatically updated on container startup. Please restart the container, and ensure that `SKIPUPDATE` isn't set to `true`.

**Comment by wsvoorhees** [comment]
Yes, your right! I followed your recommendation, and did see in the logs that it pulled the new version, and it's up and running great now. Thank you!
