### ISSUE TITLE
Feature: More server config via environment variables(?)

### ISSUE THREAD

**Issue by voruti** [wolveix/satisfactory-server#372]
The [patch notes of the latest version `v1.0.1.0 - Build 382498`](https://questions.satisfactorygame.com/post/67488665c11fcb08da7e112c) state that:
> - The following command line ini overrides are now allowed
>   - (-CustomConfig= and -ini:Config:[Section]:Value=)

Can they be used to (re-)introduce more environment variables which set the in-game server settings?

Also, maybe there are other additional use cases for those command line overrides for use in this Docker project ...

**Comment by wolveix** [comment]
Hey @voruti, we've been using these since September 11th: https://github.com/wolveix/satisfactory-server/commit/a151b0c96c52858a813deb955362cbc951b25eb2

If there are any settings in particular that you're interested, please feel free to re-open :)
