### ISSUE TITLE
Steamcmd Exec format error

### ISSUE THREAD

**Issue by sconosciute** [wolveix/satisfactory-server#380]
### Describe the Bug

When attempting to start the container it hangs with the following error:

```
/home/steam/.local/share/Steam/steamcmd/steamcmd.sh: line 37: /home/steam/.local/share/Steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
```

### Your Runtime Command or Docker Compose File

Server is managed through portainer, settings are all set per defaults. PGID & PUID are set to 1000

### Debug Output

Run the container with `DEBUG=true` as an environment variable, and it'll print out the system specs requested below, as
well as a bunch of information about your container (version, environment variables, etc.)

```
===== Satisfactory Server 1.9.0 =====
https://github.com/wolveix/satisfactory-server
Debugging enabled (the container will exit after printing the debug info)
Printing environment variables:
declare -x AUTOSAVENUM="5"
declare -x DEBIAN_FRONTEND="noninteractive"
declare -x DEBUG="true"
declare -x DISABLESEASONALEVENTS="false"
declare -x GAMECONFIGDIR="/config/gamefiles/FactoryGame/Saved"
declare -x GAMESAVESDIR="/home/steam/.config/Epic/FactoryGame/Saved/SaveGames"
declare -x HOME="/home/steam"
declare -x HOSTNAME="bd1a0abee806"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US:en"
declare -x LOG="false"
declare -x MAXOBJECTS="2162688"
declare -x MAXPLAYERS="4"
declare -x MAXTICKRATE="30"
declare -x OLDPWD
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
declare -x PGID="1000"
declare -x PUID="1000"
declare -x PWD="/config"
declare -x ROOTLESS="false"
declare -x SERVERGAMEPORT="7777"
declare -x SERVERSTREAMING="true"
declare -x SHLVL="1"
declare -x SKIPUPDATE="false"
declare -x STEAMAPPID="1690800"
declare -x STEAMBETA="false"
declare -x TIMEOUT="30"
declare -x USER="steam"
declare -x VERSION="1.9.0"
declare -x VMOVERRIDE="false"

System info:

OS:  Linux bd1a0abee806 6.4.0-20-default #1 SMP PREEMPT_DYNAMIC Tue Oct  1 10:57:21 UTC 2024 (0e26fa9) x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 7 2700X Eight-Core Processor
RAM: 21GB/32GB
HDD: 148GB/256GB (58% used)

Current version:
1.9.0

Current user:
uid=0(root) gid=0(root) groups=0(root)

Proposed user:
uid=1000(?) gid=1000(?) groups=1000(?)
```
### System Specs (please complete the following information):

If you're on Linux, just paste the following block as a single command, and paste the output here.

```
===== START ISSUE REPORT =====
OS:  Linux container-vm 6.4.0-20-default #1 SMP PREEMPT_DYNAMIC Tue Oct  1 10:57:21 UTC 2024 (0e26fa9) x86_64 x86_64 x86_64 GNU/Linux
CPU: AMD Ryzen 7 2700X Eight-Core Processor
BIOS pc-i440fx-8.0  CPU @ 2.0GHz
RAM: 22GB/32GB
HDD: 148GB/256GB (58% used)
===== END ISSUE REPORT =====
```
OS is actually OpenSuse Leap Micro 6.0

### Logs

```
===== Satisfactory Server 1.9.0 =====
https://github.com/wolveix/satisfactory-server
Checking available memory: 21GB detected
Clearing old Satisfactory logs (set LOG=true to disable this)
Setting autosave number to 5
Setting max objects to 2162688
Setting max tick rate to 30
Setting server streaming to 1
Setting timeout to 30
Setting max players to 4
Checking available storage: 106GB detected
Downloading the latest version of the game...
/home/steam/.local/share/Steam/steamcmd/steamcmd.sh: line 37: /home/steam/.local/share/Steam/steamcmd/linux32/steamcmd: cannot execute binary file: Exec format error
```

### Additional Context

Container is running fine on my local desktop running Windows with the Docker Engine in WSL, just not in linux.

**Comment by Klikini** [comment]
Can confirm, even running the suggested docker command from the README with a brand new bind directory does this.

I created a temporary container using `docker run -it --entrypoint=/bin/bash wolveix/satisfactory-server:v1.8.5 -i` to do some debugging.

I installed `file` and confirmed that the `steamcmd` binary is a 32-bit executable as expected:
```sh
# file .local/share/Steam/steamcmd/linux32/steamcmd

.local/share/Steam/steamcmd/linux32/steamcmd: ELF 32-bit LSB pie executable, Intel 80386, version 1 (GNU/Linux), dynamically linked, interpreter /lib/ld-linux.so.2, BuildID[sha1]=f367ca9da1318412cc9963b213c7ee3a3f2e75e2, for GNU/Linux 2.6.24, not stripped
```

And I made sure the container is running an OS compiled for amd64 (the host has an amd64 CPU):
```sh
# uname -mpi

x86_64 x86_64 x86_64
```

It's been running fine on the exact same host until updating today, could it be related to ffeac26978f0d8433633059206f26d6b05d3644b?

**Comment by wolveix** [comment]
Hey @sconosciute and @Klikini, thanks for reporting this. This is why I'd left merging #334 for so long.

I've just rebased to Ubuntu 22.04 with `v1.9.1`. Please test this, and let me know if you continue to experience issues :)

**Comment by Miles107** [comment]
Outsider here with the same issue, can confirm pulling the latest fixed it and at least have a running server again. Thank you!

**Comment by sconosciute** [comment]
So I'm a little baffled at this point.

On OpenSUSE I still can't get the container to run, same exact exec format error. Now, more oddly: I tried to specify the tag to pull an older version, currently tried v1.8.6. The manifest digest on docker hub (ending in 628d) matches the digest of the image I have locally, but when it runs the log says server version 1.9.1 and spits back out the exec format error. I've tried 1.8.10 and 1.7.0 and while 1.7 doesn't display the version in the log, it still has the same error!

Now when run on our Unraid server or on my desktop through WSL the problem doesn't show up and the server is able to start without issue. Only in our OpenSUSE VM running on Proxmox I am just continually getting that same error. As far as I can tell nothing has changed about the VM or host environment so I'm stumped.

**Comment by wolveix** [comment]
@sconosciute sounds like there's an issue with your Docker environment :) I'd try completely destroying the container, `docker system prune -a` (make sure you have things backed up where necessary), manually remove any straggler Satisfactory images on your machine (if there are any, something above went wrong), and then re-provision

**Comment by sconosciute** [comment]
I’ll have a go at that, thanks!

At least it doesn’t seem like the problem is with the container itself 🎉
