### ISSUE TITLE
Can't start - Permission denied

### ISSUE THREAD

**Issue by voruti** [wolveix/satisfactory-server#44]
**Describe the Bug**
I just entered the command from the README.md (see below - only changed the path) and the container stops right away. (+ same when using the docker-compose.yml file)

**Your Runtime Command or Docker Compose File**
`docker run -d --name=satisfactory-server -h satisfactory-server -v $(pwd)/config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest`

**System Specs:**
 - OS: Debian GNU/Linux 10 (buster)

**Additional Context**
Log:
```
mkdir: cannot create directory '/config/backups': Permission denied,
mkdir: cannot create directory '/config/gamefiles': Permission denied,
mkdir: cannot create directory '/config/saves': Permission denied,
mkdir: cannot create directory '/config/gamefiles': Permission denied,
mkdir: cannot create directory '/config/gamefiles': Permission denied,
mkdir: cannot create directory '/config/gamefiles': Permission denied
```

**Comment by Katorone** [comment]
On my installation, it's the /home/steam directory that's having a permission issue.
`mkdir: cannot create directory '/home/steam/.config': Permission denied
mkdir: cannot create directory '/home/steam/.config': Permission denied
mkdir: cannot create directory '/home/steam/.config': Permission denied
mkdir: cannot create directory '/home/steam/.config': Permission denied`

Exposing /home to my filesystem shows that /home/steam is created as root.

Could you try if something like this solves this issue?
`su -c "mkdir -p /config/{backups,gamefiles,saves}" steam || exit 1
su -c "mkdir -p \"${GAMECONFIGDIR}/{Config/LinuxServer,Logs,SaveGames/server,server}\"" steam || exit 1
`

**Comment by fryfrog** [comment]
I'm experiencing this issue when using `docker run --user uid:gid` which results in `mkdir: cannot create directory '/home/steam/.config': Permission denied` because obviously something like `/home` is not going to allow the `steam` user inside to make folders.

Most Docker images deal w/ this by running as `root` at initialization, then running the actual programs as the UID/GID specified. They use env vars like `-e PUID=1000` and `-e PGID=1000`.

**Comment by wolveix** [comment]
@Katorone the `su` commands won't work as we're running as `steam` which is not a privileged user for security reasons.

We're using the `root` image to sort out permissions issues (which fixes permissions for volumes), and then drop to `steam` before the end of the Dockerfile. The `root` image is the same as `latest`, except it starts as `root` to allow you to make any privileged changes.

**Comment by wolveix** [comment]
> I'm experiencing this issue when using `docker run --user uid:gid` which results in `mkdir: cannot create directory '/home/steam/.config': Permission denied` because obviously something like `/home` is not going to allow the `steam` user inside to make folders.
> 
> Most Docker images deal w/ this by running as `root` at initialization, then running the actual programs as the UID/GID specified. They use env vars like `-e PUID=1000` and `-e PGID=1000`.

Thanks for taking the time to write this out, but please read through this issue. These have already been talked about.

**Comment by Leopoldpaul** [comment]
> Okay, so you'll probably want to `exec` into the container and check the directory. Do this:
> 
> ```shell
> docker exec -it satisfactory-server ls -lah /config/saves
> ```

Okay i got a Workaround for my Problems with running the Server on my Synology NAS.
First i have to start the Docker container in the DSM Docker app with  High Privileges 
Then i have to Set the right Port numbers and set a Volume bind into the /docker dir which is created from the Docker app beacuse in this dir Docker is the owner but i have also to set the folder to allow everyone to write (Im test some things to get rid of this potetial security problem). 
After this everything works perfect.

**Comment by wolveix** [comment]
Ultimately, while it's frustrating, I believe it'll be much less of a headache to just run the container as `root`. I've already made the changes, and they've been pushed to the `:dev` image. I'll be pushing the commit shortly.

**Comment by wolveix** [comment]
This issue should now be resolved.

**Comment by msladek** [comment]
@wolveix I'm running this container in [rootless mode](https://docs.docker.com/engine/security/rootless) without issues. Perhaps it's worth mentioning in the readme under "Known Issues".

**Comment by wolveix** [comment]
As is mentioned elsewhere (within one of the permissions issues), it's largely based on your setup and environment. The existing version of the project works in both environments, the previous version did **not**.
