### ISSUE TITLE
(Suggestion) Disable Update on start

### ISSUE THREAD

**Issue by gartia** [wolveix/satisfactory-server#5]
Seems un-needed to steamcmd update each time you start it, especially if you use steamguard. You'l end up getting rate limited, if you fail the guard code because it keeps restarting due to failing steam guard code.

**Comment by wolveix** [comment]
Hey! Thanks for your feedback :) 

Steam credentials are now cached, which removes the need to re-obtain your Steam Guard code on container rebuild/restart.
