### ISSUE TITLE
groupmod: GID '100' already exists

### ISSUE THREAD

**Issue by XenorPLxx** [wolveix/satisfactory-server#58]
**Describe the Bug**
After update to the new version and setting my PGID and PUID to correct values, I'm getting this error:
`groupmod: GID '100' already exists`

**Your Runtime Command or Docker Compose File**
```
docker run
--name=satisfactory-server
--hostname=openmediavault
--env=MAXPLAYERS=16
--env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin 
--env=PUID=1000
--env=STEAMCMDDIR=/home/steam/steamcmd
--env=GAMECONFIGDIR=/config/gamefiles/FactoryGame/Saved
--env=USER=steam
--env=STEAMBETA=true
--env=DEBUG=false
--env=HOMEDIR=/home/steam
--env=GAMESAVESDIR=/home/steam/.config/Epic/FactoryGame/Saved/SaveGames
--env=STEAMAPPID=1690800
--env=PGID=100
--env=SKIPUPDATE=false
--volume=/etc/localtime:/etc/localtime:ro
--volume=/sharedfolders/AppData/satisfactory-server:/config:rw
--volume=/home/steam/steamcmd
--network=bridge
--workdir=/config
-p 15000:15000/udp
-p 15777:15777/udp
-p 7777:7777/udp
--restart=unless-stopped
--label='maintainer=walentinlamonos@gmail.com'
--runtime=runc
--detach=true
wolveix/satisfactory-server:latest
```

**System Specs (please complete the following information):**
 - OS: Debian GNU/Linux 9.13 (stretch)

**Additional Context**
User used to run containers:
![image](https://user-images.githubusercontent.com/6712823/139536303-8f6eef11-9de9-4d08-b304-2527775bc54d.png)

**Comment by wolveix** [comment]
Hey! Thanks for taking the time to submit the issue.

Out of curiosity, why are you manually setting the `PATH, USER, HOMEDIR` environment variables?

Yeah, so this is due to the group already existing. Trying to think of a simple way to change this behaviour...I could instead set the `steam` user to the group that corresponds to `100` within the container, but then that breaks a a couple of other things. I'll get back to this shortly.

**Comment by XenorPLxx** [comment]
I'm using Docker GUI inside OMV server and I think it set it by default. I've tried starting a fresh instance using command from README (just modyfied the path and GUID), but the same error occurs.

**Comment by wolveix** [comment]
Ah got you. Yeah it will. I've just realised that there's a much simpler way to do this aha. Changing it now! :)

**Comment by XenorPLxx** [comment]
Great, let me know, so I'll test it straight away when it's out :)

**Comment by wolveix** [comment]
Okay, it should be fixed now. Could you try pulling the `:dev` tag?

**Comment by XenorPLxx** [comment]
Yep, I've run the same command using the `:dev` tag, and now it works :).

**Comment by wolveix** [comment]
Great! I'll push the commit now. Thanks for your help!
