### ISSUE TITLE
Unable to start Server "usermod: permission denied"

### ISSUE THREAD

**Issue by ninjaharibo** [wolveix/satisfactory-server#65]
I have been running the server for 3 days without issue,  overnight the server started having these permission issues, all the logs show is:

```bash
usermod: Permission denied.
usermod: cannot lock /etc/passwd; try again later.
```

I have done the troubleshooting on the above error by searching for locked files and checking storage size, I have tried creating a new user to run as and get the same issues, as well as creating a new config file location to start the server from but continue to get the above.

I have recreated the compose file and container also to try and resolve, when also trying "sudo docker logs satisfactory-server" I get the above error 

Any ideas/help would be greatly appreciated 👍 

Running  Ubuntu 20.04.3 LTS

version: '3'
services:
  satisfactory-server:
      container_name: 'satisfactory-server'
      hostname: 'satisfactory-server'
      image: 'wolveix/satisfactory-server:latest'
      ports:
          - '7777:7777/udp'
          - '15000:15000/udp'
          - '15777:15777/udp'
      user: '1000'
      volumes:
          - /home/ninja/.docker/plex/config:/config
      environment:
            - MAXPLAYERS=16
            - STEAMBETA=false
      restart: unless-stopped

**Comment by wolveix** [comment]
Hmm. That's a first! Have you tried deleting the container and rebuilding it?

```bash
docker-compose down
docker-compose up -d
```

**Comment by wolveix** [comment]
Oh I see the issue! Remove the following line from your Docker Compose file:
```bash
user: '1000'
```

And add the following environment variables:
```bash
PGID=1000
PUID=1000
```

**Comment by ninjaharibo** [comment]
Awesome, thanks alot all working now :D

**Comment by wolveix** [comment]
Lovely stuff! I've pushed a change that adds a notice to avoid this happening in the future :)

Thanks for your help!
