### ISSUE TITLE
Unable to start server

### ISSUE THREAD

**Issue by HideAwayDk** [wolveix/satisfactory-server#68]
Hey :D 

I'm trying to run this docker on my synology (xpenology) but no matter what i try it always end with this:

LogOnline: Warning: OSS: EOSSDK-LogEOSP2P: NAT Detection failed, unable to resolve host
LogOnline: Warning: OSS: EOSSDK-LogEOSAnalytics: EOS SDK Analytics disabled for route [1].
LogOnline: Warning: OSS: EOSSDK-LogEOSEcom: Purchase flow is disabled due to overlay setup failure (EOS_NotConfigured).

Sorry I'm kinda new do docker / linux

**Comment by HideAwayDk** [comment]
Yeah that's where i have a problem, on synology i do have a run command but it wont allow me to use what you said to use it the guide

Here is the log, i will try the run command again and see what it say
[Crash.txt](https://github.com/wolveix/satisfactory-server/files/7456186/Crash.txt)

**Comment by wolveix** [comment]
In what way? Please be more specific. I can't help you with vague details. I do not personally own a Synology device; however, many other users have reported great success with their Synology devices.

**Comment by wolveix** [comment]
Also, could you please paste the start and finish of a log, rather than a mixed log. It just makes troubleshooting a bit easier!

**Comment by HideAwayDk** [comment]
sorry i know im not great at giving you the details, i just thout this will be easy :) i host an minecraft server and Valheim server over docker with no problems...
The log is how it is posted to me from the interface i can export it in HTML but cant attach HTML, 
I did Attach pictures of my settings, hope you can use it otherwise i have to wait to a more skilled person can make an synology guide i can use :
![folder](https://user-images.githubusercontent.com/7749454/139745592-249f2a7f-8254-41f
![config2](https://user-images.githubusercontent.com/7749454/139745613-f8e009af-952e-4b1e-8adf-78d8fb4e9f58.jpg)
0
![config1](https://user-images.githubusercontent.com/7749454/139745605-5f3bf6ab-d475-4055-9613-add159941109.jpg)
-9577-906d196
![ports](https://user-images.githubusercontent.com/7749454/139745599-9a564a2f-8e76-4333-8d9c-efcddc3179fb.jpg)
2f977.jpg)
)

**Comment by wolveix** [comment]
It's all good! It's just a bit frustrating when I can't help due to a lack of information :)

Are you sure your `PGID` and `PUID` fields are correct?

**Comment by HideAwayDk** [comment]
I know ! and iam really sorry iam not more knowledgeable into this !
yes iam sure that is correct
![uid](https://user-images.githubusercontent.com/7749454/139746855-4207ec4d-ae40-4101-a644-b62d3352b21d.jpg)

**Comment by HideAwayDk** [comment]
But again iam sure iam doing something wrong, and not that your work is not working, guess i have to wait until an synology expert is coming by :D

**Comment by wolveix** [comment]
I've only just been able to properly view your log. It doesn't look like it's crashing? If the container isn't stopping, then it's running as expected and you'll be able to connect to it from Satisfactory `experimental` (not `early access`)

**Comment by HideAwayDk** [comment]
OMG its working now ! im so sorry to waste your time :(

**Comment by HideAwayDk** [comment]
Thanks again for your time and work !
