### ISSUE TITLE
Could not bind address '0.0.0.0:15777'. Server cannot continue initialization

### ISSUE THREAD

**Issue by eeeeb** [wolveix/satisfactory-server#70]
**Describe the Bug**
When starting the docker container there seems to be an issue with binding the address that stops the startup process. On a first glance the log entries before that look normal.
> Could not bind address '0.0.0.0:15777'. Server cannot continue initialization.

I am running other containers on the server without any issues. Also I checked the port 15777 is not used.
Any idea what the issue could be?

**Log file**

> ....
> [2021.11.03-22.23.01:138][  0]LogPakFile: Precache HighWater 16MB
> [2021.11.03-22.23.01:138][  0]LogPakFile: Precache HighWater 32MB
> [2021.11.03-22.23.01:138][  0]LogPakFile: Precache HighWater 48MB
> [2021.11.03-22.23.01:138][  0]LogPakFile: Precache HighWater 64MB
> 
> Fatal error: [File:D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Server/FGServerQuerySocket.cpp] [Line: 25] 
> 
> Could not bind address '0.0.0.0:15777'. Server cannot continue initialization.
> 
> Signal 11 caught.
> 
> Malloc Size=65538 LargeMemoryPoolOffset=65554 
> 
> [2021.11.03-22.23.01:138][  0]LogNiagara: Warning: NiagaraSystem /Game/FactoryGame/VFX/World/AmbientLife/Flies/NS_Fireflies_01.NS_Fireflies_01 IsReadyToRunInternal() failed due to missing SystemScript.  Spawn[<none>] Update[<none>]
> 
> [2021.11.03-22.23.01:138][  0]LogNiagara: Warning: NiagaraSystem /Game/FactoryGame/VFX/World/AmbientLife/Bats/NS_Bats_01.NS_Bats_01 IsReadyToRunInternal() failed due to missing SystemScript.  Spawn[<none>] Update[<none>]
> 
> [2021.11.03-22.23.01:216][  0]GameAnalyticsModule: Display: GameAnalyticsModule has started!
> 
> [2021.11.03-22.23.01:216][  0]LogStreaming: Warning: Failed to read file '../../../FactoryGame/Saved/SaveGames/GameAnalytics.sav' error.
> 
> [2021.11.03-22.23.01:303][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
> 
> [2021.11.03-22.23.01:303][  0]LogAudioCaptureCore: Display: No Audio Capture implementations found. Audio input will be silent.
> 
> [2021.11.03-22.23.01:320][  0]LogUObjectArray: 49700 objects as part of root set at end of initial load.
> 
> [2021.11.03-22.23.01:320][  0]LogUObjectArray: 2 objects are not in the root set, but can never be destroyed because they are in the DisregardForGC set.
> 
> [2021.11.03-22.23.01:320][  0]LogUObjectAllocator: 15807376 out of 0 bytes used by permanent object pool.
> 
> [2021.11.03-22.23.01:320][  0]LogUObjectArray: CloseDisregardForGC: 49700/49700 objects in disregard for GC pool
> 
> [2021.11.03-22.23.01:320][  0]LogEngine: Initializing Engine...
> 
> [2021.11.03-22.23.01:321][  0]LogStats: UGameplayTagsManager::InitializeManager -  0.001 s
> 
> [2021.11.03-22.23.01:326][  0]LogInit: Initializing FReadOnlyCVARCache
> 
> [2021.11.03-22.23.01:326][  0]LogNetVersion: Set ProjectVersion to 0.0.1.0. Version Checksum will be recalculated on next use.
> 
> [2021.11.03-22.23.01:326][  0]LogInit: Texture streaming: Disabled
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: OSS: Creating online subsystem instance for: STEAM
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Warning: STEAM: Steam API failed to initialize!
> 
> [2021.11.03-22.23.01:344][  0]LogOnline: Display: STEAM: OnlineSubsystemSteam::Shutdown()
> 
> CommonUnixCrashHandler: Signal=11
> 
> [2021.11.03-22.23.01:358][  0]LogCore: === Critical error: ===
> 
> Unhandled Exception: SIGSEGV: invalid attempt to write memory at address 0x0000000000000003
> 
> [2021.11.03-22.23.01:358][  0]LogCore: Fatal error: [File:D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Server/FGServerQuerySocket.cpp] [Line: 25] 
> 
> Could not bind address '0.0.0.0:15777'. Server cannot continue initialization.
> 
> 0x00007f1910d26665 libUE4Server-FactoryGame-Linux-Shipping.so!FServerQuerySocket::Init() [D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Server/FGServerQuerySocket.cpp:25]
> 
> 0x00007f194005aa14 libUE4Server-Core-Linux-Shipping.so!FRunnableThreadPThread::Run() [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:16]
> 
> 0x00007f1940022d63 libUE4Server-Core-Linux-Shipping.so!FRunnableThreadPThread::_ThreadProc(void*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.h:185]
> 
> 0x00007f1940620fa3 libpthread.so.0!UnknownFunction(0x7fa2)
> 
> 0x00007f193c4954cf libc.so.6!clone(+0x3e)
> 
> 0x00007f1940003eb6 libUE4Server-Core-Linux-Shipping.so!FGenericPlatformMisc::RaiseException(unsigned int) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/GenericPlatform/GenericPlatformMisc.cpp:472]
> 
> 0x00007f194019f32b libUE4Server-Core-Linux-Shipping.so!FOutputDevice::LogfImpl(char16_t const*, ...) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/Misc/OutputDevice.cpp:61]
> 
> 0x00007f1910d26665 libUE4Server-FactoryGame-Linux-Shipping.so!FServerQuerySocket::Init() [D:/ws/SB-160502110050-fad/UE4/Games/FactoryGame/Source/FactoryGame/Private/Server/FGServerQuerySocket.cpp:25]
> 
> 0x00007f194005aa14 libUE4Server-Core-Linux-Shipping.so!FRunnableThreadPThread::Run() [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.cpp:16]
> 
> 0x00007f1940022d63 libUE4Server-Core-Linux-Shipping.so!FRunnableThreadPThread::_ThreadProc(void*) [D:/ws/SB-160502110050-fad/UE4/Engine/Source/Runtime/Core/Private/HAL/PThreadRunnableThread.h:185]
> 
> 0x00007f1940620fa3 libpthread.so.0!UnknownFunction(0x7fa2)
> 
> 0x00007f193c4954cf libc.so.6!clone(+0x3e)
> 
> [2021.11.03-22.23.01:370][  0]LogExit: Executing StaticShutdownAfterError
> 
> Engine crash handling finished; re-raising signal 11 for the default handler. Good bye.
> 
> /home/steam/run.sh: line 51:    76 Segmentation fault      Engine/Binaries/Linux/UE4Server-Linux-Shipping FactoryGame -log -NoSteamClient -unattended

**Your Runtime Command or Docker Compose File**
sudo docker run -d --name=satisfactory-server -h satisfactory-server -e MAXPLAYERS=16 -e STEAMBETA=false -v /home/USER/portainer_container_data/satisfactory_dedicated_server/config:/config -p 7777:7777/udp -p 15000:15000/udp -p 15777:15777/udp wolveix/satisfactory-server:latest

**Docker image used**
https://hub.docker.com/layers/wolveix/satisfactory-server/latest/images/sha256-72b185068bb0944fb3650c23077c5a29d4608687a9a0f816c2a5cc976e1f12a7?context=explore

**System Specs (please complete the following information):**
OS: Ubuntu Server 20.04 x86_64

**Comment by jb-dijkstra** [comment]
This actually is a bug in the new update for Satisfactory. The solution is to add the command line option "-multihome=0.0.0.0" where the IP address would be an environment variable so you can set it to whatever you want.

**Comment by wolveix** [comment]
The latest commit should fix this. It was caused by an update to the game server :) It will take a few minutes for the image to build, so try it in a few minutes.

**Comment by wolveix** [comment]
> This actually is a bug in the new update for Satisfactory. The solution is to add the command line option "-multihome=0.0.0.0" where the IP address would be an environment variable so you can set it to whatever you want.

This has been implemented by default :)
