### ISSUE TITLE
Changelog and versionning system ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [wolveix/satisfactory-server#77]
Hi there,

Again, I'm still grateful for your work ;). It would be great to have 2 things : 

- A versionning system 
- A changelog

I didn't see the fix for the last build : https://github.com/wolveix/satisfactory-server/commit/bc2733992892a7ccdd8809c6591988592864b821 

Regards,

**Comment by wolveix** [comment]
Versioning is now implemented, curtesy of @thijsvanloef :D 

I'm torn about the changelog. I think I'll add a `CHANGELOG` file to the repo, but suggestions are welcome.

**Comment by Jeoffreybauvin** [comment]
A changelof file to the repo should be fine :).

**Comment by wolveix** [comment]
Gonna close this and add a changelog file in the next feature-related release :) Versioning is already implemented :D
