### ISSUE TITLE
Needs and update

### ISSUE THREAD

**Issue by skluthe** [wolveix/satisfactory-server#78]
Hey, looks like the workflow needs to be triggered. If anyone is stuck, clone this repo, run `docker build -t wolveix/satisfactory-server .` and then you can use your `docker run` command or run `docker-compose up -d` in the directory with your docker-compose.yml.

**Comment by wolveix** [comment]
The latest image built fine?

**Comment by wolveix** [comment]
Not sure why you were encountering an issue. Either way, I've just pushed an unrelated commit, so the workflow will be triggered regardless.

**Comment by skluthe** [comment]
Sorry about not responding. It hadn't updated on dockerhub for the latest update from yesterday for some reason. All is good now though.

**Comment by wolveix** [comment]
No problem. I checked Docker Hub prior to responding here, and the updated timestamp corresponded with the latest commit and workflow/action. So I'm not sure why you were seeing an older image. Regardless, at least it's sorted now!
