### ISSUE TITLE
Automatic Restarts / Updates

### ISSUE THREAD

**Issue by zackhorvath** [wolveix/satisfactory-server#79]
Hey there,

Firstly, thanks for putting this together. I've written a cronjob to handle server restarts on a set time (congruent with the official dev recommendation of daily or bi-daily restarts), but I was wondering if it were possible to add in a switch to the container to check the steam API for AppID updates on a scheduled basis, and if so, gracefully kill the container so that it can be auto-restarted and grab the update.

If you're accepting PRs I could noodle on it as well, but figured you guys already had plans for that.

Thanks!

**Comment by wolveix** [comment]
Hey!

Thanks for the kind words, and for taking the time to open this issue :) PRs are *always* welcome! 

I love the idea; however, I'm quite busy right now with starting a new job. If you have the time to work on it, I'd happily review your work and merge the PR 😎

**Comment by bartkodden** [comment]
@zackhorvath I have watchtower running on my docker machine (synology nas). It does exactly what you want for all my containers.

**Comment by ArthurEnglebert** [comment]
I feel like if we want to respect docker logic, we should have a distinct image per available build of SF-DS.
And you would just switch the image tag when you which to upgrade (the save file are obviously saved in a mounted volume).

If you want your server to upgrade, this shouldn't be decided by the image itself.
Never you will see on big projects a nginx docker image updating its version itself.

For me, it's the concern of the container orchestrator (k8s) or an external system (a process on the host stopping said docker to span the freshly downloaded new image).

**Comment by wolveix** [comment]
Right, and that's fine and all @ArthurEnglebert, except for the fact that I don't maintain Satisfactory, so am unable to push an image per update. Not to mention how large the image sizes would be if we included the gamefiles directly.

The middle ground in my opinion would be to add the functionality to the image to specify the depot version of the game files. PRs are always welcome in that regard. This is out of scope for this specific issue, though.

For this specific issue, I believe that @bartkodden addressed this well enough. I believe that this is the responsibility of the orchestrator/environment and not the image itself.

**Comment by ArthurEnglebert** [comment]
Yeahhh, kinda forgot that the server files are 10Gb. when writing this comment, my bad.

**Comment by wolveix** [comment]
@ArthurEnglebert no worries! I completely agree with you otherwise, it just doesn't work in this scenario unfortunately.
