### ISSUE TITLE
Usage on K8S/GKE ?

### ISSUE THREAD

**Issue by sadortun** [wolveix/satisfactory-server#83]
Heyy @wolveix !

Would you be interested if I submit a PR with K8s config files to get this lovely container running on Kubernetes? 

Got everything working a few days ago !

**Comment by wolveix** [comment]
Hey! 

Yeah sure thing :D I'd recommend placing the `YAML` files under a `cluster/` directory :) Submit a PR and I'll be sure to review it!

**Comment by starcraft66** [comment]
@sadortun Have you gotten around to doing this yet? I'm trying to get this up and running on my homelab k8s cluster and I can only access the server if I connect directly to the pod. Connecting to a `LoadBalancer` ip address directing the traffic to my satisfactory `StatefulSet` leads to the client saying the server is offline.

**Comment by sadortun** [comment]
Hey @starcraft66 !

Yep, I got it running well! I haven't prepared a PR yet, but send me an email (see my profile)  and I'll send you the YML tomorow.

**Comment by starcraft66** [comment]
Thanks for the offer! I got it running in the end. It turns out some major stuff was broken in my network setup and the IPv6 routes originated from my cluster weren't making it to the internet. Essentially, my IPv6 was totally broken. I tweaked the BGP and OSPF configurations on one of my routers and everything connected right up.

**Comment by wolveix** [comment]
@sadortun thanks again for offering to supply your configuration files for k8s usage :) Are you still willing to do this and submit a PR?

**Comment by sadortun** [comment]
@wolveix yep! I'll do it as soon as I get a free minute !

**Comment by mitchellmaler** [comment]
Hi, I created a PR with my resource manifests I am using to deploy this image. 
https://github.com/wolveix/satisfactory-server/pull/98
