### ISSUE TITLE
Make sure that your X server is running and that $DISPLAY is set correctly

### ISSUE THREAD

**Issue by ghzatomic** [wolveix/satisfactory-server#89]
**Describe the Bug**
When i start the docker server, on the moment of start server, a problem with the X Server and display is triggered

**Your Runtime Command or Docker Compose File**
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:v4'
        environment:
            - DISPLAY=:0.0
            - STEAMUSER=asdas
            - STEAMPWD=asdas
            - STEAMCODE=asdas
            - MAXBACKUPS=10
            - STEAMBETA=false
        ports:
            - '7777:7777/udp'
        volumes:
            - './config:/config'
        restart: unless-stopped

**System Specs (please complete the following information):**
Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux

**Additional Context**
satisfactory-server    | force_install_dir /config/gamefiles
satisfactory-server    | Please use force_install_dir before logon!
satisfactory-server    | app_update "526870"
satisfactory-server    | Success! App '526870' already up to date.
satisfactory-server    | quit
satisfactory-server    |  * Starting periodic command scheduler cron
satisfactory-server    |    ...done.
satisfactory-server    | 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
satisfactory-server    | 0014:err:ole:marshal_object couldn't get IPSFactory buffer for interface {6d5140c1-7436-11ce-8034-00aa006009fa}
satisfactory-server    | 0014:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
satisfactory-server    | 0014:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
satisfactory-server    | 0014:err:ole:get_local_server_stream Failed: 80004002
satisfactory-server    | 000b:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 000b:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | 0012:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 0012:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | 0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
satisfactory-server    | 0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 0
satisfactory-server    | 0012:err:ole:marshal_object couldn't get IPSFactory buffer for interface {00000131-0000-0000-c000-000000000046}
satisfactory-server    | 0012:err:ole:apartment_createwindowifneeded CreateWindow failed with error 14007
satisfactory-server    | 0012:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x800736b7
satisfactory-server    | 0012:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 800736b7
satisfactory-server    | 0012:err:ole:get_local_server_stream Failed: 800736b7
satisfactory-server    | 0010:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 0010:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | Could not load wine-gecko. HTML rendering will be disabled.
satisfactory-server    | 0028:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 0028:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | Could not load wine-gecko. HTML rendering will be disabled.
satisfactory-server    | wine: configuration in '/home/satisfactory/.wine' has been updated.
satisfactory-server    | 002e:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 002e:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | 0036:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 0036:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
satisfactory-server    | 0035:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
satisfactory-server    | 0035:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.

**Comment by csreynolds** [comment]
> - DISPLAY=:0.0

Take that line out of your compose file. Should be fine after that.

**Comment by ghzatomic** [comment]
Hello @csreynolds, thanks for your comment, but i just put this line to try solve this same problem, but, no way =(

**Comment by ghzatomic** [comment]
That started when the update to v5 game was released

**Comment by Roobird** [comment]
I guess the problem is that update 5 is now also available on the stable early access branch. So the 'image: 'wolveix/satisfactory-server:v4' is quite outdated. To fix this, @wolveix would probably need to rebuild and push a new image with the latest update 5 release to dockerhub.

**Comment by wolveix** [comment]
@Roobird this repo's primary focus is already update 5.

As update 5 is now in early access, the update 4 branch serves no purpose, and will be deleted. 

@ghzatomic please update to update 5 and use the `main` branch.
