### ISSUE TITLE
Issues downloading Experimental v174005

### ISSUE THREAD

**Issue by bodybybuddha** [wolveix/satisfactory-server#95]
Getting Version mismatch on game and server:
Game Version : 174005
Server Version: 173879

Running Docker-compose with the following configuration:
version: '3'
services:
    satisfactory-server:
        container_name: 'satisfactory-server'
        hostname: 'satisfactory-server'
        image: 'wolveix/satisfactory-server:latest'
        ports:
            - '7777:7777/udp'
            - '15000:15000/udp'
            - '15777:15777/udp'
        volumes:
            - '/Users/myuserid/SatisfactoryServer/config:/config'
        environment:
            - PGID=20
            - PUID=501
            - SKIPUPDATE=false
            - MAXPLAYERS=16
            - STEAMBETA=true
        restart: unless-stopped

Running on Mac OS 10.15.1 with Docker Desktop v4.1.1 

Noticed the repo changed a few hours ago and I was hoping that would fix the problem, no joy.  

I can't seem to download the latest experimental version - unfortunately, the client updated so none of my users can log in.

any thoughts?

**Comment by msladek** [comment]
Probably related to https://github.com/wolveix/satisfactory-server/pull/93

Have you tried the image `wolveix/satisfactory-server:dev`?

**Comment by bodybybuddha** [comment]
Yup - the dev version worked.  I made the assumption that since the repo was updated, the images were updated.  I didn't look for a dev tag.

Thank you!

@wolveix - thanks for the repo!
