### ISSUE TITLE
Container not gracefully shutting down on SIGTERM and is being killed instead

### ISSUE THREAD

**Issue by mitchellmaler** [wolveix/satisfactory-server#99]
**Describe the Bug**
Running in a k8s environment when I delete (stop) the pod it does not show anything in the log that it is shutting down. I believe pid1 is not steamcmd so it does not know to stop the server.

**Your Runtime Command or Docker Compose File**
Kubernetes Statefulset (I logged a PR with the gist of it)

**System Specs (please complete the following information):**
- N/A

**Additional Context**
Usually when this happens it is due to subshells running the process. Looks like the init.sh calls run.sh so the SIGTERM is most likely only being sent to the init.sh process. One option is to add a trap to the init.sh to capture this but would need to test that it works.

**Comment by wolveix** [comment]
Thanks for taking the time to open this issue!

In truth, I'm unfamiliar with the concept of trapping. I assumed that as `init.sh` calls `run.sh` which calls the Satisfactory binary, `SIGTERM` would be carried up the chain.

I'd appreciate some additional insight/your help into resolving this issue!

**Comment by mitchellmaler** [comment]
Unfortunately the signal is not send down and the init.sh is the only process that receives it. I am thinking if a signal trap is added to the init.sh script that then calls something like `killall UE4Server-Linux-Shippingcommand` which will tell the engine to exit cleanly. I'll see if I can get this added in a PR.

**Comment by wolveix** [comment]
@bewing but then from a user standpoint, it'll cause issues in the future should they want to change the user on the host. I understand from a technical standpoint that that's a non-issue, but as I've mentioned in other issues, this repo needs to be as user-friendly as possible. 

I believe that there's a better way to solving this issue without skipping `run.sh` on subsequent runs.

**Comment by rawrgulmuffins** [comment]
I built a dedicated server to run satsifactory for a group of friends last night.

Today one of our players tried to log in to find that there was an update.

![image0](https://user-images.githubusercontent.com/1521575/144342797-a0619199-c51d-4626-95b0-f9d3ae879166.jpeg)

I saw that I just needed to restart the container to get an update installed but  I made the mistake of using `docker kill` instead of `docker stop`

```
CONTAINER ID   IMAGE                                COMMAND      CREATED        STATUS        PORTS
                                                      NAMES
8b89e761b299   wolveix/satisfactory-server:latest   "/init.sh"   21 hours ago   Up 21 hours   0.0.0.0:7777->7777/udp, :::7777->7777/udp, 0.0.0.0:15000->15000/udp, :::15000->15000
/udp, 0.0.0.0:15777->15777/udp, :::15777->15777/udp   satisfactory-server
[ec2-user@ip-172-31-41-212 ~]$ docker kill 8b89e761b299
8b89e761b299
```

And after doing a `docker run` on the image again

```
[ec2-user@ip-172-31-41-212 ~]$ docker run 0d140fe1f2f2
Setting max players to 16
Setting crash reporting to True
Checking available space...4GB detected
You have less than 5GB (4GB detected) of available space to download the game.
If this is a fresh install, it will probably fail.
Downloading the latest version of the game...
Redirecting stderr to '/home/steam/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
# Lots and lots of text
[2021.12.02-01.33.06:705][  0]LogOnline: Warning: OSS: [EOS SDK | Plugin] Begin Player Session...
[2021.12.02-01.33.06:705][  0]LogInit: Display: Game Engine Initialized.
[2021.12.02-01.33.06:705][  0]LogNetVersion: Set ProjectVersion to ++FactoryGame+rel-main-0.5.0-CL-174686. Version Checksum will be recalculated on next use.
[2021.12.02-01.33.06:705][  0]LogConsoleResponse: Display: Can't switch to RHI thread mode when we are not running a multithreaded renderer.
[2021.12.02-01.33.06:705][  0]LogConsoleResponse: Display: RHIThread is disabled.
[2021.12.02-01.33.06:706][  0]LogInit: OnPostEngineInit has been broadcasted successfully.
[2021.12.02-01.33.06:716][  0]LogInit: Display: Starting Game.
[2021.12.02-01.33.06:716][  0]LogNet: Browse: /Game/FactoryGame/Map/DedicatedserverEntry?name=Host?sessionName=SatisfactoryServer?Visibility=SV_FriendsOnly?loadgame=savefile?listen?bUseIpSockets
[2021.12.02-01.33.06:717][  0]LogLoad: LoadMap: /Game/FactoryGame/Map/Dedicatedser
```

I'm getting the `Starting Game` message but I'm not able to connect to the server through Server Manager In Satisfactory anymore. 

I was wondering if this has to do with the lack of a graceful shutdown that's specified here.

I went back and did a `docker start` as well of the original image to no effect

```
[ec2-user@ip-172-31-41-212 ~]$ docker ps -a
CONTAINER ID   IMAGE                                COMMAND      CREATED          STATUS                        PORTS     NAMES
e3456953673f   0d140fe1f2f2                         "/init.sh"   27 minutes ago   Exited (137) 3 minutes ago              peaceful_saha
dd1c8fd3c130   0d140fe1f2f2                         "/init.sh"   38 minutes ago   Exited (137) 27 minutes ago             serene_bhaskara
8b89e761b299   wolveix/satisfactory-server:latest   "/init.sh"   21 hours ago     Exited (137) 40 minutes ago             satisfactory-server
[ec2-user@ip-172-31-41-212 ~]$ docker start 8b89e761b299
8b89e761b299
```

To the same `This Server Appears To Be Down` Mesasge.

**Comment by wolveix** [comment]
Yeah, you should have done a simple `docker restart`. 

The lack of graceful shutdown wouldn't have made much of a difference here, particularly as you used `kill`. Is the container stopping itself? Or does it continue to run? If it continues to run, try removing your config and launching the container again. It should then launch, allowing you to upload your save and reconfigure anything else.

9/10 times someone reports an issue like this, it's purely down to a networking fault somewhere down the line. I must admit that I don't believe this to be the case with your specific issue; however, it's still worth keeping it in mind. If my comment doesn't resolve your issue, please open a new issue and fill out the issue template.

**Comment by bewing** [comment]
> @bewing but then from a user standpoint, it'll cause issues in the future should they want to change the user on the host. I understand from a technical standpoint that that's a non-issue, but as I've mentioned in other issues, this repo needs to be as user-friendly as possible.
> 
> I believe that there's a better way to solving this issue without skipping `run.sh` on subsequent runs.

Just found this today, might be an approach?  https://github.com/tianon/gosu

Appears to be used by other containers as well: https://github.com/docker-library/redis/blob/a04a6df0a45894e1a630db4e84e0c12c7bcf326a/6.2/Dockerfile#L8
